### ISSUE TITLE
heap_dump_genere in translations_zh.properties is wrong

### ISSUE THREAD

**Issue by VicBao** [javamelody/javamelody#1]
translations_zh.properties
 
like
heap_dump_genere = \u3000\u5806\u5783\u573E\u573A\u4E2D\u4EA7\u751F\u7684\u3000\u3000{0}\u3000\u3000\u3000\u3000\u4ED6\u53EF\u4EE5\u4ECEJDK or with MAT d'Eclipse.\u88ABjVisualVM or jhat \u6253\u5F00

**Comment by evernat** [comment]
I do not understand what is needed.
What should be written instead?

**Comment by VicBao** [comment]
Now "{ 0 }" ,there is blank between "{" and "0", JDK exception.

**Comment by evernat** [comment]
This was fixed as said at:
https://code.google.com/p/javamelody/issues/detail?id=453
