### ISSUE TITLE
The "View http sessions" and "Invalidate http sessions" links are missing 

### ISSUE THREAD

**Issue by backaly** [javamelody/javamelody#1010]
We upgraded to version 1.80 some time ago and noticed that the link that used to appear at the bottom of the page is no longer there. The link used to go to _?part=sessions_.  I searched through the outstanding tickets and did not see this reported or if there is a new setting necessary to enable this and the _Invalidate http sessions_ link that is also missing?

![JavaMelody-MissingSessionLink](https://user-images.githubusercontent.com/83081228/117201067-3767bd80-adba-11eb-8bd8-3db17f99cc45.png)

We haven't upgraded to the latest build but will do so and report if it is still an issue. Just curious if anyone is aware of this.

**Comment by evernat** [comment]
I suppose that you have added the javamelody MonitoringFilter in the WEB-INF/web.xml of your webapp and that you have forgotten to add the javamelody SessionListener next to the MonitoringFilter.
Do you confirm?

**Comment by evernat** [comment]
No response from the reporter so closing as incomplete.
