### ISSUE TITLE
Add offline mode for offline usage or restricted access scenarios

### ISSUE THREAD

**Issue by StefanPenndorf** [javamelody/javamelody#1011]
When using the "dependency view" for maven projects javamelody tries to load `pom.xml` files from Maven Central to gather information about all (transitive) dependencies. Unfortunately this is not possible in all environments. Some of our clients deny access from applications within their datacenter _to_ the outside world (only incoming http requests may be processed). Additionally some artifacts cannot be resolved in central because they have been loaded from another maven repository or require access to a private repository.

Loading the dependency page (e.g. `/monitoring/?part=dependencies&format=xml`) takes long because requests to maven central need to timeout after 20s before next dependency will be tried. I'm aware that the dependency information will be incomplete when remote access is not available.

**Enhancement Request**
It would be nice to have an offline-mode that skips the HTTP requests that are failing either way to speedup page loading. Currently I'm only interested in our own dependencies that ship with a pom in the `*.jar` file thus all the information can be provided without scanning maven central.

**Comment by evernat** [comment]
You can set the maven-repositories parameter to an empty string or to a local directory in order to be offline for Maven pom searching in this "Dependencies" page.
For that you can set it in system properties (`-Djavamelody.maven-repositories= `) or in web.xml for example:
```xml
<context-param>
   <param-name>javamelody.maven-repositories</param-name>
   <param-value></param-value>
</context-param>
```
