### ISSUE TITLE
Graphs are not loading..Error in console

### ISSUE THREAD

**Issue by KanagarajGanapathy** [javamelody/javamelody#1019]
Javamelody graphs are not loading also noticed java script error when loading this page. Tried with latest javamelody version still the issues persists. See attachment for error log.

![image](https://user-images.githubusercontent.com/18610422/119217611-f204f900-baf8-11eb-9b3a-40cc44cd1e18.png)

**Comment by evernat** [comment]
The calls to resources such as .../monitoring?monitoring.css fail and it seems that they return html instead, such as an authentication page.
If refreshing the page does not work, open .../monitoring?monitoring.css by yourself in a browser and see what it is.
According to that, I suggest to see in your application or in any proxies what is blocking.

**Comment by KanagarajGanapathy** [comment]
When i access the /monitoring?monitoring.css , it returns the following page.
![image](https://user-images.githubusercontent.com/18610422/119232034-4fbd3380-bb41-11eb-9236-ee959145e2e6.png)
Having the below console error.
![image](https://user-images.githubusercontent.com/18610422/119232056-61064000-bb41-11eb-8542-1e4a6233d24a.png)

**Comment by evernat** [comment]
sorry, I should have written .../monitoring?resource=monitoring.css like in the screenshot.
Can you try with that?

**Comment by KanagarajGanapathy** [comment]
facing the same issues with this url:https://rqi.dok-re7.intra.renault.fr/api/monitoring?resource=monitoring.css

same javascript error in console.
![image](https://user-images.githubusercontent.com/18610422/119254611-e25ae280-bbd4-11eb-9f09-92c64d0ac81d.png)

![image](https://user-images.githubusercontent.com/18610422/119254618-f3a3ef00-bbd4-11eb-943d-fb1885bc4c90.png)

**Comment by evernat** [comment]
ok, the content returned for .../monitoring?resource=monitoring.css is the monitoring page itself instead of the resource, like if the resource parameter was not present in the url. And it seems to be the same for the graph parameter.
I do not understand what is modifiying the request to .../monitoring?resource=monitoring.css.
Can you create and give the source of a project to reproduce the issue?

**Comment by KanagarajGanapathy** [comment]
In our local system it is working, problem only after deployed in server.

**Comment by evernat** [comment]
Can you create and give the source of a project to reproduce the issue?

**Comment by KanagarajGanapathy** [comment]
we could not reproduce the issue in our local environment....Chart not loading image faced only after deployment in server only...Also we try add the same in collective server getting above attached error message.

As you said , it might be issue with proxy..Do we have any specific configurations for setting proxy's ?

**config in application.properties:**
javamelody.enabled:true
javamelody.init-parameters.authorized-users:admin:admin

**dependency:**

<dependency>
			<groupId>net.bull.javamelody</groupId>
			<artifactId>javamelody-spring-boot-starter</artifactId>
			<version>1.87.0</version>
		</dependency>
