### ISSUE TITLE
CommonsPool2TargetSource release target throw exception Returned Object is not part of this pool

### ISSUE THREAD

**Issue by shakunahuja** [javamelody/javamelody#1020]
With Spring profiling enabled,CommonsPool2TargetSource release method throw exception Returned Object is not part of this pool 
as the hash of the thread has been changed to newer one.

**Comment by evernat** [comment]
Can you give the source of a project and a scenario to reproduce the issue?

**Comment by shakunahuja** [comment]
Sorry for the delay in response.Attaching the same for reference

**Comment by shakunahuja** [comment]
Any update?

**Comment by evernat** [comment]
I see no source of a project neither a scenario to reproduce the issue.
Can you give the source of a project and a scenario to reproduce the issue?

**Comment by shakunahuja** [comment]
Sorry, I have attached the source earlier but don't know why it failed to attach, I will attach the source again and confirm to you.

**Comment by shakunahuja** [comment]
[javamelody-pool2-issue.zip](https://github.com/javamelody/javamelody/files/6763778/javamelody-pool2-issue.zip)
Please find attached file.

**Comment by evernat** [comment]
That's normal. Spring+javamelody create proxy to monitor objects. So if you say to monitor the executions of the method `run` of `TestRunnable` either using `@MonitoredWithSpring` or using `@Service` which are monitored automatically, then a proxy of the object is created. And you use once the proxy as target of `CommonsPool2TargetSource` and once `this`, which is not the proxy, to release that target. That fails of course.

In summary, the monitored proxy of `TestRunnable` is not the same as `this` in `TestRunnable`.

You should not mix monitoring proxies with CommonPool2TargetSource. Or shoot yourself in the foot, that"s faster.

I suggest to not monitor that `run` method:
- Remove the two `@MonitoredWithSpring` and the `@Service` from TestRunnable and replace the `@Service` by `@Component`.
- Then move what you want to monitor from the `run` into another method `testrun` in a TestService to create and annotated with `@Service`.
- Call `testrun` from `run`.
- The method `testrun` will be monitored and you have what you want.

You may also give the correct target to release like the following, but I do not recommend that mix:
```java
			TestRunnable test = (TestRunnable) genericPoolLifeCycle.getTarget();
			executor.execute(() -> {
					test.setTarget(test);
					test.run();
			});
```

**Comment by evernat** [comment]
Closed as invalid.
