### ISSUE TITLE
Différence in value range / scale displayed in statistic info

### ISSUE THREAD

**Issue by eric-gagnon** [javamelody/javamelody#1021]
Hello,

Finally have deployed Javamelody in production, so happy as it gives us very valuable insights to understand the behavior of the system. Thank you very much!

Previous programmer had allocated a pool of 200 connections, I have changed the value and we now have real data to help calibration.

I have noticed that the statistic view is not diplaying value in the same range, is this a settings that I have missed, a normal behavior or a bug? I'm still using 1.86, I will update but see nothing that seem to be related in the release ntoes of 1.87

![image](https://user-images.githubusercontent.com/21067311/120505837-5b0b2d00-c393-11eb-8107-f81f5abfd239.png)

**Comment by evernat** [comment]
It's normal behavior. Unit at the bottom of the graph is chosen automatically based on values (by JRobin).
The meaning of the units is displayed below the graph as a reminder.

**Comment by eric-gagnon** [comment]
Ah ok, still weird to have a "moyenne de 105 millième de connection jdbc" but we will live with that...
