### ISSUE TITLE
Missing property descriptions from spring-configuration-metadata.json

### ISSUE THREAD

**Issue by andrasdenk** [javamelody/javamelody#1025]
Missing property descriptions:
* javamelody.spring-monitoring-enabled
* management-endpoint-monitoring-enabled

**Comment by evernat** [comment]
Issue for the first one is fixed by a2a9218.
For the second one, `javamelody.management-endpoint-monitoring-enabled` is already described in `META-INF/spring-configuration-metadata.json`.
