### ISSUE TITLE
add support to Caffeine Cache in Data Cache section

### ISSUE THREAD

**Issue by lucas-prestes** [javamelody/javamelody#1026]
I'm using Caffeine cache in my application, and wish to see the detailed  data cache info that is available for EhCache,  I think it would be really interesting if possible

**Comment by lucas-prestes** [comment]
Okay, just discovered I can wrap Caffeine in a JCache which is supported by Java Melody. I feel a bit dumb now, but this issue can be closed.

**Comment by 813221068** [comment]
> Okay, just discovered I can wrap Caffeine in a JCache which is supported by Java Melody. I feel a bit dumb now, but this issue can be closed.

how to wrap Caffeine to JCache with springboot?
