### ISSUE TITLE
 RemoteCall & RemoteCollector issue / monitoring

### ISSUE THREAD

**Issue by AishaSheikhAlbalad** [javamelody/javamelody#1033]
# Description

I tried to implement scripts and alters that were mentioned in "https://github.com/javamelody/javamelody/wiki/ScriptsAndAlerts" in Spring boot project but I have the below issue "RemoteCall is abstract; cannot be instantiated" while using RemoteCall.
In addition, I tried to use RemoteCollector to check if I can use it instead of RemoteCall but the error "c.m.c.jMelody.monitoringController : Unexpected html content type, maybe not authentified

java.lang.IllegalStateException: Unexpected html content type, maybe not authentified"
The implementation for RemoteCollector is as the following:

List<URL> urls = new ArrayList<>();
            URL u1 = new URL("http://localhost:8080/admin/monitoring?");
            urls.add(u1);
            RemoteCollector rc = new RemoteCollector(applicationContext.getApplicationName(), urls);
            rc.collectCurrentRequests() ;

## Expected Behavior

Get monitoring data using scripts and how to send alerts based on thresholds. 

## Actual Behavior

Get errors while using RemoteCall & RemoteCollector

## Environment

- OS: [Windows 10]
- IDE: [Netbeans ]
- Javamelody Version: [1.87.0]
- IDE Version: [12.3]

**Comment by evernat** [comment]
First, the [ScriptsAndAlerts](https://github.com/javamelody/javamelody/wiki/ScriptsAndAlerts) page does not speak of RemoteCollector, I do not know what you makes you think that it may work with that.
And I do not reproduce your issue with RemoteCall.
Do you have authentication on your monitored application? If yes and if it is a basic auth, you can put the username and password as said in the doc.
