### ISSUE TITLE
Separate URLs for monitoring and RUM

### ISSUE THREAD

**Issue by mppfiles** [javamelody/javamelody#1039]
Currently I am unable to set a `security-constraint` just for the monitor page, without blocking the RUM for normal app users. This is because both components share the same URL (`/monitoring` and `/monitoring?resource=boomerang.min.js` respectively).

Although it's possible to write a servlet filter that detects the presence of boomerang.min.js in the URL, it's a bit cumbersome and can be easily avoided by exposing it in another URl.

This way, normal app users (without any "monitoring" role) can use the app and post RUM data, meanwhile only authorized users can access the stats pages.

**Comment by evernat** [comment]
See #1224 

It is not planned to expose another URL for RUM.
