### ISSUE TITLE
Metric http sessions in Confluence

### ISSUE THREAD

**Issue by chgarling** [javamelody/javamelody#1040]
Hello all,

this is not an issue but a question. There is a Confluence server with JavaMelody running and the HTTP session metric counts round about 600 sessions as a baseline. This value is the minimum, at night too. We are wondering about this and already disabled the HTTP monitoring but nothing changed.

Where does JavaMelody count the HTTP sessions and how is a session defined? What does count into this metric? The Confluence session timeout is set to 5 hours, so after work the graph should go down to a lower value in my opinion, especially at night.

Regards, Christrian

**Comment by evernat** [comment]
any news ?

**Comment by evernat** [comment]
no response from the reporter
