### ISSUE TITLE
Prometheus endpoint returns empty response when working with SpringBoot

### ISSUE THREAD

**Issue by goldyliang** [javamelody/javamelody#1064]
It is found that when using spring boot and javamelody-spring-boot-starter, the Prometheus end point (?format=prometheus) returns 200 as status code but the response body is empty.

After some digging, it seems that there is a missing flush being called in the below code in MonitoringController:

```
	public void doPrometheus(HttpServletResponse httpResponse,
			List<JavaInformations> javaInformationsList, final boolean includeLastValue)
			throws IOException {
		httpResponse.setContentType("text/plain; version=0.0.4;charset=UTF-8");
		final PrometheusController prometheusController = new PrometheusController(
				javaInformationsList, collector, httpResponse.getWriter());
		prometheusController.report(includeLastValue);

                // Below is added to fix
		httpResponse.getWriter().flush();
	}
```

After adding the flush, it is verified to be working.  I see the other parts of that class also do the flush as well, so probably this is missing in Prometheus part.

**Comment by goldyliang** [comment]
Or should the code be httpResponse.flushBuffer() like other part?  I did not test with flushBuffer, but getWriter().flush() works.

**Comment by goldyliang** [comment]
Created a pull request for this simple fix.

https://github.com/javamelody/javamelody/pull/1099

**Comment by evernat** [comment]
not reproduced using javamelody-spring-boot-starter and embedded tomcat but ok anyway

**Comment by evernat** [comment]
#1099 merged
