### ISSUE TITLE
Grafana dashboard application switch issue in javamelody

### ISSUE THREAD

**Issue by vijazy** [javamelody/javamelody#1072]
I am new in javamelody, i have configured javamelody monitor for multiple tomcat servers pushed stats to promethus and imported grafana dashboard..i can see metrics on grafana.

but i would like to see metrics for one application at a time...its showing all application metrics rather than single application...also in variable field not working properly.

how can i achieve this ?

**Comment by evernat** [comment]
It seems to be a grafana usage issue and not a javamelody issue.

In Prometheus' scrape config, you have job_name and targets, as you can see an example at:
https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#exposing-metrics-to-prometheus

For Grafana usage, see for example:
https://stackoverflow.com/questions/70785017/grafana-filter-jobs-and-targets
