### ISSUE TITLE
javamelody is causing bean injection issue

### ISSUE THREAD

**Issue by narsinallamilli** [javamelody/javamelody#1073]
https://github.com/narsinallamilli/jm.git

http://localhost:8080/hello
http://localhost:8080/camel/health-job

If I disable javamelody-spring-boot-starter both above endpoints test ok but if you enable then they throw initialization error. I guess its something to do with javamelody aop bean handling.

**Comment by narsinallamilli** [comment]
I see issue is relate with aop.nested spring beans are not getting injected with @Autowired properties.

**Comment by evernat** [comment]
@narsinallamilli I suggest to disable monitoring of services, in your specific case using kotlin (and CamelContext).
For that, configure javamelody, in this case in your application.properties :
```
javamelody.spring-monitoring-enabled=false
```
