### ISSUE TITLE
Is it javamelody compatible with `tomcat-10`

### ISSUE THREAD

**Issue by sakitA** [javamelody/javamelody#1083]
When I use `javamelody` with `tomcat-10` I got error because of there is no `javax.servlet` package. With tomcat-10 replace all `javax` lib with `jakarta`.

**Comment by keithphw** [comment]
Short answer: not yet.
See this thread:
https://github.com/javamelody/javamelody/issues/978
PS: Thanks for your hard work evernat and everyone. 
JavaMelody is a fantastic tool.
