### ISSUE TITLE
Timer already cancelled.

### ISSUE THREAD

**Issue by sakitA** [javamelody/javamelody#1093]
Hello. I have 3 web application(`A`, `B` and `C`). All these web apps located the same tomcat container. I am using latest servlet api. All three apps have dependency `javamelody`. To avoiding duplicate javamelody dependency I put javamelody and its dependencies under tomcat common lib directory(not `lib` or not `shared lib`). Everything works normal. But when I undeploy one of the modules javamelody stop monitoring and throw `Timer already cancelled.` error. I also tried https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#deployment-on-tomcat-without-modification-of-monitored-webapps-beta. Everything seems normal but request counter did not work. How can I solve this problem without duplicating dependencies for each web application?

Java version: openjdk version "11.0.13" 2021-10-19 LTS
Tomcat version: apache-tomcat-10.0.13(with jakarta)
javamelody: 1.90.0

**UPDATE**

I checked the source code and I think that problem is related to https://github.com/javamelody/javamelody/blob/24bdd22ff97a9010d5dafd2f4c8490c6f837cd39/javamelody-core/src/main/java/net/bull/javamelody/FilterContext.java#L271

`JRobin.initBackendFactory(timer);` time is static. It means that `JRobin` store only one(last deployed) web application `timer`. Because of this in my use case if we undeploy any web application `filter context` stop timer so that other web application monitor does not work normal.

**SOLUTION**
I think we can register timer based on context path and when we undeploy just cancel that web application timer

**Comment by evernat** [comment]
Do not put javamelody in tomcat lib. Even less when there are several monitored webapps in the same Tomcat.
Put javamelody in webapp's WEB-INF/lib as a dependency of webapps. It is the documented and standard way.

**Comment by sakitA** [comment]
@evernat thank you very much for your response. I appreciated your works and thanks for this amazing tool. The solution which you suggested is not efficient solution and takes more resource in my use case. Because I have 30 modules. I will try to find why request counter not works properly when we use https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#deployment-on-tomcat-without-modification-of-monitored-webapps-beta this way. This configuration what we need it.
