### ISSUE TITLE
Incorrect "used jdbc connections" when using Spring JdbcTemplate.queryForStream

### ISSUE THREAD

**Issue by piercemar** [javamelody/javamelody#1094]
Hello,

When using JdbcTemplate.queryForStream (introduced in spring-jdbc 5.3), JavaMelody does not decrease the open jdbc connections count upon stream close.

This result in _apparently_ dangling connections, though they are correctly released to the pool.

I traced it down to the proxied Statement created by calling Connection#createStatement() on a proxied connection, not returning the proxied connection when calling Statement#getConnection(). Instead it returns the underlying *real* connection. So when close() is finally called, the wrapper is not aware of it and cannot decrease the counter.

JavaMelody 1.90
Spring 5.3.15 (spring-boot 2.6.3)

**Comment by piercemar** [comment]
To better illustrate, I created a simple spring-boot demo showcasing the issue.
But I don't know how to attach it to this thread (3 KB).

**Comment by evernat** [comment]
fixed by 629f76d. Thanks for the issue.
