### ISSUE TITLE
 ser.gz files inside datacollector directory.

### ISSUE THREAD

**Issue by SiddGhoshGit** [javamelody/javamelody#1095]
Hello,

Needed some advise regarding .ser,gz files inside datacollector directory in javamelody.

1) Are these archived files which get zipped after certain amount of days ? If yes, after how many days?
2) Can older .ser.gz files be deleted to recover space ? and will these not affect to the stats on the javamelody dashboard ?
3) Does .ser.gz contains the old date .rrd file contents ?

Thank you

**Comment by SiddGhoshGit** [comment]
Requesting someone to respond / advise. Thank you.

**Comment by evernat** [comment]
Hello,
.ser.gz files contains statistics data on http, sql and other requests. .rrd files contains data for graphs.
1. The .gz means that they are already (g)zipped when they are created. So the answer is that they are gzipped after 0 day.
2. Old .ser.gz are automatically deleted after 365 days, by default. This is configurable with the obsolete-stats-days parameter.
3. .ser.gz files and .rrd files do not contain the same data.

Given that they are gzipped and automatically deleted when obsolete, the total size of .ser.gz files is a few mega-bytes or a few tens of mega-bytes per server, which is in general not a problem.
