### ISSUE TITLE
dependency scope setting issues

### ISSUE THREAD

**Issue by DataProvided** [javamelody/javamelody#1101]
Hi,

We are developing a tool to check whether the dependencies' scopes in maven are set rightly and reasonably. 

Our tools have found some issues in your project about scope setting in maven' pom.xml file.

- in `javamelody-core\pom.xml`, `javax.servlet.jsp:javax.servlet.jsp-api` scope should be `compile`  instead of `provided`.
- in `javamelody-core\pom.xml`, `javax.interceptor:javax.interceptor-api` scope should be `compile`  instead of `provided`.
- in `javamelody-core\pom.xml`, `javax.mail:javax.mail-api` scope should be `compile`  instead of `provided`.

Please help us confirm whether the above reports are right and explain why it should set like these.

Thanks a lot.

**Comment by evernat** [comment]
@DataProvided you don't know what you are speaking about.
