### ISSUE TITLE
Two Javamelody collector servers.

### ISSUE THREAD

**Issue by SiddGhoshGit** [javamelody/javamelody#1106]
I have a question , For the sake of High availability / redundancy . Can two javamelody collector servers collect data from one remote application server without any conflicts ?

I mean for example we have two collector servers A and B and I add remote server C to be monitored in the app.properties file in both collector Servers A and B , therefore we will have two redundant sets of data correct ?  and this should not cause any conflict ?

Please advise.

**Comment by SiddGhoshGit** [comment]
Requesting advise ,thank you

**Comment by evernat** [comment]
@SiddGhoshGit probably no, sorry. Two javamelody collector servers are not supposed to collect data from one remote application. If you do it that way, it is expected that each collector server has correct data for memory, cpu, http sessions, threads, jdbc connections, but each collector server has about half of http and sql stats in particular the numbers of hits of http and sql requests. So http and sql stats may be misleading on hits and by consequence of which hits are counted in means and maximums.

Collector servers were not created with redundancy in mind, given that they are a secondary usage compared to the features of your applications and they are not supposed to have a big load with many users. And please note that collector servers are less used in percentage compared to javamelody without collector servers : often and more simply, javamelody is just included in monitored applications and monitoring pages are accessed on each instance separatly for example.

So, I would advise to :
- use javamelody but without the collector server if you don't need to aggregate stats and/or info about many instances,
- use javamelody and the collector server if you need to aggregate stats and/or info about many instances,
- if you want redundancy of collector server, think again about the complexity you introduce or use two collector servers in parallel with the warning about half the http and sql stats in mind.

I hope it answers you question, so I close the issue.
You can still ask related questions below.
