### ISSUE TITLE
Question / Query regarding age of the data storage

### ISSUE THREAD

**Issue by SiddGhoshGit** [javamelody/javamelody#1120]
hello @evernat 

Requesting advise on a query , the javamelody storage contains the following files:
- *.rrd files for values in graphics (using jrobin library)
- *.ser.gz for values in statistics

I wanted to know if javamelody automatically deletes the older files (extensions stated above ) which are more than a year old by default ? if yes, where is this control applied in the code ?

**Comment by SiddGhoshGit** [comment]
Hello @evernat requesting advise on this query.

**Comment by blontrock** [comment]
The .rrd files are round robin data. Meaning new data gets in and replaces old data. So no need to remove old files, at least when new data is added. I guess for counters that are no longer used, that they are never cleaned up.

**Comment by evernat** [comment]
@SiddGhoshGit Sorry for the delay. 
Yes, javamelody automatically deletes the older files, every day at midnight. By default, *.ser.gz are deleted after 365 days. *.rrd files are round robin data like @blontrock said, which means new data gets in and replaces old data as time goes by. And *.rrd files which become unused are deleted after 90 days.

This is configurable by the following javamelody parameters:
Parameter | Description | Default value
-- | -- | --
obsolete-graphs-days | Retention of obsolete graph files (rrd) in days | 90
obsolete-stats-days | Retention of stats files (ser.gz) in days | 365

For *.ser.gz files, it is managed at https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/internal/model/CounterStorage.java#L169
