### ISSUE TITLE
Number of hits grows exponentially in the javamelody collector

### ISSUE THREAD

**Issue by mgagp** [javamelody/javamelody#1121]
The count of http requests is correct when accessed directly on the javamelody application instance.
But when using the collector, the count grows exponentially.

**Comment by evernat** [comment]
@mgagp 
- Which version of javamelody are you using in the monitored application ?
- Which version of the javamelody collector are you using ?
- Do you see a message like `Do not use this monitoring page if you use the optional collector server: either use the monitoring page from the webapp, without a collector server, or use the page from the collector server` in the monitoring page when displaying the monitored page directly in the monitored application (that is without using the collector to display the monitored page). The message may be translated in your browser's language.
- Have you configured an "aggregation" of 2 or more monitored applications in the collector ?

**Comment by mgagp** [comment]
javamelody in monitored application = 1.91.0
javamelody collector = 1.91.0

there is no message like "Do not use this monitoring page ..."

No, there is no aggregation of 2 or more applications.




Le jeu. 5 janv. 2023, à 07 h 58, evernat ***@***.***> a
écrit :

**Comment by evernat** [comment]
The URL called by the collector server on the monitored application is like .../monitoring?collector=stop&format=serialized.
Have you changed something by code in the collector server to change this URL ?

**Comment by mgagp** [comment]
No modification in the collector. Example from our production: 
http://172.nn.nnn.178:8081/actuator/monitoring?collector=stop&format=serialized

**Comment by evernat** [comment]
At last, I understand what is causing this issue. You are using the management port of Spring Boot for the monitoring page instead of the http port of the webapp. This configuration uses code which did not have what is needed when used from a javamelody collector server.

Fixed by fd52e41 in 1.x branch (javaee) and by 5caa82f in 2.x branch (jakartaee).

**Comment by evernat** [comment]
Before the release, you can download a snapshot build for the monitored application at 
http://javamelody.org/downloads/javamelody-core-1.95.0-SNAPSHOT.jar
