### ISSUE TITLE
JavaMelody shows different max memory than Tomcat and VisualVM

### ISSUE THREAD

**Issue by robozb** [javamelody/javamelody#1142]
What can cause it?

Thanks: Bela

**Comment by evernat** [comment]
If you speak of the blue line and the Maximum in the Used memory graph like this:
![usedMemory](https://user-images.githubusercontent.com/498950/216469503-3edd1150-7398-47e9-8c38-df0dfb94848d.png)
then it is not the maximum memory (Xmx) which can be used for the heap by the JVM.

It is the maximum measured value on the period, like in all the graphs.

You can see the maximum memory which can be used for the heap by the JVM in the "System informations" part of the monitoring page. By definition of Xmx, the used memory in the graph above can never be more than the Xmx.

**Comment by robozb** [comment]
Dear @evernat,

You are pro! Thank you so much! ChatGPT didn't know the good answer :) 

Best Regards: Bela
