### ISSUE TITLE
JavaMelody: @net.bull.javamelody.Monitored annotation not showing Statistics for Classes or Methods

### ISSUE THREAD

**Issue by matawak** [javamelody/javamelody#1149]
Hello, we followed the JavaMelody User Guide https://github.com/javamelody/javamelody/wiki/UserGuide, and annotated a method of our CDI Bean with `@SessionScoped` accordingly (`@net.bull.javamelody.Monitored`) as described in the **Session Business facades (ejb-jar.xml file if EJB3) or CDI** session of the User Guide. We are using JavaMelody Version 1.92.0

However, when we deploy the application and call the `/monitoring `endpoint, everything is displayed, but no information on the monitored method. Also, placing the annotation on the class has no effects, i.e., no statistics.

Are there other prerequisites to meet in addition to get the statistics to be collected and displayed?
I will appreciate any help, please.

**Comment by evernat** [comment]
Activation of a CDI interceptor, like the net.bull.javamelody.MonitoringCdiInterceptor, depends on which CDI version is used and of which server version and configuration are used. So it is sometimes different and evolving over the years.

In a snapshot build, I have added `@Priority(value = Interceptor.Priority.APPLICATION)` on the MonitoringCdiInterceptor class. 
You can download this snapshot build at http://javamelody.org/downloads/javamelody-core-1.93.0-SNAPSHOT.jar
Does it work better for you ?

**Comment by matawak** [comment]
I will try it tomorrow at work and feedback accordingly.
Thank you.

**Comment by matawak** [comment]
Another question please, since we had a heated discussion this morning...

Do we need a beans.xml File when we use the @net.bull.javamelody.Monitored annotation?
My opinion is no!

Thanks for clarification...

**Comment by evernat** [comment]
I think that you don't need to write a beans.xml file in your application. Test the new snapshot build with a Monitored annotation on your CDI beans, and you will see if the MonitoringCdiInterceptor is enabled.

**Comment by matawak** [comment]
Alright. Thanks again

**Comment by matawak** [comment]
Hello sir, 
sorry I am resonating a bit late, had to accord another task priority.
I tried it out, had to add jrobin as application dependency, and yes, I am seeing the information under "Statistics for EJB". All the instrumented classes are monitored. Thanks again.
I have just one inquiry: when would the 1.93.x version be available in Maven Repo?
Cheers

**Comment by evernat** [comment]
fixed by commit above. to be released.

**Comment by evernat** [comment]
released in javamelody 1.94.0

**Comment by matawak** [comment]
Thank you very much. It is working.

Cheers

 
 

Gesendet: Montag, 17. April 2023 um 03:15 Uhr
Von: "evernat" ***@***.***>
An: "javamelody/javamelody" ***@***.***>
Cc: "matawak" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [javamelody/javamelody] JavaMelody: @net.bull.javamelody.Monitored annotation not showing Statistics for Classes or Methods (Issue #1149)


 

released in javamelody 1.94.0
