### ISSUE TITLE
JavaMelody PDF Report: Customizing Content of generated PDF Report

### ISSUE THREAD

**Issue by matawak** [javamelody/javamelody#1159]
Hello,
we have introduced JavaMelody v1.94.0 to monitor some Jakarta EE Applications at the customers. So far good. 

However, in the production environment, the customer is not happy with the content of the generated PDF Report. In fact, the customer only wants to see the Statistics for SQL Queries, HTTP Requests and performance indicators at the method level.  Other Statistics like the Diagrams and the System Information, especially the User Sessions must not appear in the generated PDF Report. 

Failing to meet these requirements will lead to not adopting JavaMelody at all.
 
We have perused the User Guide, to see whether there are parameters to exclude blocks of content from the PDF Report, but so far no success.

Hence, my question: Is it possible to customize the content of the generated PDF Report, and if yes, how do we achieve this please?

Thanks

**Comment by evernat** [comment]
The main PDF report does not contain details on each http session. For http sessions, it contains a graph and in System informations, the count of http sessions. It does not seem worth of removing a line saying the count of http sessions, because it is not troublesome and not worth refusing javamelody for that. Same for the other graphs and System informations, just ignore them if they are not interesting for you.

However, it is not possible to customize the content of the PDF reports.

**Comment by matawak** [comment]
Hello,thank you for the clarification!CheersAm 27.05.23 um 19:04 schrieb evernat
                
            
            
                
                    Von: "evernat" ***@***.***>Datum: 27. Mai 2023An: "javamelody/javamelody" ***@***.***>Cc: "Author" ***@***.***>,"matawak" ***@***.***>Betreff: Re: [javamelody/javamelody] JavaMelody PDF Report: Customizing Content of generated PDF Report (Issue #1159)
                
                
The main PDF report does not contain details on each http session. For http sessions, it contains a graph and in System informations, the count of http sessions. It does not seem worth of removing a line saying the count of http sessions, because it is not troublesome and not worth refusing javamelody for that. Same for the other graphs and System informations, just ignore them if they are not interesting for you.
However, it is not possible to customize the content of the PDF reports.
