### ISSUE TITLE
 java.lang.NoClassDefFoundError: org/jrobin/core/RrdException

### ISSUE THREAD

**Issue by tomekkup** [javamelody/javamelody#1161]
I've upgraded from javamelody 1.92.0 to 1.95.0-SNAPSHOT. Since now I cannot see any graphs.

**Comment by evernat** [comment]
I suggest to look at the log from start of the server to this error. Please copy here any exception about javamelody, including stack-traces. And also copy here this NoClassDefFoundError with its stack-trace. You can anonymize private data in stack-traces.

**Comment by evernat** [comment]
any news ?

**Comment by evernat** [comment]
no response from the reporter, so closing
