### ISSUE TITLE
Auto registrating in optional collector in spring-boot-starter

### ISSUE THREAD

**Issue by arseny-tl** [javamelody/javamelody#1166]
Hello!
Im using spring starter.
Based on https://github.com/javamelody/javamelody/issues/679 there is a programmatic way to register application in optional server collector. Currently, i have >80 microservices, which i am trying to migrate to optional collector. It seems to me a little bit odd that i need to add to all microservices startup/shutdown hooks to register / deregister application from collector. Even if i just created my own starter which will register/deregister automatically i would need to update >80 pom files. Do you think it is possible to add property 'collector-server-url' and reuse it in AutoConfiguration to automatically register based on application properties?
I can try to add this functionality.

**Comment by evernat** [comment]
It seems to me that it would be needed to have values for applicationName and applicationNodeUrl and not only for collectServerUrl, when calling the `MonitoringFilter.registerApplicationNodeInCollectServer(applicationName, collectorServerUrl, applicationNodeUrl)`.
What would you do for those parameters ?

**Comment by evernat** [comment]
?

**Comment by evernat** [comment]
no response from the reporter, so closing
