### ISSUE TITLE
InfluxDB 2.X (Auth) Support

### ISSUE THREAD

**Issue by mweber89** [javamelody/javamelody#1170]
In InfluxDB 2.x, passing the token or username/password directly within the URL is not supported. The recommended method is to include the authentication information in the request headers. This helps ensure secure transmission of sensitive information.
I can't find in the docs, how to configure request headers, hence the request to have a closer look into the InfluxDB 2.x requirements.

**Comment by evernat** [comment]
According to influxdb doc, Basic Authentication is still supported in InfluxDB 2.x by using the InfluxDB 1.x compatibility API:
https://docs.influxdata.com/influxdb/v2.7/reference/api/influxdb-1x/

Note that when you have username and password or token in the influxdb url as explained in the [javamelody doc](https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#sending-metrics-to-influxdb), javamelody will in fact send a http request header like `Authorization: Basic INFLUX_USERNAME:INFLUX_PASSWORD_OR_TOKEN` as explained in influxdb doc:
https://docs.influxdata.com/influxdb/v2.7/reference/api/influxdb-1x/#basic-authentication
So yes, a http request header is already used by javamelody and not query string parameters.

**Comment by evernat** [comment]
The header is set here if you search it:
https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/internal/model/LabradorRetriever.java#L307

**Comment by evernat** [comment]
And I have added support to set an `influxdb-api-token` parameter like the `influxdb-url` parameter: cd34d03 and ea73a31
