### ISSUE TITLE
Exception NoClassDefFoundError (HttpSessionListener) when trying to start Tomcat

### ISSUE THREAD

**Issue by Chealer** [javamelody/javamelody#1181]
I just tried upgrading Javamelody from 1 to 2.0.1, and this fails with the following:

> GRAVE: Erreur lors de la configuration de la classe d'écoute de l'application (application listener) [net.bull.javamelody.SessionListener]
> java.lang.NoClassDefFoundError: jakarta/servlet/http/HttpSessionListener
> 	at java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
> 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2337)
> 	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:810)
> 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1293)
> 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1141)
> 	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:488)
> 	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:470)
> 	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:142)
> 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4389)
> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4914)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
> 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
> 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866)
> 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:794)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
> 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
> 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866)
> 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:248)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
> 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:433)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
> 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:921)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
> 	at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347)
> 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)
> Caused by: java.lang.ClassNotFoundException: jakarta.servlet.http.HttpSessionListener
> 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1329)
> 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1141)
> 	... 40 more

2.0.1 breaks our application's startup due to this error. We are using OpenJDK 8, which does feature `HttpSessionListener`, but not in the path mentioned (jakarta/servlet/http/HttpSessionListener). This path must be specific to JDK 9+, so this is probably caused by part of the code expecting JRE 9+. 1.95.0 works fine with our Eclipse Temurin jdk8u392-b08 and Tomcat 8.5.85.

**Comment by evernat** [comment]
It is not explicitly written in releases, but it is written here :
https://github.com/javamelody/javamelody/wiki/UserGuide#dependencies

The 2.x branch is for Jakarta EE such as Tomcat 10.
Use the 1.x branch for Java EE such as Tomcat 9. So 1.95.0 is the latest for you at the moment.

**Comment by Chealer** [comment]
Thank you for the explanation @evernat , I fixed the description. This does have to do with our JavaMelody being incompatible with our servlet container (Tomcat 8.5).

Thank you for the link to the guide. Fixing the guide (updating the introduction) would mitigate the impact:

> Server version required for execution: servlet api 2.4 at least (or JavaEE 1.4), like Tomcat 5.5 or +, GlassFish v2+, JBoss 4+, Jetty 6+, WebLogic 9+
