### ISSUE TITLE
License called "ASL"

### ISSUE THREAD

**Issue by Chealer** [javamelody/javamelody#1192]
[The user guide's introduction](https://github.com/javamelody/javamelody/wiki/UserGuide#introduction) contains:

> 
> Informations
> 
>     License: ASL since v1.50, LGPL before v1.50

JavaMelody is licensed under the [Apache License](https://opensource.org/license/apache-2-0/). Calling it the "ASL" is confusing. Avoiding that acronym and adding a link would help.

pom.xml files also need to be fixed:
```
	<licenses>
		<license>
			<name>ASL</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>repo</distribution>
		</license>
	</licenses>
```

By the way, "Information" is usually uncountable (in English).

**Comment by evernat** [comment]
Yeah sorry. I speak French :-)

**Comment by evernat** [comment]
fixed, thank you

**Comment by Chealer** [comment]
> Yeah sorry. I speak French :-)

Ça va, tu n'es pas le seul à le faire ^_^

**Comment by Chealer** [comment]
> fixed, thank you

Thanks to you

The POM-s of modules also have the issue though, like https://github.com/javamelody/javamelody/blob/master/javamelody-swing/pom.xml#L18
