### ISSUE TITLE
Question about sending alerts

### ISSUE THREAD

**Issue by adrianboangiu** [javamelody/javamelody#1196]
Hello,

I am using the examples provided in ScriptsAndAlerts to send alerts. Everything works fine but I need more information how to report some information.
I would like to present the list of active http queries with their stack (like it is available in the active queries section
![monitoring](https://github.com/javamelody/javamelody/assets/28983495/068befd7-9568-4c6b-be33-2bf1efdbebaa)) and eventually their "active" sql queries (if any).
I think it is possible to recuperate all this but there is no documentation on how this information can be achieved. More generally, is there an explanation about how to "recuperate" programatically (groovy script) every piece of information present in the JavaMelody interface.

Thank you.

**Comment by evernat** [comment]
I have added for you a groovy script to display the current requests (http and current childs such as sql and also stack-trace of the thread) in the https://github.com/javamelody/javamelody/wiki/ScriptsAndAlerts#display-current-requests page.

Note that the displayed durations may have some offset, since the remote host may not be at the same time. And the cpu and allocated kbytes by request can't be displayed this way.
I hope that you find what you are looking for.

**Comment by evernat** [comment]
About explanations for other data, I have updated the link in the page to https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/internal/model/RemoteCall.java to know all data which you can get remotely in a script.

Then you can see the source of the classes you get from "RemoteCall" and see which getters are available on these classes (some getters may not work in a script if they depend on a transient field or if they depend to be called on the remote host) : https://github.com/javamelody/javamelody/tree/master/javamelody-core/src/main/java/net/bull/javamelody/internal/model

off topic: je travaille vers Paris, mais ma boîte (conseil/intégration ...) a un bureau à Montpellier si vous voulez parler affaires un jour.

**Comment by adrianboangiu** [comment]
Thank you.
I was already able to retrieve the current requests and discover their threads and stacks (by using the sources of JavaMelody). I still had to find the sql requests of a current http request (something "not existing" in the JavaMelody interface. Thank you for your help and let me say that JavaMelody is a great, great piece of software!
