### ISSUE TITLE
Kubernetes. Is there a way to save the data to a fixed storage directory?

### ISSUE THREAD

**Issue by pier4r** [javamelody/javamelody#1198]
Hi everyone!

### Problem
We (my Team and I) are using Javamelody in applications deployed in kubernetes. The problem is that those apps have a changing pod hostname and it seems to me that javamelody is using the hostname to create a directory for the data.

This is very limiting because every time the application gets redeployed and its hostname changes, the javamelody folder changes and we lose the ability to see the older data.

Example, under `/usr/local/tomcat/temp/javamelod` we have the following folders:

```
app-55969c9dff-wjt64
app-55cb5f9cf9-psp79
app-569bd6c846-zjck2
app-59dd786dc4-pf5md
app-5d5c7878ff-tnppc
app-648cc8bd88-f9fvf
app-67998f6bbb-6kw4b
app-688f78c6fd-7fstn
app-6986687766-kw5td
app-6bfc598df6-gkqgc
app-74c6c6d8b4-m4tx2
app-7866f6dfd6-rfds9
app-7f5fd874b6-dwf2r
app-845786c549-lk6x8
app-86cb68cdf-mmzt5
app-8dbc8d6db-6jz4g
app-bb5fdb7dd-krksz
```

I also tried to give javamelody storage a value, namely

```
-Djavamelody.storage-directory=/usr/local/tomcat/temp/javamelody/fixed
```

but it is no solution, as javamelody again creates subfolders using the hostname of the pod.

Is there a way to force javamelody to use one fixed folder without creating subfolders if the hostname of the pod changes?

**Comment by evernat** [comment]
Yes, in order that the subdirectory in the storage directory does not depend on the hostname, you need to use the javamelody parameter `application-name`. For example, in a system property: `-Djavamelody.application-name=myapp`

**Comment by pier4r** [comment]
Thank you!
