### ISSUE TITLE
Release new OfflineViewer

### ISSUE THREAD

**Issue by rPraml** [javamelody/javamelody#1213]
Hello, is it planned to update the offline viewer?

The current release is 1.87, which is rather old
https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#offline-viewer

(As workaround, I compiled it manually.)

Roland

**Comment by evernat** [comment]
Done. [javamelody-offline-viewer 2.2.0](https://github.com/javamelody/javamelody/releases/download/javamelody-core-2.2.0/javamelody-offline-viewer.jar) is available for download and includes javamelody-core 2.2.0 and Tomcat embedded 10.1.23.
