### ISSUE TITLE
Using JavaMelody to offer monitoring and diagnostics of Resources within a Message Oriented Middleware

### ISSUE THREAD

**Issue by matawak** [javamelody/javamelody#1221]
We are a using a custom component based on JMS messages and E-Mail to communicate between our Enterprise Java Web Applications and an external System.

Presently, we are using JavaMelody for performance monitoring and diagnostics of our main Enterprise Web Applications.

We intend to extend the functionality of JavaMelody to incorporate the resources within the Messaging System. The Messaging Component does not however offer a User Interface or Application Context (not a Web Application per se), so apparently, we are not sure how to integrate JavaMelody within the Messaging Application.

Essentially, this is how the Web Application and the Messaging Component work together:
1) The main Web Application sends JMS Messages to a Queue in our Messaging System (OUTBOUND)

2) The Messaging System employs a Quartz Scheduler (Job) to read the JMS Messages in the OUTBOUND-Queue and transform these to normal Java Mail Messages (E-Mail) and send them to the target system (Mail Server)

3) The Messaging System polls E-Mail Responses from the Mail server via a Quartz Scheduler, transforms these to JMS Messages and puts them in a Queue in the Messaging System (INBOUND)

4) The main Web Application reads the JMS messages in the INBOUND-Queue, converts them to database records and saves them in the database.

So our concretized questions:
1) How can we integrate JavaMelody in the standalone Messaging System to monitor the Queues and Jobs?

2) Can we access these diagnostic information in the Messaging System directly within our main Web Application? The main Web Applications and the Messaging Gateway are deployed in the same Wildfly / JBoss.

Thanks for directives

**Comment by evernat** [comment]
JavaMelody needs to be able to give you reports. So I suggest that you make you messaging application a webapp and so you can integrate JavaMelody like in any webapp. Since you already have Wildfly / JBoss, you can deploy it there.

You can restrict the access to the monitoring page in the new webapp with a username and a password using the `authorized-users` javamelody parameter.
