### ISSUE TITLE
Collector: read-only application.properties not disabling Add/Remove Application

### ISSUE THREAD

**Issue by Funstar81** [javamelody/javamelody#1229]
We have a TomCat 9.0.41 with Collector 1.99 running on Windows 2019 Server. Even I set an explicit "deny" to write to the application.properties file for the user running the TomCat, the links for adding/removing applications are not removed as mentioned in the documentation. When I try to add/remove something via the links, I get an error that the file cannot be written (which is what we want, right?).

**Comment by evernat** [comment]
> When I try to add/remove something via the links, I get an error that the file cannot be written (which is what we want, right?)

yes, it is.

I suppose that you have clicked `Deny` next to `Write`.
Instead of that, just click `Read only` in the `General` tab.
