### ISSUE TITLE
Sql mean times graph showing NaN values instead mean and max values

### ISSUE THREAD

**Issue by abhishekkumawat9696** [javamelody/javamelody#1233]
I have JavaMelody version 1.98.0
Tomcat version 10.1.26
Why it is showing NaN 
<img width="135" alt="sql-mean-times-hit" src="https://github.com/user-attachments/assets/048ffa70-6082-419f-a767-2e3a944c2159">

![image](https://github.com/user-attachments/assets/5c4b4421-45db-4c37-a60b-bcc42fbacf87)

**Comment by evernat** [comment]
The graph displays NaN for Mean and Maximum, because there are not enough recorded values and so the Mean and Maximum would not be meaningful.
The graph will contain values and Mean and Maximum after some time.
