### ISSUE TITLE
Javamelody + JIRA = Encoding problems

### ISSUE THREAD

**Issue by flexguse** [javamelody/javamelody#2]
Hi,

we are running a JIRA 6.2 instance on Windows 2008 server with JDK 1.7.0_67.

We tried to enable JavaMelody but every time we add the javamelody.jar to the JIRA Tomcat lib folder we get encoding Problems in JIRA and the JavaMelody webgui does not work at all (heavy encoding problems).

We tried JavaMelody 1.55.0 and 1.49.0 and had the problems with both versions.

Is this a known issue?

I've used JavaMeldoy before (without any problems), so I don't have an idea where to search.

**Comment by evernat** [comment]
This is not a known problem, at least not in JIRA.
There was a gzip double encoding problem in Jenkins a long time ago, but your issue does not seem like that.

I suppose that there is a compatibility issue with some other plugin or something other.
So I suggest to test by disabling some other plugins and to test without going through IIS or Apache httpd in front of Confluence. At some point, between where you are and a standard JIRA just downloaded, you will find what breaks encoding.

By the way, issues are supposed to be created at https://code.google.com/p/javamelody/issues/list with the others, so I will disable creating issues at https://github.com/javamelody/javamelody/issues

**Comment by evernat** [comment]
I may have not seen something obvious from the start: why do you put javamelody.jar file in Tomcat lib folder, and why don't you simply use the jira-javamelody.jar plugin file in atlassian-jira/WEB-INF/lib folder?
See https://code.google.com/p/javamelody/wiki/AtlassianPlugin
