### ISSUE TITLE
Language configuration

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javamelody/javamelody#271]
```
I have a little problem, we are a Chinese team, we  want to use English version 
of JavaMelody, but the language setting of all our browsers is Chinese. Is it 
possible to make the language of JavaMelody to configurable? For example, we 
can have an additional parameter for monitoring filter in web.xml, or we can 
have a language selection in the index page. 

If you do not mind, I hope I can make a patch for this function.



```

Original issue reported on code.google.com by `xiukongt...@gmail.com` on 18 Dec 2012 at 11:42

**Comment by massimosala** [comment]
Hi
Does the official release support this new parameter *locale* ?

I tried to set it to en_US but the output is still localized to Italian.
And I cannot find it in the [https://github.com/javamelody/javamelody/wiki/UserGuide](url)
