### ISSUE TITLE
Add more granularity to graphs & data view

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javamelody/javamelody#327]
```
Add an ability to view graphs & data in a 1 minute (or current collection 
interval set) granularity. So for example I can specify to view data from 
3.01.2013 13:23 - 3.01.2013 13:41

```

Original issue reported on code.google.com by `tomasz.r...@gmail.com` on 5 Aug 2013 at 8:21

**Comment by clarkgaybel** [comment]
When we see the granularity offers tools like New Relic, that would be a killer feature to have in Melody.
But I get that it would be too costly. Is there a way to catch and export raw data, let's say every 60 seconds, so I can analyse them with a third party tool?

**Comment by evernat** [comment]
@clarkgaybel 
You could call http://localhost:8080/mywebapp/monitoring?format=xml&part=counter&counter=http&period=tout to get http stats and then compute deltas by yourself.
See [External API](https://github.com/javamelody/javamelody/wiki/ExternalAPI#xml)
