### ISSUE TITLE
java melody reporting large Nb of used jdbc connections with Spring Routing Data source

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javamelody/javamelody#399]
```
What steps will reproduce the problem?
1. Configure a MYSQL Routing Data source by extending AbstractRoutingDataSource 
from Spring and using approach explain here 
http://spring.io/blog/2007/01/23/dynamic-datasource-routing/
2. Now when we send some request which involves database operation using that 
routing data source
3. Java melody reports invalid number of used jdbc connections. It reports one 
active connection per request and number of active connections keeps increasing 
as the request comes. Even it exceeds the pool size. On the other hands MYSQL 
DBMS is reporting correct number of connections

Number of active jdbc connections are not correct, java melody shows that 
connection count is increasing as the request count increases 


JavaMelody version: 1.32.1
Server version: Apache Tomcat/6.0.35
OS Name:        Linux
OS Version:     3.10.34-39.137.amzn1.x86_64
Architecture:   amd64
JVM Version:    1.6.0_30-b30 (IcedTea6 1.13.1)
JVM Vendor:     Sun Microsystems Inc.
```

Original issue reported on code.google.com by `atifo...@gmail.com` on 31 Mar 2014 at 10:59

Attachments:
- [JDBCConnections.png](https://storage.googleapis.com/google-code-attachments/javamelody/issue-399/comment-0/JDBCConnections.png)
- [JDBCConnections1.png](https://storage.googleapis.com/google-code-attachments/javamelody/issue-399/comment-0/JDBCConnections1.png)

**Comment by escoand** [comment]
I have a similar issue but without using Spring.
Neither at the MySQL server nore at the heap dump such a large number is reasonable.

OS: Linux unknown, amd64/64
Java: OpenJDK Runtime Environment, 1.7.0_101-mockbuild_2016_04_19_08_45-b00
Server: Apache Tomcat/6.0.24
JavaMelody version: 1.63.0
