### ISSUE TITLE
Jira - javamelody do not show sql statistic

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javamelody/javamelody#465]
```
What steps will reproduce the problem?
1.Install javamelody to Jira
2.It works but Sql Statistic is not shown

What is the expected output? What do you see instead?
Sql Statistic should be shown

What version of the product are you using? On what application server, JDK,
operating system?
Jira version 6.2.6, JDK 1.7, Linux, MSSQLServer 2008

Please provide any additional information below.
Could you please give me some advises for this issue? How to get Sql Statistic 
for Jira?

Thanks
```

Original issue reported on code.google.com by `thinh.ng...@pyramid-consulting.com` on 10 Mar 2015 at 10:40

**Comment by evernat** [comment]
I do not reproduce the issue using JIRA 6.2.6.

1. Do you use Tomcat 8 instead of Tomcat 7 ? (if I suppose that JIRA supports Tomcat 8 at the moment)
2. Copy here the debugging logs displayed at the end of the monitoring page.

**Comment by evernat** [comment]
Any news?

**Comment by evernat** [comment]
No response from the reporter, so closing as incomplete.
