### ISSUE TITLE
Google code soon dead

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javamelody/javamelody#466]
```
http://www.01android.com/android-news/google-code-is-officially-dead-heres-how-t
o-transfer-your-projects-to-github/


I lovee your project !

what's next ?!


```

Original issue reported on code.google.com by `maxime.d...@gmail.com` on 19 Mar 2015 at 8:27

**Comment by evernat** [comment]
* The JavaMelody project is now migrated from GoogleCode (https://code.google.com/p/javamelody) to GitHub. The new project home page is: https://github.com/javamelody/javamelody/wiki

  * JavaMelody [Issues](../issues), [Releases (downloads)](../releases), [Release notes](ReleaseNotes), [User's guide](UserGuide) have new pages.
  * Contributors to code can now fork the github [repository](..) and submit [pull requests](../pulls)
  * The repository of the [Grails plugin](http://www.grails.org/plugin/grails-melody) is also moved to https://github.com/javamelody/grails-melody-plugin
  * The repository of the [Liferay plugin](UserGuide#liferay-plugin) is moved to https://github.com/javamelody/liferay-javamelody
  * The repository of the [Sonar plugin](UserGuide#sonar-plugin) is moved to https://github.com/javamelody/sonar-javamelody
