### ISSUE TITLE
Catch StackOverflowError when applying sql-transform-pattern

### ISSUE THREAD

**Issue by stoerr** [javamelody/javamelody#480]
We had some trouble since we deployed a complicated regex as sql-transform-pattern in JavaMelody 1.55.0, with which Matcher.replaceAll in net.bull.javamelody.Counter.getAggregateRequestName sometimes threw an uncaught StackOverflowError, causing the JDBC request to fail. (See http://stackoverflow.com/q/7509905/21499 for an example how this can happen). This took us quite some time to diagnose, and it would have been very unpleasant in production - not appropriate for a monitoring software. :-)

So I suggest to wrap the pattern replacement in net.bull.javamelody.Counter.getAggregateRequestName into a try catch, which catches StackOverflowError (and probably RuntimeException as well) and just uses the unchanged requestName, instead. That's something much better than having the request fail.

You might also want to log the error, since something like that shouldn't go unnoticed.

(BTW, for people who do get an StackOverflowError: you might want to use the advice of http://stackoverflow.com/a/7510006/21499 to not use repetitive alternative paths (A|B)* if possible; in our case using posessive quantifiers instead of the normal greedy quantifiers did also do the trick, not quite sure why. :-)

**Comment by evernat** [comment]
OK, I have added a catch StackOverflowError.
This is fixed in commit b4267c8c54beb63ee37e175c45046c2f9765b828 and ready for the next release (1.57).
