### ISSUE TITLE
javamelody 1.56 project run at  in tomcat 7 or tomcat 8  config web.xml param is invalid 

### ISSUE THREAD

**Issue by rjzou** [javamelody/javamelody#481]
javamelody 1.56 project run at  in tomcat 7 or tomcat 8  , set filter class net.bull.javamelody.MonitoringFilter   web.xml  init-param  is 
Invalid。i test javamelody 1.55,1.54 is all invalid。

pleas help me.thankyou!

**Comment by rjzou** [comment]
eg : 
<filter>
          <filter-name>monitoring</filter-name>
          <filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
          <async-supported>true</async-supported>
           <init-param>
            
            <param-name>monitoring-path</param-name>
            <param-value>/admin/javamelody</param-value>
        </init-param>
        <init-param>
            
            <param-name>disabled</param-name>
            <param-value>false</param-value>
        </init-param>
          <init-param>
       		<param-name>storage-directory</param-name>
            <param-value>${catalina.base}/javamelody-data</param-value>
          </init-param>
    </filter>
     <filter-mapping>
        <filter-name>monitoring</filter-name>
        <url-pattern>/*</url-pattern>
         <dispatcher>REQUEST</dispatcher>
        <dispatcher>ASYNC</dispatcher>
    </filter-mapping>
  	<listener>
         <listener-class>net.bull.javamelody.SessionListener</listener-class>
 	</listener>

it is init-param monitoring-path,disabled,storage-directory in tomcat 7,8  is all invalid。

**Comment by evernat** [comment]
Your issue is invalid, because you did not say what is the problem (what happens? what error? where?) and you should post your web.xml as text, not as screenshot.
