### ISSUE TITLE
Invalid characters on monitoring page for JIRA 6.4.4+

### ISSUE THREAD

**Issue by Baartt** [javamelody/javamelody#482]
We encounter a bug on JIRA new versions with the monitoring page of javamelody, it shows invalid characters apparently due to gzip compression.

The plugin (version 1.56.0) works fine on JIRA 6.4.3 but fails on the more recent versions (6.4.4 to latest).

![javamelody gzip issue](https://cloud.githubusercontent.com/assets/6860896/8826003/7fa3a830-3083-11e5-8548-1a042535b10a.jpg)

A user posted the exact problem on atlassian issue tracker but I did not see it on yours so I'm just forwarding it, as the problem looks to be on the plugin's side.
Here you can find the relative issue : https://jira.atlassian.com/browse/JRA-44059

Do you have any solution better than disabling GZIP compression or stay in jira 6.4.3?
A fix would be really appreciated, we actually can't afford to loose performances on our JIRA by disabling GZIP compression, and we want to stay up-to-date with the latest version.

**Comment by evernat** [comment]
Yes there are 2 others solutions: system property or nightly build before next release.

This is a known compatibility issue with the latest versions of JIRA.
There is a question-answer at:
https://answers.atlassian.com/questions/16878185/javamelody-plugin-1.55.0-and-1.56.0-not-working-with-jira-6.4.5
and the same in the javamelody users' group at:
https://groups.google.com/forum/#!topic/javamelody/gNjfBOk04h8

The next release of the javamelody plugin (1.57) will disable its own gzip compression.
Nightly build is already available at:
https://javamelody.ci.cloudbees.com/job/javamelody/ws/javamelody-core/jira-javamelody.jar

**Comment by Baartt** [comment]
Thanks a lot for the quick answer evernat, I'll go for the nightly build for now :-)
