### ISSUE TITLE
 javamelody 1.56 project run at in tomcat 7 or tomcat 8 config "monitoring-path" and "storage-directory" web.xml param is invalid

### ISSUE THREAD

**Issue by rjzou** [javamelody/javamelody#483]
<?xml version="1.0" encoding="UTF-8"?>
<web-app 
    xmlns="http://java.sun.com/xml/ns/javaee"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
    version="3.0">
	<display-name>agent</display-name>
 		
 	
	
	<context-param>
		<param-name>contextConfigLocation</param-name>
		<param-value>
		classpath:net/bull/javamelody/monitoring-spring.xml
		classpath*:applicationContext.xml
		</param-value>
	</context-param>
	<listener>
		<listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
	</listener>
	<listener>
		<listener-class>
			org.springframework.web.context.request.RequestContextListener</listener-class>
	</listener>

	<filter>
		<filter-name>shiroFilter</filter-name>
		<filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
		<init-param>
			<param-name>targetFilterLifecycle</param-name>
			<param-value>true</param-value>
		</init-param>
	</filter>
	<filter-mapping>
		<filter-name>shiroFilter</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>
	

 		<login-config>
                <auth-method>BASIC</auth-method>
                <realm-name>Monitoring</realm-name>
        </login-config>
        <security-role>
                <role-name>monitoring</role-name>
        </security-role>
        <security-constraint>
                <web-resource-collection>
                        <web-resource-name>Monitoring</web-resource-name>
                        <url-pattern>/monitoring</url-pattern>
                </web-resource-collection>
                <auth-constraint>
                        <role-name>monitoring</role-name>
                </auth-constraint>
        </security-constraint>
     <filter>
          <filter-name>monitoring</filter-name>
          <filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
          <async-supported>true</async-supported>
           <init-param>
            
            <param-name>monitoring-path</param-name>
            <param-value>/monitoring</param-value>
        </init-param>
        <init-param>
            
            <param-name>disabled</param-name>
            <param-value>false</param-value>
        </init-param>
          <init-param>
       		<param-name>storage-directory</param-name>
            <param-value>${catalina.base}/javamelody-data</param-value>
          </init-param>
          
    </filter>
     <filter-mapping>
        <filter-name>monitoring</filter-name>
        <url-pattern>/*</url-pattern>
         <dispatcher>REQUEST</dispatcher>
        <dispatcher>ASYNC</dispatcher>
    </filter-mapping>
  	<listener>
         <listener-class>net.bull.javamelody.SessionListener</listener-class>
 	</listener>
 	
		
	<filter>
		<filter-name>encodingFilter</filter-name>
		<filter-class>org.springframework.web.filter.CharacterEncodingFilter</filter-class>
		<init-param>
			<param-name>encoding</param-name>
			<param-value>UTF-8</param-value>
		</init-param>
		<init-param>
			<param-name>forceEncoding</param-name>
			<param-value>true</param-value>
		</init-param>
	</filter>
	<filter-mapping>
		<filter-name>encodingFilter</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>
	

	
	
	<servlet>
		<servlet-name>CaptchaServlet</servlet-name>
		<servlet-class>com.eeepay.agent.auth.CaptchaServlet</servlet-class>
	</servlet>
	<servlet-mapping>
		<servlet-name>CaptchaServlet</servlet-name>
		<url-pattern>/servlet/captchaCode</url-pattern>
	</servlet-mapping>
	
	
	<servlet>
		<servlet-name>mvc</servlet-name>
		<servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
		<init-param>
			<param-name>contextConfigLocation</param-name>
			<param-value>classpath*:mvc-servlet.xml</param-value>
		</init-param>
		<load-on-startup>1</load-on-startup>
		
	</servlet>
	<servlet-mapping>
		<servlet-name>default</servlet-name>
		<url-pattern>*.png</url-pattern>
		<url-pattern>*.jpg</url-pattern>
		<url-pattern>*.gif</url-pattern>
		<url-pattern>*.js</url-pattern>
		<url-pattern>*.css</url-pattern>
		<url-pattern>*.ico</url-pattern>
		<url-pattern>*.swf</url-pattern>
		<url-pattern>*.zip</url-pattern>
		<url-pattern>*.rar</url-pattern>
		<url-pattern>*.apk</url-pattern>
	</servlet-mapping>
	<servlet-mapping>
		<servlet-name>mvc</servlet-name>
		<url-pattern>/</url-pattern>
	</servlet-mapping>
	
	
	
	<filter>
		<filter-name>sitemeshFilter</filter-name>
		<filter-class>com.opensymphony.sitemesh.webapp.SiteMeshFilter</filter-class>
	</filter>
	<filter-mapping>
		<filter-name>sitemeshFilter</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>
	
	<servlet>
		<servlet-name>uploadFile</servlet-name>
		<servlet-class>
			com.eeepay.agent.servlet.UploadServlet
		</servlet-class>
	</servlet>
	<servlet-mapping>
	    <servlet-name>uploadFile</servlet-name>
	    <url-pattern>/servlet/upload</url-pattern>
  	</servlet-mapping>
	<jsp-config>
		<taglib>
			<taglib-uri>/WEB-INF/pagebar.tld</taglib-uri>
			<taglib-location>/WEB-INF/pagebar.tld</taglib-location>
		</taglib>
	</jsp-config>
	<session-config>
	  <session-timeout>400</session-timeout>
	</session-config>
</web-app>

this is web.xml;

tomcat 7,8 startup debug  log is 

09:13:41.436 [localhost-startStop-1] DEBUG net.bull.javamelody - JavaMelody filter init started
09:13:41.440 [localhost-startStop-1] DEBUG net.bull.javamelody - OS: Windows 7 Service Pack 1, amd64/64
09:13:41.440 [localhost-startStop-1] DEBUG net.bull.javamelody - Java: Java(TM) SE Runtime Environment, 1.8.0_45-b15
09:13:41.440 [localhost-startStop-1] DEBUG net.bull.javamelody - Server: Apache Tomcat/7.0.47
09:13:41.440 [localhost-startStop-1] DEBUG net.bull.javamelody - Webapp context: /agent
09:13:41.440 [localhost-startStop-1] DEBUG net.bull.javamelody - JavaMelody version: 1.56.0
09:13:41.440 [localhost-startStop-1] DEBUG net.bull.javamelody - JavaMelody classes loaded from: file:/e:/repository/net/bull/javamelody/javamelody-core/1.56.0/javamelody-core-1.56.0.jar
09:13:41.441 [localhost-startStop-1] DEBUG net.bull.javamelody - Host: YOS-20150703CDB@192.168.4.16
09:13:41.452 [localhost-startStop-1] DEBUG net.bull.javamelody - log listeners initialized
09:13:41.453 [localhost-startStop-1] DEBUG net.bull.javamelody - datasources found in JNDI: []
09:13:41.458 [localhost-startStop-1] DEBUG net.bull.javamelody - counters initialized
09:13:41.583 [localhost-startStop-1] DEBUG net.bull.javamelody - counters data read from files in C:\Users\ADMINI~1\AppData\Local\Temp\javamelody\agent_YOS-20150703CDB
09:13:41.788 [localhost-startStop-1] DEBUG net.bull.javamelody - collect task scheduled every 60s
09:13:42.300 [localhost-startStop-1] DEBUG net.bull.javamelody - first collect of data done
09:13:42.301 [localhost-startStop-1] DEBUG net.bull.javamelody - JavaMelody filter init done in 865 ms

it is nothing "monitoring-path" and "storage-directory"  parameter defined;

**Comment by evernat** [comment]
try with <filter-name>javamelody</filter-name> instead of <filter-name>monitoring</filter-name>
as said at:
https://github.com/javamelody/javamelody/wiki/UserGuide#2-webxml-file

**Comment by rjzou** [comment]
this is bug ?   in tomcat6 is ok

**Comment by evernat** [comment]
no, it's servlet api 3
