### ISSUE TITLE
Add support for log4j2 and slf4j

### ISSUE THREAD

**Issue by georgethekkan** [javamelody/javamelody#484]
Javamelody currently supports only log4j, logback and java util logging

**Comment by evernat** [comment]
A pull request would be great.

**Comment by evernat** [comment]
javamelody now supports log4J 2 like log4J, logback and java.util.logging (068139d70dd65ff7574c5ec3cb15045af2f33d9f for v1.59), so closing this enhancement.

For slf4j, I do not understand exactly what you mean and if it's possible with "slf4j only". You may explain it here.
