### ISSUE TITLE
java melody does not works

### ISSUE THREAD

**Issue by gyuzelev** [javamelody/javamelody#490]
Hello all,

I executed instructions from: https://github.com/javamelody/javamelody/wiki/AtlassianPlugin for my Jira instance.

"For this, download the jira-javamelody.jar file of the plugin and copy the file: * in the "JIRA x.x.x/atlassian-jira/WEB-INF/lib" directory for JIRA, * in "Bamboo/atlassian-bamboo/WEB-INF/lib" for Bamboo (or in "Bamboo/webapp/WEB-INF/lib" for older Bamboo) * or upload the file with the "Plugin manager" in the "Administration" menu for Confluence.

Restart the server.

Then you can open the report from the address http://<host>:<port>/monitoring (the "Monitoring" link is also available in the "Administration" menu). That's it in general."

In spite of everything I see no Administration menu in Jira and no Monitoring page. I delete plaugin restart the server and try again. The same - nothing. 

Would you advise me how to proceed to have working monitoring with Java Melody? I use Jira 6.4.10.

Thank you in advance,
Plamen Gyuzelev

**Comment by evernat** [comment]
1. Closing this issue because of inaccurate title.
2. For the Monitoring link, in a recent JIRA, you can find the link in the "Manage add-ons" page of the Administration menu.
