### ISSUE TITLE
work perfectly in win 7, but can not work in CentOS6.5

### ISSUE THREAD

**Issue by eacdy** [javamelody/javamelody#491]
### tomcat 7
javamelody can work perfectly !

### tomcat 8
it can not work any more .
### chrome shows
ERR_CONTENT_DECODING_FAILED
### firefox comes the error
Firefox shows "Content Encoding Error"

#### web.xml
```
    <filter>
        <filter-name>monitoring</filter-name>
        <filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
        <async-supported>true</async-supported>
        <init-param>
            <param-name>gzip-compression-disabled</param-name>
            <param-value>true</param-value>
        </init-param>
    </filter>
    <filter-mapping>
        <filter-name>monitoring</filter-name>
        <url-pattern>/*</url-pattern>
        <dispatcher>REQUEST</dispatcher>
        <dispatcher>ASYNC</dispatcher>
    </filter-mapping>
    <listener>
        <listener-class>net.bull.javamelody.SessionListener</listener-class>
    </listener>
```
#### pom.xml
```
        <dependency>
            <groupId>net.bull.javamelody</groupId>
            <artifactId>javamelody-core</artifactId>
            <version>1.56.0</version>
        </dependency>
```

**Comment by evernat** [comment]
What say the logs of the server? (standard and error output)

**Comment by eacdy** [comment]
hello evernat :
Here is the code. 
https://github.com/eacdy/javamelody-test

I've fond the reason it can not work in linux is that javamelody can not work together with sitemesh.
when I modify web.xml like this:
```
    <!-- SiteMesh -->
    <filter>
        <filter-name>sitemeshFilter</filter-name>
        <filter-class>org.sitemesh.webapp.SiteMeshFilter</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>sitemeshFilter</filter-name>
        <url-pattern>/xxxxxx</url-pattern>
    </filter-mapping>
```
It can work perfectly.

How can I use javamelody with sitemesh?

**Comment by evernat** [comment]
in web.xml, put the MonitoringFilter like the following before the SiteMeshFilter
 
    <filter>
        <filter-name>javamelody</filter-name>
        <filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
        <async-supported>true</async-supported>
        <init-param>
            <param-name>gzip-compression-disabled</param-name>
            <param-value>true</param-value>
        </init-param>
    </filter>
    <filter-mapping>
        <filter-name>javamelody</filter-name>
        <url-pattern>/*</url-pattern>
        <dispatcher>REQUEST</dispatcher>
        <dispatcher>ASYNC</dispatcher>
    </filter-mapping>
    <listener>
        <listener-class>net.bull.javamelody.SessionListener</listener-class>
    </listener>

**Comment by eacdy** [comment]
thanks a lot!
