### ISSUE TITLE
Encoding issue if system setting and servlet setting are different

### ISSUE THREAD

**Issue by tedliang** [javamelody/javamelody#493]
If the encoding is forced to be UTF-8 by encodingFilter in web.xml, in Windows (default encoding CP1250) or Ubuntu Upstart mode (environment variable LANG is not set), it will have encoding issue if javamelody is used.

You can reproduce this issue with https://github.com/tedliang/springmvc-bootstrap. Check out and run it with tomcat 7/8 in Windows or passing an empty environment variable LANG in linux, the characters (Hello in different languages) under 'Download Now' button in the home page will not display properly if javamelody is used.

**Comment by evernat** [comment]
This is not a bug.
If you really want to force encoding with CharacterEncodingFilter, it must be the first filter in general.
To be sure that the MonitoringFilter is after the CharacterEncodingFilter, add the following in web.xml after filter and filter-mapping of CharacterEncodingFilter:
```
	<filter>
		<filter-name>javamelody</filter-name>
		<filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
		<async-supported>true</async-supported>
	</filter>
	<filter-mapping>
		<filter-name>javamelody</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>
	<listener>
		<listener-class>net.bull.javamelody.SessionListener</listener-class>
	</listener>
```
