### ISSUE TITLE
Use javamelody with collector server

### ISSUE THREAD

**Issue by stepio** [javamelody/javamelody#499]
First of all, thank you for the great module!

I'm configuring the optional collector server - want to have a single access point for all the monitored applications.

After trying this approach I see next message on the each of a separate applications:
"Do not use this monitoring page if you use the optional collector server: either use the monitoring page from the webapp, without a collector server, or use the page from the collector server"

Now I have few questions about this configuration:
1. Is it possible, that the message is displayed even although the appropriate collector server is already down?
2. If 1 is correct, how to "reset" this? Is there some flag to clear?
3. Also if 1 is correct, is it possible to find if an application is currently collected externally? Is it possible to identify such a collector to prevent conflicts?

**Comment by evernat** [comment]
1. Yes. The message would be displayed even if the collector server is down.
2. If you have changed your mind and you don't want to use the collector server anymore, you must restart the monitored application.
3. It's not possible in javamelody. But if you have an access log in Apache httpd or in your app server, you can find the ip address which is still calling the /monitoring URL.

**Comment by stepio** [comment]
Thank you very much for the tips - it's clear now.
