### ISSUE TITLE
Define history retention policy

### ISSUE THREAD

**Issue by Fbo-AH** [javamelody/javamelody#506]
It would be nice if you can add a setting to define the period of reference for data retention to prevent temporary data to grow.

Example : Clear history data after 1 month

Best regards.

**Comment by evernat** [comment]
There are already javamelody parameters to define the retention delays:
- "obsolete-graphs-days" to define the retention of obsolete graph files (rrd) in days (default: 90),
- "obsolete-stats-days" to define the retention of stats files (ser.gz) in days (default: 365).
They can be defined like the other javamelody parameters.
And they are not documented for sake of brevity of the user's guide.

**Comment by Fbo-AH** [comment]
Thank you very much, it is very important I mean :)

Best regards,
