### ISSUE TITLE
Latest release 1.57.1 not published to Maven Central

### ISSUE THREAD

**Issue by prismsoundzero** [javamelody/javamelody#509]
Hi, seems that the latest release 1.57.1 has not been published to Maven Central repository yet.

**Comment by evernat** [comment]
Only javamelody plugin for jira/confluence/bamboo was released as v1.57.1, to fix a blocker issue with JIRA 7.
Otherwise javamelody v1.57.0 is available in github releases and in Maven central.

**Comment by prismsoundzero** [comment]
Alright, so when can we expect [the fix for the monitoring of datasources in Wildfly 9](https://github.com/javamelody/javamelody/commit/45203cfe67eaeaf5984423532cfe4b7d5ce6746c) to be published? It is tagged as javamelody-core-1.57.1 so that's why I thought a new release of the core had been published.

**Comment by evernat** [comment]
In fact, it will be released in 1.58.0. Perhaps at end of November.
