### ISSUE TITLE
/VERSION.properties conflicts with jgroups

### ISSUE THREAD

**Issue by james-hu** [javamelody/javamelody#511]
Both javamelody and jgroups expect /VERSION.properties exists in the class path and both of them have its own version of VERSION.properties packaged in the jar file. If javamelody and groups are used together, jgroups fails to initialise its Version.class

I know this is not the fault of javamelody, but moving VERSION.properties in javamelody to somewhere else looks like the easiest solution.

**Comment by evernat** [comment]
I have renamed VERSION.properties to JAVAMELODY-VERSION.properties to remove conflict ([2e944e3](../commits/2e944e38abb9c8d1716fb3d97b7d35c9f862d4c2)).
Thanks for the issue.

**Comment by evernat** [comment]
I have created a jgroups issue to suggest the same for them:
https://issues.jboss.org/browse/JGRP-1978

**Comment by james-hu** [comment]
thanks!
