### ISSUE TITLE
Collect server authentication

### ISSUE THREAD

**Issue by fcbflying** [javamelody/javamelody#512]
I download the collect server javameldoy-1.57.0.war.
I start it and add some applications.
Now I want to add authentication for collect server access.
So I try following command to start the server:
java -server -Xmx128m -jar javamelody-1.57.0.war --httpPort=8081 --argumentsRealm.passwd.test=123

Does it mean username=test and password=123?
But when I try to access my collect server,  no reminder for me to input username and password.
Anything I missing?

Could you show me how to set username and password for collect server access.

**Comment by evernat** [comment]
argumentsRealm.passwd.<user> and argumentsRealm.roles.<user> are for adding user and role in the server realm (which is certainly useless without adding security constraint in web.xml).
To secure the collect server with basic auth, just add a system property javamelody.authorized-users.
For example:
java -server -Xmx128m -Djavamelody.authorized-users=test:123,user2:pwd2 -jar javamelody-1.57.0.war --httpPort=8081

I have removed the "realm" arguments from the usage help in order not to have confusion.

**Comment by fcbflying** [comment]
@evernat  Thanks very much.
