### ISSUE TITLE
Allow to forward monitoring operation

### ISSUE THREAD

**Issue by jglapa** [javamelody/javamelody#513]
Hi, I find it quite limiting that the request to `monitoring` page cannot be internally forwarded with a dispatcher.

I believe that this if statement is not allowing that:
https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/MonitoringFilter.java#L168

My use-case would be:
I would like to pull some metrics from javamelody through the  ExternalAPI(jmxValue).
The problem is that the  `monitoring` page in my app is secured and only authenticated and authorized people can see it.
What I wanted to do is to create a separate Controller that would be "public" and allow to access the ExternalAPI in a limited way.
So forward operation would be perfect for this(internally authentication and authorization will be ignored) but unfortunately the `doMonitoring` in the `MonitoringFIlter` is not reached b/c the `RequestURI` differs from the `MonitoringURL`.

Or perhaps there is a different way?

**Comment by evernat** [comment]
I think that you can use the net.bull.javamelody.ReportServlet already available in javamelody.
For that, add the following to your web.xml:
<servlet>
    <servlet-name>monitoringServlet</servlet-name>
    <servlet-class>net.bull.javamelody.ReportServlet</servlet-class>
</servlet>
<servlet-mapping>
    <servlet-name>monitoringServlet</servlet-name>
    <url-pattern>/admin/monitoring</url-pattern>
</servlet-mapping>

Reference : https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#using-a-servlet-to-display-the-monitoring-reports

Then you should of course secure the url you have chosen in the url-pattern above like you have done for the MonitoringFilter.
And keep your separate and "public" Controller but forward to ReportServlet (in the example, to "/admin/monitoring").
That way the ReportServlet will respond to the jmxValue request and there's no problem with RequestURI different than the MonitoringURL.

**Comment by jglapa** [comment]
:+1: thanks, worked like a charm
