### ISSUE TITLE
compilation error - missing java.lang.AutoCloseable (jdk 1.7 class)

### ISSUE THREAD

**Issue by sreev** [javamelody/javamelody#517]
javamelody-core/pom.xml sets the source & target to java 1.6.

**Comment by sreev** [comment]
![screen shot 2015-12-02 at 13 01 42](https://cloud.githubusercontent.com/assets/441385/11545274/52717e74-98fb-11e5-94ea-3c7fee53deaf.png)

**Comment by evernat** [comment]
Your problem in Eclipse is only a problem in Eclipse. It does not say that the target java version for compilation should be changed from 1.6 to 1.7 in pom.xml. In particular, given that a large number of jdk 1.6 users will not be able to upgrade javamelody anymore (that would be a blocker regression).

If you do not want a problem in Eclipse, you just have to configure a JDK 1.7 in Eclipse / Windows / Preferences.

**Comment by sreev** [comment]
User always finds a work around.  The intention here is not let pom.xml dictate that.

FYI!
http://www.oracle.com/technetwork/java/eol-135779.html
6 end of life feb 2013 and 7 end of life apr 2015.

**Comment by evernat** [comment]
pom.xml must have 1.6 as java target version, because some javamelody users still use java 1.6, even if EOL, and javamelody should support java 1.6.
