### ISSUE TITLE
remove eclipse specific artifacts

### ISSUE THREAD

**Issue by sreev** [javamelody/javamelody#519]
clean up the eclipse specific artifacts.

update .gitignore; add .project .classpath and other eclipse artifacts; to block future check-ins/commits of these files specific to individual developer machines.

**Comment by evernat** [comment]
Won't fix

**Comment by sreev** [comment]
hi evernat,
you do not have to fix it. i will fix it. and send you a pull request.
thanks
sree

**Comment by evernat** [comment]
No PR for this. thanks.

**Comment by sreev** [comment]
It is not a Personal Request, evernat.
I just want to be sure, you didn't misunderstand me.
I raised the issue so, I can refer it in comments when I check-in / commit.

**Comment by evernat** [comment]
I think that I understood. I just don't want to add .project and .classpath in gitignore. So, no pull request.
