### ISSUE TITLE
missing JobBuilder and TriggerBuilder in quartz 1.5.2

### ISSUE THREAD

**Issue by sreev** [javamelody/javamelody#520]
These two classes were introduced in quartz v2.

![screen shot 2015-12-02 at 13 47 31](https://cloud.githubusercontent.com/assets/441385/11545309/8d88dc82-98fb-11e5-957d-58c252544814.png)

**Comment by evernat** [comment]
quartz 1.5.2 in pom.xml and that testing jsp are on purpose.
Have you seen that the jsp works well even if Eclipse does not understand it ?
Closing as invalid.

**Comment by sreev** [comment]
> Have you seen that the jsp works well even if Eclipse does not understand it ?
Totally, agree.

Do you know, how so ?

**Comment by evernat** [comment]
I have written that jsp and I often use it to test. So I know.
