### ISSUE TITLE
Manual execution of garbage collection: show used memory

### ISSUE THREAD

**Issue by stoerr** [javamelody/javamelody#522]
Just a small enhancement. When one manually triggers a garbage collection from melody, the dialog shows how many memory is freed, but not how much is left uncollected. But it is often interesting how much memory is used permanently, which is difficult to find out with javamelody (compare issue #497 ). So I suggest to show this in the dialog as well, since the used memory will already have changed when the dialog is closed.

**Comment by evernat** [comment]
Good idea.
It's done now in master and ready for the next release (1.59).
