### ISSUE TITLE
DefaultAdvisorAutoProxyCreator causing error in Spring Boot 1.3

### ISSUE THREAD

**Issue by mallim** [javamelody/javamelody#523]
Hi All

Given Spring Boot 1.3.0.RELEASE
and JavaMelody is version 1.58.0
and JDK is 1.8
when using @ImportResource("classpath:net/bull/javamelody/monitoring-spring.xml")
there will be some @Service beans fail to inject due to Proxy error
and when taking out monitoring-spring.xml 
and work out bean by bean 
when DefaultAdvisorAutoProxyCreator is removed
then JavaMelody can work 

Is there any impact if the following bean is not declared?

````
    @Bean
    public DefaultAdvisorAutoProxyCreator makeDefaultAdvisor()
    {
        return new DefaultAdvisorAutoProxyCreator();
    }
````

Regards
Ian Lim

**Comment by evernat** [comment]
Hi Ian,
I do not understand "Is there any impact if the following bean is not declared?". (Where is that method?)

Anyway, you may want to use ```@ImportResource("classpath:net/bull/javamelody/monitoring-spring-aspectj.xml")``` instead of ```@ImportResource("classpath:net/bull/javamelody/monitoring-spring.xml")```. See #502 about that.
Otherwise, it would be better to give the source of a simple project to reproduce the issue.

**Comment by mallim** [comment]
Thanks for the tip.

@ImportResource("classpath:net/bull/javamelody/monitoring-spring-aspectj.xml") allows the whole application start without strange problem.

I will proceed to close this issue.
