### ISSUE TITLE
how can javamelody monitor the datasource in spring ?

### ISSUE THREAD

**Issue by Stayering** [javamelody/javamelody#525]
some people point out  to modify the web.xml  and applicationContext.xml  ,but it doesn't work to monitor the datasource 、sql and jdbc  in applicationContext.xml ,how to do? is there a  demo for javaee like that ?

**Comment by evernat** [comment]
If you have a DataSource in your Spring context, you can monitor your datasource.
See https://github.com/javamelody/javamelody/wiki/UserGuide#7-jdbc and scroll down to the paragraph for Spring datasource.

Note that it probably means to import a javamelody file which contains:
```xml
	<bean id="springDataSourceBeanPostProcessor" class="net.bull.javamelody.SpringDataSourceBeanPostProcessor">
 	</bean>
```

**Comment by Stayering** [comment]
can you show me a demo to work it out? or point out the detail in UserGuide , the paragraph <9. Business facades (if Spring)>    is right ? but I am still not clear! Thank u! It is the first answer for the question after I  use github!

**Comment by Stayering** [comment]
<bean id="springDataSourceBeanPostProcessor" class="net.bull.javamelody.SpringDataSourceBeanPostProcessor">
     </bean>
    
     <bean id="wrappedDataSource" class="net.bull.javamelody.SpringDataSourceFactoryBean">
        <property name="targetName" value="dataSource" />
    </bean>
