### ISSUE TITLE
Filter HTTP request URLs

### ISSUE THREAD

**Issue by stolp** [javamelody/javamelody#528]
First and foremost many thanks for creating this indispensable tool.

I would like to have more control over the HTTP request getting monitored, i.e. filter out some URL paths which I do not want counted towards the average HTTP response time.

In our case these are requests to /javax.faces.resource/listen.icepush.xml which really belong to the underlying framework and not the application.

Would it be possible to add filter criteria for this usecase?

**Comment by evernat** [comment]
The javamelody parameter url-exclude-pattern exists for that and accepts a regexp.
For example, you can have in your WEB-INF/web.xml file:
``` xml
<filter>
    <filter-name>javamelody</filter-name>
    <filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
    <init-param>
        <param-name>url-exclude-pattern</param-name>
        <param-value>(/javax\.faces\.resource/listen\.icepush\.xml|anotherurl)</param-value>
    </init-param>
</filter>
<filter-mapping>
    <filter-name>javamelody</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>
<listener>
    <listener-class>net.bull.javamelody.SessionListener</listener-class>
</listener>
```

Or you can set a javamelody.url-exclude-pattern context parameter or system property if you prefer.
See https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters

Is it ok for you?

**Comment by stolp** [comment]
I really overlooked this. Works perfectly. Thanks, you're the man.
