### ISSUE TITLE
Tomcat does not shutdown gracefully

### ISSUE THREAD

**Issue by AnishJoseph** [javamelody/javamelody#529]
I am running on tomcat 8, java 8 and javamelody 1.58. Tomcat does not shutdown gracefully since there are a bunch of DefaultQuartzScheduler threads running.
I know there was an earlier issue on this [https://groups.google.com/forum/#!topic/javamelody/tMj1wWu1I3U](url)

However this appears to be slightly different.
I have tried the following:
1)  Setting _quartz-default-listener-disabled _to _true_ in the init-param of the javamelody filter - unfortunately the following code (in class Parameters in method getParameterByName)
			`result = filterConfig.getInitParameter(parameterName);`
returns null - so setting the init-param did not do what was expected, and i saw the bunch of DefaultQuartzScheduler worker threads (this seem more of a tomcat bug- will follow that separately)

2) I then added the JVM option -Djavamelody.quartz-default-listener-disabled=true
In this case, in class Parameters, getParameterByName does get the value "true" and i see the log message in method addGlobalJobListener in class Quartz2Adapter

> Initialization of Quartz default listener has been disabled

BUT  i still get the bunch of DefaultQuartzScheduler worker threads

In both the above cases tomcat did not shutdown gracefully.

3) I then disabled javamelody completely - tomcat does shutdown gracefully.

4) I then re-enabled javamelody and added the following in web.xml 
` <listener>
        <listener-class>org.quartz.ee.servlet.QuartzInitializerListener</listener-class>
    </listener>
`
Tomcat shuts down gracefully.

I would prefer not to use the _listener_ mechanism. Ideas welcome? 

thx
joe
`

**Comment by AnishJoseph** [comment]
Update: I had made a mistake - by adding a listener in web.xml was causing the DefaultQuartzScheduler in case 2. 

So essentially adding the JVM option -Djavamelody.quartz-default-listener-disabled=true works perfectly. There are no  DefaultQuartzScheduler worker threads and tomcat shuts down gracefully.

However adding  quartz-default-listener-disabled as an init param for the javamelody filter does not work.

Will investigate this some more and post it here.

**Comment by AnishJoseph** [comment]
Sorry all - i had my filter definition for javamelody at the bottom. All worked as expected after moving it to before the before the description of the servlets. This is clearly mentioned in the user doc for javamelody but ...

**Comment by evernat** [comment]
ok, no problem
