### ISSUE TITLE
Collector server always creates new session when collect data

### ISSUE THREAD

**Issue by BaoTran90** [javamelody/javamelody#531]
Hi javamelody guys,

I'm configuring collector server to monitor my applications.

When testing the collector server, I got this problem:
- Collector server always creates new session when collecting data of application. So the number of sessions of application is too high but it's not session of users.

My application is using Spring Security for authentication.

But this problem is not happened when I monitor in each application.

Could you show me how to resolve this problem?

**Comment by evernat** [comment]
When the collector server calls the /monitoring url on the webapp to collect data, something and certainly a servlet filter other than the MonitoringFilter is creating a a session.
I suggest to put the following near the top of your web.xml, in order that there are no other servlet filter before the MonitoringFilter:
<filter>
    <filter-name>javamelody</filter-name>
    <filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
    <async-supported>true</async-supported>
</filter>
<filter-mapping>
    <filter-name>javamelody</filter-name>
    <url-pattern>/*</url-pattern>
    <dispatcher>REQUEST</dispatcher>
    <dispatcher>ASYNC</dispatcher>
</filter-mapping>
<listener>
    <listener-class>net.bull.javamelody.SessionListener</listener-class>
</listener>

If you are worried about the security of the /monitoring url, you can look at
https://github.com/javamelody/javamelody/wiki/UserGuide#16-security

Is it ok?

**Comment by BaoTran90** [comment]
Thanks for your prompt reply.

But I have one more question:
- Do I need to remove /monitoring url from Spring Security filter chain at below your suggest filter or not?

I'm afraid of Spring Security filter chain is creating session in this case.

Can I still use Spring security for authetication or not?

**Comment by evernat** [comment]
If you put the MonitoringFilter before the Spring Security filter, the /monitoring url will be removed from the Spring Security filter chain de facto.
I suggest to try that and see if it fixes the issue.

If yes, you could then look at your Spring configuration to understand why sessions are created by Spring Security (Spring Security does not force that). For example, you could read the following:
https://docs.spring.io/spring-security/site/docs/3.0.x/reference/appendix-namespace.html#create-session

Otherwise, if you still want to have some security without Spring Security, look at
https://github.com/javamelody/javamelody/wiki/UserGuide#16-security

**Comment by BaoTran90** [comment]
I have tried to put the MonitoringFilter before Spring Security filter, the issue is fixed but I can not restrict access to monitor application by using Spring Security anymore.

Could you explain for me the mechanism of collector server when collecting data from application? I guess that every when collecting data, the collector server will re-authenticate and create new session but the old session still exist.

Before, I have tried to use basic authentication for Javamelody instead of Spring Security. But there were some issues regarding basic authentication of Javamelody and form log in of Spring. There was unexpected pop-up showed on my application. 

I want to confirm that can I use both basic authentication for Javamelody and Spring Security for user log-in or not?

Thank you so much!

**Comment by evernat** [comment]
Yes you can use basic authentication for Javamelody and Spring Security for user log-in.
First, put the MonitoringFilter before the Spring Security filter and add the filter parameter [authorized-users](https://github.com/javamelody/javamelody/wiki/UserGuide#16-security).
For example:
```xml
<filter>
    <filter-name>javamelody</filter-name>
    <filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
    <async-supported>true</async-supported>
    <init-param>
        <param-name>authorized-users</param-name>
        <param-value>myusername:mypassword</param-value>
    </init-param>
</filter>
<filter-mapping>
    <filter-name>javamelody</filter-name>
    <url-pattern>/*</url-pattern>
    <dispatcher>REQUEST</dispatcher>
    <dispatcher>ASYNC</dispatcher>
</filter-mapping>
<listener>
    <listener-class>net.bull.javamelody.SessionListener</listener-class>
</listener>
```

Then you can add the monitored webapp with basic auth in the collector server by using an url like the following:
http://myusername:mypassword@myhost:8080/mywebapp
