### ISSUE TITLE
Java melody doesn't show graphs on RHEL Tomcat 7

### ISSUE THREAD

**Issue by VinodKadiyala** [javamelody/javamelody#534]
facing issues seeing graphs for application Hosted on RHEL Tomcat 7 . 
The graphs are not visible.  Image attached. 
![jmelody error](https://cloud.githubusercontent.com/assets/17618236/13497752/fa16468e-e124-11e5-8e55-642a37df9fc4.PNG)

**Comment by evernat** [comment]
Can you give the debugging logs displayed at the botton of the page, just after starting the server?

**Comment by VinodKadiyala** [comment]
Wed Mar 02 10:20:05 CST 2016     DEBUG     JavaMelody listener init started
Wed Mar 02 10:20:05 CST 2016     DEBUG     datasources found in JNDI: [java:comp/env/jdbc/opeds]
Wed Mar 02 10:20:05 CST 2016     DEBUG     datasource rebinded: java:comp/env/jdbc/opeds from class org.apache.tomcat.dbcp.dbcp.BasicDataSource to class $Proxy5
Wed Mar 02 10:20:05 CST 2016     DEBUG     JavaMelody listener init done in 134 ms
Wed Mar 02 10:20:06 CST 2016     DEBUG     spring interceptor initialized
Wed Mar 02 10:20:06 CST 2016     DEBUG     Spring datasource wrapped: dataSource
Wed Mar 02 10:20:08 CST 2016     DEBUG     JavaMelody filter init started
Wed Mar 02 10:20:08 CST 2016     DEBUG     OS: Linux unknown, amd64/64
Wed Mar 02 10:20:08 CST 2016     DEBUG     Java: OpenJDK Runtime Environment, 1.7.0_09-icedtea-mockbuild_2013_01_15_04_12-b00
Wed Mar 02 10:20:08 CST 2016     DEBUG     Server: Apache Tomcat/7.0.59
Wed Mar 02 10:20:08 CST 2016     DEBUG     Webapp context: /OnePayExtras
Wed Mar 02 10:20:08 CST 2016     DEBUG     JavaMelody version: 1.55.0
Wed Mar 02 10:20:08 CST 2016     DEBUG     JavaMelody classes loaded from: file:/opt/tomcat7/webapps/OnePayExtras/WEB-INF/lib/javamelody-core-1.55.0.jar
Wed Mar 02 10:20:08 CST 2016     DEBUG     Host: xyz.com@10.212.170.212
Wed Mar 02 10:20:08 CST 2016     DEBUG     log listeners initialized
Wed Mar 02 10:20:08 CST 2016     DEBUG     datasources found in JNDI: [java:comp/env/jdbc/opeds]
Wed Mar 02 10:20:08 CST 2016     DEBUG     counters initialized
Wed Mar 02 10:20:08 CST 2016     DEBUG     counters data read from files in /opt/tomcat7/temp/javamelody/OnePayExtras_xyz.com
Wed Mar 02 10:20:08 CST 2016     DEBUG     collect task scheduled every 60s
Wed Mar 02 10:20:09 CST 2016     DEBUG     first collect of data done
Wed Mar 02 10:20:09 CST 2016     DEBUG     JavaMelody filter init done in 501 ms
Thu Mar 03 00:00:09 CST 2016     DEBUG     Obsolete files deleted. JavaMelody disk usage: 4734 KB
Thu Mar 03 08:25:00 CST 2016     WARN     heaphisto report failed
Fri Mar 04 00:00:09 CST 2016     DEBUG     Obsolete files deleted. JavaMelody disk usage: 4741 KB
Sat Mar 05 00:00:09 CST 2016     DEBUG     Obsolete files deleted. JavaMelody disk usage: 4741 KB
Sun Mar 06 00:00:09 CST 2016     DEBUG     Obsolete files deleted. JavaMelody disk usage: 4741 KB
Mon Mar 07 00:00:09 CST 2016     DEBUG     Obsolete files deleted. JavaMelody disk usage: 4741 KB

**Comment by VinodKadiyala** [comment]
Tue Mar 08 08:20:54 CST 2016     DEBUG     counters data read from files in /opt/tomcat7/temp/javamelody/OnePayExtras_xyz
Tue Mar 08 08:20:54 CST 2016     DEBUG     collect task scheduled every 60s
Tue Mar 08 08:20:55 CST 2016     DEBUG     first collect of data done
Tue Mar 08 08:20:55 CST 2016     DEBUG     JavaMelody filter init done in 328 ms
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/usedMemory.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/cpu.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/httpSessions.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/activeThreads.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/activeConnections.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/usedConnections.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/gc.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/threadCount.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/loadedClassesCount.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/usedNonHeapMemory.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/usedPhysicalMemorySize.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/usedSwapSpaceSize.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/systemLoad.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/fileDescriptors.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/httpSessionsMeanAge.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/transactionsRate.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/Free_disk_space.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/tomcatBusyThreads.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/tomcatBytesReceived.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/tomcatBytesSent.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/httpHitsRate.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/sqlHitsRate.rrd
Tue Mar 08 09:17:54 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/springHitsRate.rrd
Tue Mar 08 09:19:09 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/usedMemory.rrd
Tue Mar 08 09:19:09 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/cpu.rrd
Tue Mar 08 09:19:09 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/httpSessions.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/activeThreads.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/activeConnections.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/usedConnections.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/gc.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/threadCount.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/loadedClassesCount.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/usedNonHeapMemory.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/usedPhysicalMemorySize.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/usedSwapSpaceSize.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/systemLoad.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/fileDescriptors.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/httpSessionsMeanAge.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/transactionsRate.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/Free_disk_space.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/tomcatBusyThreads.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/tomcatBytesReceived.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/tomcatBytesSent.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/httpHitsRate.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/sqlHitsRate.rrd
Tue Mar 08 09:19:10 CST 2016     DEBUG     A JRobin file was deleted and created again: /opt/tomcat7/temp/javamelody/OnePayExtras_xyz/springHitsRate.rrd


I see the above logs now. Could some one help with the graphs not displaying .

**Comment by evernat** [comment]
Its seems that the linux user running tomcat has an issue to write to the directory /opt/tomcat7/temp/javamelody/OnePayExtras_xyz.com (or OnePayExtras_xyz ?)
You should check linux permissions to write files.

**Comment by evernat** [comment]
Any news?

**Comment by evernat** [comment]
No response from the reporter, so closing as invalid / incomplete.
