### ISSUE TITLE
SQL stats only show stats for one out of three datasources

### ISSUE THREAD

**Issue by clarkgaybel** [javamelody/javamelody#535]
Given an application running with 3 datasources correctly identified by Javamelody: spark, scorm and quartz.
Then in the SQL stats table, only stats for queries to one of the datasource are displayed: quartz.
But sql stats for the 3 datasources are expected.

Here is the debug logs

Thu Mar 10 07:05:54 PST 2016     DEBUG     JavaMelody listener init started
Thu Mar 10 07:05:54 PST 2016     DEBUG     datasources found in JNDI: [java:comp/env/jdbc/spark, java:comp/env/jdbc/scorm, java:comp/env/jdbc/quartz]
Thu Mar 10 07:05:54 PST 2016     DEBUG     datasource rebinded: java:comp/env/jdbc/spark from class org.apache.tomcat.dbcp.dbcp.BasicDataSource to class com.sun.proxy.$Proxy236
Thu Mar 10 07:05:54 PST 2016     DEBUG     datasource rebinded: java:comp/env/jdbc/scorm from class org.apache.tomcat.dbcp.dbcp.BasicDataSource to class com.sun.proxy.$Proxy236
Thu Mar 10 07:05:54 PST 2016     DEBUG     datasource rebinded: java:comp/env/jdbc/quartz from class org.apache.tomcat.dbcp.dbcp.BasicDataSource to class com.sun.proxy.$Proxy236
Thu Mar 10 07:05:54 PST 2016     DEBUG     JavaMelody listener init done in 121 ms
Thu Mar 10 07:05:54 PST 2016     DEBUG     JavaMelody filter init started
Thu Mar 10 07:05:54 PST 2016     DEBUG     OS: Linux unknown, amd64/64
Thu Mar 10 07:05:54 PST 2016     DEBUG     Java: Java(TM) SE Runtime Environment, 1.8.0_45-b14
Thu Mar 10 07:05:54 PST 2016     DEBUG     Server: Apache Tomcat/6.0.44
Thu Mar 10 07:05:54 PST 2016     DEBUG     Webapp context: 
Thu Mar 10 07:05:54 PST 2016     DEBUG     JavaMelody version: 1.59.0
Thu Mar 10 07:05:54 PST 2016     DEBUG     JavaMelody classes loaded from: file:/opt/j2ee/domains/trainingrocket.com/instance/webapps/customware-spark/deployments/trainingrocket-2016.1.4.0-rc1/exploded_war/WEB-INF/lib/javamelody-1.59.0.jar
Thu Mar 10 07:05:54 PST 2016     DEBUG     Host: test-performance.trainingrocket.com@172.17.0.5
Thu Mar 10 07:05:54 PST 2016     DEBUG     log listeners initialized
Thu Mar 10 07:05:54 PST 2016     DEBUG     datasources found in JNDI: [java:comp/env/jdbc/spark, java:comp/env/jdbc/scorm, java:comp/env/jdbc/quartz]
Thu Mar 10 07:05:55 PST 2016     DEBUG     job global listener initialized
Thu Mar 10 07:05:55 PST 2016     DEBUG     counters initialized
Thu Mar 10 07:05:55 PST 2016     DEBUG     counters data read from files in /tmp/javamelody/_test-performance.trainingrocket.com
Thu Mar 10 07:05:55 PST 2016     DEBUG     collect task scheduled every 60s
Thu Mar 10 07:05:55 PST 2016     DEBUG     first collect of data done
Thu Mar 10 07:05:55 PST 2016     DEBUG     JavaMelody filter init done in 1087 ms

**Comment by evernat** [comment]
Perhaps your application looks up the datasources before the init of the javamelody listener.
You can try to add a javamelody parameter, as a system property for example: -Djavamelody.rewrap-datasources=true (This is an undocumented parameter.)

**Comment by clarkgaybel** [comment]
Ok. I'll try adding the parameter in the web.xml first. I'll let you know the result.

**Comment by clarkgaybel** [comment]
Perfect! it's working nicely adding the init parameter in the web.xml!
Given it's not a documented, may I ask if there is any known reason not to enable this parameter?
Or is it just a documentation bug?

**Comment by evernat** [comment]
This parameter is not needed in general, and rarely needed in fact. That's why it is undocumented.
There is probably something special in your webapp, like something with a servlet listener looking up datasources and keeping them in cache.
