### ISSUE TITLE
tomcat7 cannot shutdown after integrated javamelody

### ISSUE THREAD

**Issue by wisemyth** [javamelody/javamelody#539]
after integrated javamelody ,run the shell bin/shutdown.sh cannot shutdown tomcat.
checking the log file 'catalina.out' ,founded bellow error:

[DEBUG][12:18:10] PoolingHttpClientConnectionManager:394 Connection manager shut down
log4j:WARN No appenders could be found for logger (net.bull.javamelody).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
三月 23, 2016 12:18:10 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
严重: The web application [/pindan] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, 
the JDBC Driver has been forcibly unregistered.
三月 23, 2016 12:18:10 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
严重: The web application [/pindan] appears to have started a thread named [startQuertz_Worker-1] but has failed to stop it. This is very likely to create a memory leak.
三月 23, 2016 12:18:10 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
严重: The web application [/pindan] appears to have started a thread named [startQuertz_Worker-2] but has failed to stop it. This is very likely to create a memory leak.

**Comment by evernat** [comment]
You probably need to add the javamelody parameter quartz-default-listener-disabled.
For example: -Djavamelody.quartz-default-listener-disabled=true
See https://github.com/javamelody/javamelody/wiki/UserGuide#13-batch-jobs-if-quartz
