### ISSUE TITLE
Support "read-only" mode

### ISSUE THREAD

**Issue by dimarassin** [javamelody/javamelody#540]
Hi, I'd like to be able to run JavaMelody in "read-only" mode. That means to disable all actions which might change the process state, especially **"kill thread"** buttons.
Today this is a blocker for me to use JavaMelody in my services in production. 

Thanks in advance

**Comment by evernat** [comment]
This feature already exists. You can add a javamelody parameter "system-actions-enabled". For example, in system properties: `-Djavamelody.system-actions-enabled=false`
