### ISSUE TITLE
Download source code of collector server

### ISSUE THREAD

**Issue by BaoTran90** [javamelody/javamelody#541]
Hi javamelody guys,

Could you show me how to download the source code of collector server?

I just saw the source code of javamelody-core on GitHub. I want to run the collector server on my Eclipse and then debug to source code to research its collect method.

Thanks!!!

**Comment by evernat** [comment]
The source code of the collector server is at the same location as javamelody-core:
https://github.com/javamelody/javamelody/tree/master/javamelody-core
You can start from the CollectorServlet class.

There is also a maven projet:
https://github.com/javamelody/javamelody/blob/master/javamelody-collector-server/pom.xml
You can run `mvn jetty:run-exploded` in that directory to start the collector server.
