### ISSUE TITLE
sortable.js

### ISSUE THREAD

**Issue by Zyzygy** [javamelody/javamelody#543]
Firstoff, forgive my ignorance I am an systems and infrastructure guy so my dev/code skills are minimal. 

I was asked by our Java dev team to deploy JavaMelody.  I was able to do so and we are using a collection server (1.59.0).  I have begun adding instances and now have quite a few.  I was looking at the code and it seems that kryogenix sortable.js is referenced there.  There must be a way to sort my list of numerous instances ascending alpha or something to that effect.  Perhaps this goes outside of your code or is off topic from JMelody (apologies in advance) but maybe you can guide me in the right direction to sort my list of instances.

Lastly, I have to commend you on a really simple, beautiful and granular look at our java/tomcat instances.

Zyg

**Comment by evernat** [comment]
The list of applications is sorted alphabetically when the collector server starts.
So you can just stop and start the collector server.

The code should also sort the applications alphabetically when a new one is added.
It's done now (619a4b0) for the next release.
Thanks.
