### ISSUE TITLE
Jmelody on WebSphere 7 or higher

### ISSUE THREAD

**Issue by VinodKadiyala** [javamelody/javamelody#548]
Hi 

Can we deploy the jmelody on websphere 7 or higher version?

I tried deploying and made the requried changes to application.xml file and web,xml file and bounced the jvm but am still not able to access the jmelody page.

**Comment by evernat** [comment]
In theory yes, javamelody is compatible with the servlet api version of websphere 7.
That said, I don't test javamelody in websphere myself.

**Comment by VinodKadiyala** [comment]
I am facing the 404 error on websphere 7 even after adding the custom properties to the server settings.
