### ISSUE TITLE
mutiple sessions for same user in java melody http sessions

### ISSUE THREAD

**Issue by KanagarajGanapathy** [javamelody/javamelody#551]
Dear Team,
Multiple HTTP sessions are created for the same user, we could verify this in java melody sessions. we confirmed with the user they are using single system for the login. is it an issue in java melody?  i have given the configuration details below.
jboss : JBoss Web/7.4.9.Final-redhat-1
java : Java(TM) SE Runtime Environment, 1.7.0_60-b19
javamelody : JavaMelody 1.59.0 
![muliple_sessions](https://cloud.githubusercontent.com/assets/18610422/15017907/d238160a-1217-11e6-9c78-e36496961545.png)

**Comment by evernat** [comment]
The sessions have different session ids, so I think that those sessions exist really in your app.
That would mean it is an issue in your app and not in javamelody.

That said if you give the source of a simple and valid project (using maven) to reproduce an issue in javamelody, we can look at it. (Still I doubt that it is an issue in javamelody.)

**Comment by KanagarajGanapathy** [comment]
Thanks for the update. I will share the source code of session management asap. For few sessions we don't see any ip address,browser,country and user information, so i think its not created from the application. please see the attachment below.
![capture](https://cloud.githubusercontent.com/assets/18610422/15105839/3dea4f70-15c5-11e6-9d97-41ed33807fab.PNG)
When i click any session id's in the attachment few are  "invalidated".[but why it is listing in http sessions in javamelody page?]
![capture1](https://cloud.githubusercontent.com/assets/18610422/15105874/8952b7b8-15c5-11e6-934d-17fee5c30762.PNG)
few sessions id's have some information about the javamelody class.
![capture3](https://cloud.githubusercontent.com/assets/18610422/15105883/a5a879ac-15c5-11e6-9e18-760266db348c.PNG)

**Comment by KanagarajGanapathy** [comment]
I think sessions which does not have ip address, country, browser , os and user is created by javamelody .

**Comment by evernat** [comment]
I don't think so.

If you give the source of a simple and valid project (using maven) to reproduce an issue in javamelody, we can look at it. I bet you will not do it.

**Comment by KanagarajGanapathy** [comment]
In java melody i could see invalidate sessions id also,when i click on any session id  invalidated message is displaying.[Session js-W1ZIv7F02vSzeT48GC2 2.gqe_AS02 invalidated ]
![capture1](https://cloud.githubusercontent.com/assets/18610422/15145464/01b9fb1c-16b6-11e6-9715-ff1bb22dbc0e.PNG)
![capture2](https://cloud.githubusercontent.com/assets/18610422/15145467/04a0b17c-16b6-11e6-9710-aa791889bc05.PNG).

Is it normal?
