### ISSUE TITLE
javamelody for JIRA/Confluence using JDBC Direction Configuration

### ISSUE THREAD

**Issue by 1cec0ldAlpha** [javamelody/javamelody#552]
Supporting a large landlord-tenant Atlassian suite environment, having the ability to view MySQL metrics for provided Atlassian products would be essential to provide a suite of services with a "five 9s" SLA. Viewing the SQL Metrics allows administrators to take proactive measures and identify potential bugs and such that may not close DB Connections correctly. 

However, my environment is configured using a "Direct JDBC" connection to our MySQL databases. Attempting to switch over from "Direct" to "Datasource" has not been the easiest to do following any documentation. Not to mention, reviewing a response from an Atlassian Support official regarding the comparison of "Direct JDBC" and "Data Source" connections the vendor does not recommend "Data Source" configurations as the Tomcat libraries may not be optimized for Atlassian Applications (https://answers.atlassian.com/questions/8629689/datasource-vs-jdbc). 

With that said, providing a Atlassian Suite of services for over 40k users, 600k issues, and 3.1 million hits a day to our Apache containers I am very nervous about switching over from "Direct" to "Data Source" as I have not tested the upgrade complexity of switching from one to the other. Is it possible to release a version of Javamelody that supports "Direct JDBC" configurations with the simplest/modest configurations to a Production environment under a 99.999% uptime? 

Thanks!

**Comment by evernat** [comment]
The performance of jndi datasources in Tomcat is good.  And I have not heard of performance issues after switching from "jdbc direct" to "jndi datasource".
In fact, it seems that JIRA uses the same DBCP as Tomcat datasources:
https://confluence.atlassian.com/adminjiraserver071/tuning-database-connections-802592189.html#Tuningdatabaseconnections-settings

Probably, you can switch to "jndi datasource" and keep an eye to see how it goes after a day or two.
If you are nervous about switching, I am ok to review your config before and after the switch if you want.

**Comment by evernat** [comment]
And by the way, configuring net.bull.javamelody.JdbcDriver to try to monitor "JDBC direct" in JIRA is said to not work (Unable to bootstrap application: The database driver (net.bull.javamelody.JbdcDriver) was not found in the class path).
See https://answers.atlassian.com/questions/38511562/javamelody-for-jira-configuration-

**Comment by evernat** [comment]
Closing this question for the moment, since it is answered as best as we can.
You can still add comments.

**Comment by 1cec0ldAlpha** [comment]
Thanks evernat!!

How could I add a link to the back-end jira database metrics onto the JavaMelody "Monitoring" page? I simply want to add the following hyperlink on the /monitoring page
https://jira.fqdn/jira/secure/admin/monitor_database.jspa

**Comment by evernat** [comment]
You can add a link in the popup menu available at the top and right of the page.
For that, add the following system properties (for example, in bin/setenv.sh or conf/catalina.properties):
-Djavamelody.custom-reports=JIRA_Database_Metrics
-Djavamelody.JIRA_Database_Metrics=/jira/secure/admin/monitor_database.jspa

**Comment by 1cec0ldAlpha** [comment]
Thanks again!
I am looking to create a link to the native database metrics for jira on the actual javamelody/monitoring page created by the javamelody plugin.

**Comment by evernat** [comment]
That's not possible.
