### ISSUE TITLE
Not able monitor Datasource in Jboss EAP 6.2.0

### ISSUE THREAD

**Issue by sakthivelmahesh** [javamelody/javamelody#553]
hi,

We are using Jboss EAP 6.2.0 and set up javaMelody 1.59.0

Datasource in our application is configured in spring config file.

We followed the steps mentioned in JavaMelody setup, 

We are still seeing the connections as 0.

Please help.

regards
Mahesh

**Comment by evernat** [comment]
Others have done the same and it works for them.
So this is not a valid issue.
It may have been valid if you had given the source of a simple project (using Maven) to reproduce the issue.
