### ISSUE TITLE
Clear counters up to a specific date

### ISSUE THREAD

**Issue by HonoluluHenk** [javamelody/javamelody#561]
Would be cool to only clear counter entries older than X days/months/years.

**Comment by evernat** [comment]
I do not think that this is an absolutely necessary feature. In fact, if you don't want older entries, you can just choose a period for that. For example, choose the day period if you don't want older statistics, or week, month or custom period,
Thanks for suggesting the idea anyway.

**Comment by HonoluluHenk** [comment]
The reason for this is not just display, but storage.
Operations does not allow files to grow endlessly and using a dedicated collector-server is (unfortunately) not an option :(
By regularly deleting old entries, we hope to keep database size in control.

**Comment by evernat** [comment]
Don't worry.
Files will not grow endlessly. They will be automatically deleted after 1 year for .ser.gz files. The size of RRD files is fixed to 34KB forever so they will not grow either. And obsolete RRD files are automatically deleted after 3 months.

If this is still too much for you, you can add javamelody parameters for example in web.xml or in system properties like the other javamelody parameters.
To keep data for 90 days only, the system properties can be:
-Djavamelody.obsolete-graphs-days=90    (default is 90)
-Djavamelody.obsolete-stats-days=90       (default is 365)

**Comment by HonoluluHenk** [comment]
thanks, you rock!
