### ISSUE TITLE
Deployment on Jboss EAP 6.x without modification of monitored webapps for Javamelody

### ISSUE THREAD

**Issue by varegala** [javamelody/javamelody#562]
Hi,

can anyone help me to configure javamelody in jboss eap 6.x without modifying applications.

Thanks in advance,
Vijaya

**Comment by evernat** [comment]
See https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#deployment-on-tomcat-without-modification-of-monitored-webapps-beta
Note that it was never tested for JBoss or supported for JBoss.
