### ISSUE TITLE
Issue monitoring dbcp BasicDataSource

### ISSUE THREAD

**Issue by rahulvikky** [javamelody/javamelody#565]
Hi,

I'm facing an issue setting up javamelody to monitor our App's datasource. Below is the stack trace.
Believe this is because of the mismatch b/w Javamelody's Spring supported version and our App's Spring version. Please let me know the Spring version beginning with that Javamelody supports and also it would be helpful if the same is updated in the documentation.

Error registering bean with name 'springDataSourceBeanPostProcessor' defined in class path resource [net/bull/javamelody/monitoring-spring.xml]: Class that bean class [net.bull.javamelody.SpringDataSourceBeanPostProcessor] depends on not found; nested exception is java.lang.NoClassDefFoundError: org/springframework/core/PriorityOrdered

**Comment by evernat** [comment]
org.springframework.core.Ordered exists since 2003 (about Spring v1), so I don't think that there is a mismatch between Spring versions.
But perhaps you do not have the spring-core jar file in your app. If so, you will need to add that spring-core jar file in your app, with the same version as others spring jar files.

**Comment by rahulvikky** [comment]
Ok, so I have been using the latest version of Java Melody (1.60) and the spring core version we use is 1.2.6 ( I know it's quite old but we are planning to upgrade our product version sometime next year and along with it the spring version).
The exception is due to the use of 'PriorityOrdered' for Data Source Post processor which I think was introduced in v1.36 or 1.37 of Java Melody, 
Hence my original request was to understand the javamelody version that would support our Spring version. Please assist.

**Comment by evernat** [comment]
As far as I know, all Spring versions are supported.
But for Spring 1.2.6, who else than you can know?

**Comment by rahulvikky** [comment]
Well, then I need to try with versions below 1.37.

I shall do that meanwhile could you let me know if there is any harm in removing monitoring-spring XMLs from the jar in case we set up JNDI for data source and hence, as per my understanding, there won't be a need for a Data source Post Processor ?  

Hopefully this is my last question related to this :)

**Comment by evernat** [comment]
There is no harm in removing monitoring-spring XMLs. But you don't need to remove it, you just have to not use it if you don't want it.
You can also write and use your-own-custom-monitoring-spring.xml file in your application if you want.
