### ISSUE TITLE
Monitoring average request size for webservices

### ISSUE THREAD

**Issue by svrolanski** [javamelody/javamelody#568]
Hi,

Running on Tomcat 7 and METRO webservices.
I got this webapp portal for monitoring field agents.
The application running on Psion EP10 handheld is using a lot of bandwidth.
I mean, some apps are using almost 4GB!!
That is a lot of data since we online transfer text.
I cannot monitor this with precision on the field application side.
So I'm trying to monitor this from the server side.

The problem is that the request size for the webservices calls are always zero.
Unlike the normal calls to access the monitoring webpage (GET for images, javascripts, css, etc.) that have the average size.

Thanks for any help,
Ser

**Comment by svrolanski** [comment]
Also, I think JavaMelody has some problems with basic auth (my webapp is using)

**Comment by evernat** [comment]
> The problem is that the request size for the webservices calls are always zero.
I do not reproduce the issue.

I suggest to look into your Tomcat's localhost_access_log* to see what are the different response sizes of the requests.
If you think that there is a real javamelody issue, you can submit here the sources of simple project (using maven if possible) to reproduce the issue.

**Comment by svrolanski** [comment]
OK, I will check that out first, thank you.

**Comment by evernat** [comment]
OK, we can reopen this issue if you have more info like a project to reproduce the issue.
