### ISSUE TITLE
Cannot kill tomcat threads

### ISSUE THREAD

**Issue by kailt** [javamelody/javamelody#569]
Hello,

I'm using the latest JavaMelody 1.6.0 and after I detected a stuck thread in my webapp, I tried to kill it and JavaMelody showed a notification that it had successfully killed the thread but I checked and the stuck thread was still there.

To install JavaMelody, I just dropped the two jars into my webapp's lib dir. Do I need to do anything else?

**Comment by evernat** [comment]
You don't have anything to do.
Killing a thread by Thread.stop() like javamelody does is certainly not guaranteed by the JVM and not recommended in general.
It generally works, but if it does not you can't do anything about it except restarting the JVM.
