### ISSUE TITLE
Unable to add pointcuts with java Config and Spring boot

### ISSUE THREAD

**Issue by afillatre** [javamelody/javamelody#570]
I'm using Java Melody (JM) 1.60 with Spring Boot (SB) 1.2.3.

I configured JM exactly like the SB example. JM works fine, but when I attempt to add another pointcut (cf below code), it doesn't work at all (others continue to work fine, though):

```java
	@Bean
	public MonitoringSpringAdvisor springRepositoryMonitoringAdvisor() {
		final MonitoringSpringAdvisor interceptor = new MonitoringSpringAdvisor();
		interceptor.setPointcut(new AnnotationMatchingPointcut(Repository.class));
		return interceptor;
	}
```

In the console, while SB is starting, I can see that the new bean is loaded (also I can get the application to stop on a breakpoint inside while SB starts), but I never see the metrics on my repositories.

Although, when I add the `@MonitoredWithSpring` on a repository, it appears in the metrics. Since I have hundreds of classes to monitor, it would be convenient not to have to add the `@MonitoredWithSpring` on all of them.

I hope the issue's description is accurate enough. Thanks for your work

**Comment by evernat** [comment]
Can you give the source of a simple project to reproduce the issue?

**Comment by afillatre** [comment]
Yes, here's the link: https://github.com/afillatre/java-melody-issue-570

I wasn't able to monitor any Spring bean with this one (and it has minimal configuration). Maybe I'm missing a dependency ? HTTP requests are well monitored though.
I also tried adding the `@MonitoringWithSpring ` annotation too, but no success either.

I hope that'll help anyway..

**Comment by afillatre** [comment]
I was able to make it work (with the simple example project), but not how I wanted to. See https://github.com/afillatre/java-melody-issue-570/tree/monitoring-spring.

What I did is the following:
 - activate the XML configuration (monitoring-spring.xml)
 - create a custom pointcut to monitor my custom annotation
 - add the retention type "RUNTIME" on my annotation (I forgot it earlier)

In my current project, I have a many projects that depend on one with the configuration, so I'd rather have the java configuration working, or else I would have to create an xml file for every one of them.

**Comment by evernat** [comment]
Yes, it is needed to `@Retention(RetentionPolicy.RUNTIME)` to your custom annotation.
But it is not needed:
- to activate the XML configuration (monitoring-spring.xml)
- neither to create a custom pointcut to monitor my custom annotation

I have just forgotten to add the following when replacing the import on monitoring-spring.xml by java methods:
```
@Bean
public DefaultAdvisorAutoProxyCreator getDefaultAdvisorAutoProxyCreator() {
	return new DefaultAdvisorAutoProxyCreator();
}
```
except that for some reason it does not work in your case with a custom annotation.
So instead of that method, you can just add the following in your `application.properties`:
```
spring.aop.proxy-target-class=true
```
(I will fix the JavaMelodyConfiguration example.)

**Comment by afillatre** [comment]
Sorry, I tried the following, but without any success:
 - `spring.aop.proxy-target-class=true` is not working at all (nothing is monitored)
 - adding the `DefaultAdvisorAutoProxyCreator` makes the controller being monitored, but I'm still unable to monitor my service.

Alongside with the `DefaultAdvisorAutoProxyCreator` bean, I did the following for the service. Either

```java
	@Bean
	public MonitoringSpringAdvisor springServiceMonitoringAdvisor() {
		final MonitoringSpringAdvisor interceptor = new MonitoringSpringAdvisor();
		interceptor.setPointcut(new AnnotationMatchingPointcut(Service.class, true)); // Not working either
		return interceptor;
	}
```

or 

```java
	@Bean
	public MonitoringSpringAdvisor springServiceMonitoringAdvisor() {
		final MonitoringSpringAdvisor interceptor = new MonitoringSpringAdvisor();
		interceptor.setPointcut(new AnnotationMatchingPointcut(Service.class));
		return interceptor;
	}

	@Bean
	public MonitoringSpringAdvisor springCustomServiceMonitoringAdvisor() {
		final MonitoringSpringAdvisor interceptor = new MonitoringSpringAdvisor();
		interceptor.setPointcut(new AnnotationMatchingPointcut(CustomService.class));
		return interceptor;
	}
```

I'm still unable to of the Service monitored. I pushed the code in the master branch of my example (with all of the above at once, just to be sure). Am I missing something ?

**Comment by evernat** [comment]
ah yes, it is also needed to add in your pom.xml:
<dependency>
   <groupId>org.aspectj</groupId>
   <artifactId>aspectjweaver</artifactId>
</dependency>

**Comment by afillatre** [comment]
My bad, I forgot to add the retention on the annotation on this branch. With it, is works, but only when I create another specific pointcut.

When I when to use the `new AnnotationMatchingPointcut(Service.class, true)`, I get AOP errors, even with the aspectj dependency, the cglib dependency (i had to be sure), and the `spring.aop.proxy-target-class=true` property on my application.properties.

I don't know if you want to investigate further this issue, but the main use case works now, so thanks a lot for it.
