### ISSUE TITLE
Enhancement: Option to send metrics to statsd 

### ISSUE THREAD

**Issue by waynr** [javamelody/javamelody#576]
- I have several services (Jenkins instances specifically) using javamelody
- Most of my other infrastructure is capable of sending data to statsd and/or graphite
- I want a way to compare my Jenkins statistics with other pieces of my infrastructure

...is this reasonable? If someone with more Java/javamelody experience is willing to offer me some advice on how to approach making this kind of change to the javamelody code base I would love to take on the work myself.

**Comment by evernat** [comment]
If you want to take a look, every value added to a graph goes into net.bull.javamelody.JRobin.addValue(double)

**Comment by evernat** [comment]
There are now options to send some metrics to Graphite or to AWS CloudWatch.
This is ready for the next release (1.68) probably in a few weeks.
Release notes: https://github.com/javamelody/javamelody/wiki/ReleaseNotes
You can see the CloudWatch commit for example: e65d6054acec4b1126a212b9ec4605c020c7186a

If you can, I would like to know if it works for you, etc.
You will need the doc: https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#sending-metrics-to-graphite
And you will need a build including those features. So you can download javamelody-core at: https://javamelody.ci.cloudbees.com/job/javamelody/net.bull.javamelody$javamelody-core/lastSuccessfulBuild/artifact/net.bull.javamelody/javamelody-core/1.68.0-SNAPSHOT/javamelody-core-1.68.0-SNAPSHOT.jar
Or you can download javamelody-collector-server at: https://javamelody.ci.cloudbees.com/job/javamelody-collector-server/net.bull.javamelody$javamelody-collector-server/lastSuccessfulBuild/artifact/net.bull.javamelody/javamelody-collector-server/1.68.0-SNAPSHOT/javamelody-collector-server-1.68.0-SNAPSHOT.war

I wish to know if these features work for you, if doc is OK for configuration of the feature, if metrics are correctly displayed (take screenshots) and if metrics names (and CloudWatch dimensions) are good or not (for filtering / aggregating ...), or any suggestions you have.
