### ISSUE TITLE
Documentation of parameter jpa-naming-strategy

### ISSUE THREAD

**Issue by HonoluluHenk** [javamelody/javamelody#579]
Hi

Here's some copy-pasta for the new parameter - including some shameless plug for my plugin :)

Optional Parameters
The parameter jpa-naming-strategy enables you to implement a custom naming schema for the JPA section. 
Currently, the parameter *must* be set up as system property since since the application server configures JPA before web components.
If given, the value must be a fully qualified name of a class implementing net.bull.javamelody.JpaNamingStrategy. The class *must* have a public no-args constructor.
Default: net.bull.javamelody.JpaDefaultNamingStrategy.

Hibernate -and probably other JPA providers- currently does not allow sane names for CriteriaQuery by itself. 
Until this is fully implemented in Hibernate, there exists an ugly workaround at https://github.com/HonoluluHenk/javamelody-jpa-naming-strategies.

**Comment by evernat** [comment]
Not needed anymore as said in:
https://github.com/javamelody/javamelody/pull/578
