### ISSUE TITLE
Problem with spring 4

### ISSUE THREAD

**Issue by aliaharbil** [javamelody/javamelody#584]
I integreted java melody with my spring boot 1.4 project coupled with spring security 4+ it didn't work at first and I had to change some deprecated import, at last it worked when i deleted this lines from the configuration class
@Bean
public DefaultAdvisorAutoProxyCreator getDefaultAdvisorAutoProxyCreator() {
	return new DefaultAdvisorAutoProxyCreator();
}
what does it do? Will I need to add them because it works fine without it

**Comment by evernat** [comment]
- change deprecated imports to new ones from spring boot 1.4 : yes
- you don't need to remove getDefaultAdvisorAutoProxyCreator(), just add the following dependency in your pom.xml:
```xml
<dependency>
   <groupId>org.aspectj</groupId>
   <artifactId>aspectjweaver</artifactId>
</dependency>
```
Note : e89048ac3d26322f9691bb3d6f3008c6c315d6fd

**Comment by aliaharbil** [comment]
Tank you for your answer, I ve tried to add the aspectjweaver dependecy but the outcome is still the same if the dafaultAdvisorAutoProxy line is not removed i cann't go past the login page without having an error, my request just don't reach the controller method an i keep being forwarded to my default error page

**Comment by evernat** [comment]
You can remove the getDefaultAdvisorAutoProxyCreator() method. At worst you will not have statistics of execution on controller and services.
