### ISSUE TITLE
cannot get Active threads and Active jdbc connections data

### ISSUE THREAD

**Issue by VincentDhWang** [javamelody/javamelody#588]
Hi:
    In my case, I cannot get Active threads and Active jdbc connections data. Do u know how to fix it?

**Comment by VincentDhWang** [comment]
Following is my conf.
web.xml
<filter>
        <filter-name>javamelody</filter-name>
        <filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
        <async-supported>true</async-supported>

        <init-param>
            <param-name>url-exclude-pattern</param-name>
            <param-value>/static/*</param-value>
            <param-name>locale</param-name>
            <param-value>en</param-value>
        </init-param>
    </filter>
    <filter-mapping>
        <filter-name>javamelody</filter-name>
        <url-pattern>/*</url-pattern>
        <dispatcher>REQUEST</dispatcher>
        <dispatcher>ASYNC</dispatcher>
    </filter-mapping>
    <listener>
        <listener-class>net.bull.javamelody.SessionListener</listener-class>
    </listener>

spring.xml
<bean id="springDataSourceBeanPostProcessor" class="net.bull.javamelody.SpringDataSourceBeanPostProcessor">
    </bean>

    <bean id="wrappedDataSource" class="net.bull.javamelody.SpringDataSourceFactoryBean">
        <property name="targetName" value="shardingDataSource" />
    </bean>

**Comment by evernat** [comment]
Probably you already have them.
Anyway, can you give the source of a simple project (using Maven) to reproduce the issue?

**Comment by VincentDhWang** [comment]
hi evernat:
Following is a simple project.
https://github.com/VincentDhWang/forTest

**Comment by evernat** [comment]
You may not see active threads displayed, if your calls are very short: a 1 ms request can not give an active thread for a noticeable period of time in the graph.
But in your controler, if I replace userDAO.insert(user) by Thread.sleep(500000) then I call the /test url and refresh the monitoring page, I see that there are active threads.
And so it works and the issue is invalid.

**Comment by VincentDhWang** [comment]
But i got  a blank graph, i think the graph will show the usage of some period, won't it?

**Comment by evernat** [comment]
If you have an active thread for 0.001% of the time, it is normal to have a blank graph

**Comment by VincentDhWang** [comment]
i got it,  thanks for your reply, evernat.
