### ISSUE TITLE
JIRA Javamelody

### ISSUE THREAD

**Issue by mattttttttttt** [javamelody/javamelody#589]
Hello, 

I have JIRA Javamelody installed on my JIRA instance.  The JIRA instance uses a JNDI connection to connect to its Microsoft SQL Server 2012 database.  While viewing the javamelody graphs, none of the SQL graphs populate, along with the SQL statistics area.

**Comment by evernat** [comment]
What version of JIRA do you use?
And can you give the "debugging logs" at the bottom of the report?

**Comment by mattttttttttt** [comment]
JIRA v7.2.4
What log file would you like?

**Comment by evernat** [comment]
I was not asking about a log file. I was asking about "debugging logs" :
1. Open the monitoring report. Ex : http://jira/monitoring
2. Go to the bottom
3. Click the "debugging logs" link
4. Copy the text displayed in this issue (after replacing possible secrets in the text).

**Comment by mattttttttttt** [comment]
Never mind - I found it.  There is some information that I have to sanitize before I send it....Is there specific information you require?

**Comment by mattttttttttt** [comment]
Sun Dec 04 01:08:22 CST 2016     DEBUG     JavaMelody listener init started
Sun Dec 04 01:08:22 CST 2016     DEBUG     datasources found in JNDI: [java:comp/env/jdbc/JiraDS]
Sun Dec 04 01:08:22 CST 2016     DEBUG     datasource rebinded: java:comp/env/jdbc/JiraDS from class org.apache.tomcat.jdbc.pool.DataSource to class com.sun.proxy.$Proxy$$$$
Sun Dec 04 01:08:22 CST 2016     DEBUG     JavaMelody listener init done in 129 ms
Sun Dec 04 01:08:22 CST 2016     DEBUG     JavaMelody filter init started
Sun Dec 04 01:08:22 CST 2016     DEBUG     OS: Linux unknown, amd64/64
Sun Dec 04 01:08:22 CST 2016     DEBUG     Java: Java(TM) SE Runtime Environment, 1.8.0_77-b03
Sun Dec 04 01:08:22 CST 2016     DEBUG     Server: Apache Tomcat/8.0.33
Sun Dec 04 01:08:22 CST 2016     DEBUG     Webapp context: /jirabank
Sun Dec 04 01:08:22 CST 2016     DEBUG     JavaMelody version: 1.62.0
Sun Dec 04 01:08:22 CST 2016     DEBUG     JavaMelody classes loaded from: file:/$$$/$$$$$$$$$/$$$$/$$$$$$$$/WEB-INF/lib/jira-javamelody-1.62.0.jar
Sun Dec 04 01:08:22 CST 2016     DEBUG     Host: lx$$$@$$.$.$$.$$$
Sun Dec 04 01:08:22 CST 2016     DEBUG     parameter defined: storage-directory=/$$$/$$$$$$$$$/$$$$/javamelody
Sun Dec 04 01:08:22 CST 2016     DEBUG     parameter defined: http-transform-pattern=-\d+|/\d+|chment/.+|onent/.+|abel/.+|/x/.+|est/.+|ifact/.+
Sun Dec 04 01:08:22 CST 2016     DEBUG     parameter defined: quartz-default-listener-disabled=true
Sun Dec 04 01:08:22 CST 2016     DEBUG     parameter defined: gzip-compression-disabled=true
Sun Dec 04 01:08:22 CST 2016     DEBUG     parameter defined: system-actions-enabled=true
Sun Dec 04 01:08:22 CST 2016     DEBUG     parameter defined: rewrap-datasources=true
Sun Dec 04 01:08:22 CST 2016     DEBUG     parameter defined: monitoring-path=/secure/admin/monitoring
Sun Dec 04 01:08:22 CST 2016     DEBUG     log listeners initialized
Sun Dec 04 01:08:22 CST 2016     DEBUG     datasources found in JNDI: [java:comp/env/jdbc/JiraDS]
Sun Dec 04 01:08:22 CST 2016     DEBUG     Datasource needs rewrap: java:comp/env/jdbc/JiraDS of class org.apache.tomcat.jdbc.pool.DataSource
Sun Dec 04 01:08:22 CST 2016     INFO     Datasource can't be rewrapped: java:comp/env/jdbc/JiraDS of class org.apache.tomcat.jdbc.pool.DataSource
Sun Dec 04 01:08:22 CST 2016     DEBUG     counters initialized
Sun Dec 04 01:08:23 CST 2016     DEBUG     counters data read from files in /$$$/$$$$$$$$$/$$$$/javamelody/$$$$$$$$_lx$$$
Sun Dec 04 01:08:23 CST 2016     DEBUG     collect task scheduled every 60s
Sun Dec 04 01:08:23 CST 2016     DEBUG     first collect of data done
Sun Dec 04 01:08:23 CST 2016     DEBUG     JavaMelody filter init done in 1377 ms
Sun Dec 04 01:08:23 CST 2016     DEBUG     JavaMelody is monitoring JIRA
Mon Dec 05 00:00:23 CST 2016     DEBUG     Obsolete files deleted. JavaMelody disk usage: 2668 KB

**Comment by mattttttttttt** [comment]
Any news ?

**Comment by evernat** [comment]
I am quite busy at the moment, so I will look at this at a later date.
I will try first to reproduce (or not to reproduce) the issue on a fresh jira install.

**Comment by evernat** [comment]
So you have a jdbc datasource configured in conf/server.xml as documented here:
https://github.com/javamelody/javamelody/wiki/AtlassianPlugin

But I see in your debugging logs above that your datasource is of type `org.apache.tomcat.jdbc.pool.DataSource`.
Why is that?
Do you have added `factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"` for your datasource in conf/server.xml ? (That's not what the javamelody page says.)

If yes, please remove that factory attribute: the datasource does not need a factory to be defined and it should use the default one (DBCP) in order that the jdbc datasource and SQL requests are monitored in JIRA/Confluence/Bamboo.
