### ISSUE TITLE
large gap in all charts in the same period of time

### ISSUE THREAD

**Issue by chuck13** [javamelody/javamelody#590]
log enabled and no error or exception in the log file
<img width="846" alt="ss" src="https://cloud.githubusercontent.com/assets/6442118/20954433/3466197c-bc76-11e6-8df9-0e7c5dc14742.png">

**Comment by evernat** [comment]
For some reason, javamelody was not able to collect data in this period:
- either the application server was down
- or the disk of the storage directory was full
- or the server was blocked saturated by 100% cpu for example

**Comment by chuck13** [comment]
I'm pretty sure it has something to do with the rrd files, cause after I deleted the old files, there was no gap then. However, I found that javamelody generated thousands of files per application, and I had tune up the open files limit to 65535. Thought the total file numbers was larger than that, I don't think that all the files were opened that time, I thought it was OK. Should I be ware of the rrd file numbers?

**Comment by evernat** [comment]
If you have more than 10000 or more than 20000 rrd files, then you probably should use javamelody parameters http-transform-pattern or sql-transform-pattern:
- open the report
- click "Details" for http requests
- click on the request name header to sort by request name
- if you have many requests like /rest/book/123 and /rest/book/456 with digits as dynamic values, then you would better use http-transform-pattern parameter with value \d+ to aggregate those http requests.
And it's the same for sql requests.

See https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
