### ISSUE TITLE
Problem using CustomResourceFilter when non static servlet-mapping uses /*

### ISSUE THREAD

**Issue by pethers** [javamelody/javamelody#597]
Hi,

Thanks for a good project.

Use Vaadin that uses servlet-mapping /* , not ideal but want to keep that behavior and at the same time use a custom montoring.css . 

Only a small change + config needed to get it to work. Need it to use forward instead of include to get it to work, otherwise just some other content is presented at /monitoring?resource=customizableMonitoring.css 

Possible change needed to https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/CustomResourceFilter.java

```
if (customResources.get("useForward") == null ) {
  request.getRequestDispatcher(customResource).include(request, response);
} else {
   request.getRequestDispatcher(customResource).foward(request, response);
}
```

Uses config https://github.com/Hack23/cia/blob/master/citizen-intelligence-agency/src/main/webapp/WEB-INF/web.xml

and created a custom https://github.com/Hack23/cia/blob/master/citizen-intelligence-agency/src/main/java/com/hack23/cia/web/impl/ui/application/web/filter/CustomResourceFilterForward.java that works. But would prefer not to add any custom code.

Trying to get javamelody to look like the rest of the application https://www.hack23.com/cia/ .

Do you think the above change would be useful for somebody else ?

All the best

**Comment by evernat** [comment]
Thanks Pether.
Yes, I think that it would not harm and it can be useful for such case.
Do you want to create a pull request? (Or I can do it of course)

**Comment by pethers** [comment]
Happy to create a pull request, just wanted to check it was ok first.

**Comment by evernat** [comment]
PR #599 merged
