### ISSUE TITLE
Separate port for the UI

### ISSUE THREAD

**Issue by anderius** [javamelody/javamelody#601]
It would be nice if Java Melody could monitor requests on one port, but expose the UI and the collector data on another.

I am using Spring Boot, and would like to use the management port already in use there, if possible,

**Comment by evernat** [comment]
I don't think that it is possible. A webapp can add servlets on the http(s) port, but it can not add servlets on a management port already in use.
So closing this issue.

**Comment by anderius** [comment]
Would it be possible to disable access to the UI in the MonitoringFilter, and somehow invoke MonitoringController from a Spring Controller in the management servlet?  It seems not possible, as it requires the servlet context,,,

**Comment by anderius** [comment]
Just for reference, the following works, and could easily be included in a spring-boot-starter.

```
import net.bull.javamelody.MonitoringFilter;
import net.bull.javamelody.ReportServlet;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.actuate.endpoint.Endpoint;
import org.springframework.boot.actuate.endpoint.mvc.MvcEndpoint;
import org.springframework.boot.web.servlet.FilterRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.bind.annotation.GetMapping;

import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

/**
 * We configure the Java Melody {@link MonitoringFilter} normally, but disables all access to the UI. Instead,
 * we create a {@link ReportServlet}, and expose it through a {@link MvcEndpoint} in {@link #javaMelodyReportEndpoint()}.
 */
@Configuration
public class JavaMelodyConfiguration {

    private final ServletConfig servletConfig;

    @Autowired
    public JavaMelodyConfiguration(ServletConfig servletConfig) {
        this.servletConfig = servletConfig;
    }

    @Bean
    MvcEndpoint javaMelodyReportEndpoint() {
        ReportServlet reportServlet = new ReportServlet();
        // We initialize the servlet with the servlet configuration from the server that runs on server.port, as
        // it currently only uses it to access the Collector instance, and some system information.
        reportServlet.init(servletConfig);

        return new MvcEndpoint() {
            @Override
            public String getPath() {
                return "/monitoring";
            }

            @Override
            public boolean isSensitive() {
                return false;
            }

            @Override
            public Class<? extends Endpoint> getEndpointType() {
                return null;
            }

            @GetMapping
            public void report(HttpServletRequest httpRequest, HttpServletResponse httpResponse) throws ServletException, IOException {
                reportServlet.service(httpRequest, httpResponse);
            }
        };
    }

    @Bean
    FilterRegistrationBean javaMelodyFilterRegistration() {
        FilterRegistrationBean javaMelody = new FilterRegistrationBean();
        javaMelody.setFilter(monitoringFilter());
        javaMelody.setName("javamelody");
        javaMelody.addUrlPatterns("/no-urls-are-allowed-anyway");
        return javaMelody;
    }

    @Bean
    MonitoringFilter monitoringFilter() {
        return new MonitoringFilter() {
            @Override
            protected boolean isAllowed(HttpServletRequest httpRequest, HttpServletResponse httpResponse) throws IOException {
                // We allow no access to the report (/monitoring) from this filter, access is done through the
                // MvcEndpoint above, using the management port.
                return false;
            }
        };
    }
}
```

**Comment by evernat** [comment]
@anderius 
Personnally, I don't know how to bind a MVCEndPoint on an existing "management port", but except that yes the above could work, ...

provided you replace
javaMelody.addUrlPatterns("/no-urls-are-allowed-anyway");
by 
javaMelody.addUrlPatterns("/*");
otherwise it will not monitor any http request.

**Comment by anderius** [comment]
Indeed, thank you for pointing that out! :-)

**Comment by reneberghuis** [comment]
Does anybody know how to do this with Spring Boot 2.0?

**Comment by breneb** [comment]
I found the solution. Instead of declaring a MvcEndpoint bean, do the following:


@Component
@Endpoint(id = "monitoring")
public class JavaMelodyEndpoint {

    private final ReportServlet reportServlet;

    @Autowired
    public JavaMelodyEndpoint(ServletConfig servletConfig) {
        reportServlet = new ReportServlet();
        reportServlet.init(servletConfig);
    }

    @ReadOperation
    public void reportJavaMelody() throws ServletException, IOException {
        final HttpServletRequest httpServletRequest =
                ((ServletRequestAttributes) RequestContextHolder.currentRequestAttributes()).getRequest();
        final HttpServletResponse httpResponse = ((ServletRequestAttributes) RequestContextHolder.currentRequestAttributes()).getResponse();

        reportServlet.service(httpServletRequest, httpResponse);
    }
}

**Comment by evernat** [comment]
6aeb3b1 follows up on 388892d for renaming

**Comment by evernat** [comment]
@anderius @breneb 
I have just understood that a MVCEndpoint is always on the management port, since it is an "actuator endpoint".
Anyway the solution using `@Endpoint` is more in line with Spring boot 2.0 practices and documentation.

I have integrated this solution given a property in the javamelody spring boot starter.
It's committed as 6aeb3b1, and 388892d for renaming, and it's ready for the next release (1.76).
There is a documentation at:
https://github.com/javamelody/javamelody/wiki/SpringBootStarter#configuration-in-case-of-management-port
