### ISSUE TITLE
InstanceNotFoundException

### ISSUE THREAD

**Issue by sandrogiacom** [javamelody/javamelody#603]
When I configured "jboss.platform.mbeanserver" in jboss 4.2.3-GA, the error bellow appears and the JavaMelody don't deploy.

2017-01-13 10:34:09,733 WARN  [net.bull.javamelody] exception while collecting data: java.lang.IllegalStateException: javax.management.InstanceNotFoundException: java.nio:type=BufferPool,name=direct is not registered.
java.lang.IllegalStateException: javax.management.InstanceNotFoundException: java.nio:type=BufferPool,name=direct is not registered.
	at net.bull.javamelody.MemoryInformations.getUsedBufferMemory(MemoryInformations.java:130)

Parameters in run.bat

set JAVA_OPTS=%JAVA_OPTS% -Dcom.sun.management.jmxremote.port=29491 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote
set JAVA_OPTS=%JAVA_OPTS% -Djboss.platform.mbeanserver
set JAVA_OPTS=%JAVA_OPTS% -Djavax.management.builder.initial=org.jboss.system.server.jmx.MBeanServerBuilderImpl
set JAVA_OPTS=%JAVA_OPTS% -XX:+UnlockCommercialFeatures -XX:+FlightRecorder

In Mbean tree, service java.nio:type=BufferPool,name=direct is registered correctly

JavaMelody javamelody-1.62.0.jar and jrobin-1.5.9.jar

Java VM: Java HotSpot(TM) 64-Bit Server VM 24.79-b02,Oracle Corporation
OS-System: Windows 8.1 6.3,amd64

**Comment by evernat** [comment]
Just a question: why do you need to configure "jboss.platform.mbeanserver" ? Does it work without that?
Then jboss 4.2.3-GA is very very old (supporting jboss 4.2.3-GA can't be a priority). So it can be suggested to upgrade jboss.
As a workaround, you may use javamelody 1.56 instead of 1.62.

**Comment by sandrogiacom** [comment]
It is a tecnology limitation for our product. The same situation occurs when starts the datasoruces jndi. In this case, do not throw an exception, just write DEBUG log. My workaround to start whithout exception was change line "throw new IllegalStateException(e);"  to "LOG.warn(e.toString(), e);" With this, I can start the service normally. So far, I did not notice any problems.
