### ISSUE TITLE
MongoDB GridFS file upload fails when using MongoWrapper

### ISSUE THREAD

**Issue by pgifford** [javamelody/javamelody#605]
File uploads fail after wrapping our Mongo database with MongoWrapper.  Using MongoDB Java driver v3.4.1, Javamelody v1.63.0

```java
GridFSBucket bucket = GridFSBuckets.create(wrappedDb, "files");
// fis is a FileInputStream, filename is the non-null, non-empty filename,
// metadata is a Document with a few key-value pairs
ObjectId oid = bucket.uploadFromStream(filename, fis, metadata);
```

Exception is

```
org.bson.BsonInvalidOperationException: Document does not contain key filename
        at org.bson.BsonDocument.throwIfKeyAbsent(BsonDocument.java:844)
        at org.bson.BsonDocument.getString(BsonDocument.java:233)
```

**Comment by evernat** [comment]
Can you give the source of a simple project (using Maven if possible) to reproduce the issue?

**Comment by pgifford** [comment]
Yes, I'll put one together but I won't be able to get to it for a couple of days.

**Comment by evernat** [comment]
It would be good to have the source of a simple project (using Maven if possible) to reproduce the issue.

**Comment by evernat** [comment]
No response from the reporter, so closing as incomplete.
