### ISSUE TITLE
Configuration to hide the warnings in System Errors

### ISSUE THREAD

**Issue by KanagarajGanapathy** [javamelody/javamelody#606]
Dear Team,
Is there any configuration available to remove or hide the warning errors in system errors from javamelody url?

**Comment by evernat** [comment]
You can hide all the system errors, if that's what you want.

For that you have to use the "displayed-counters" parameter. For example, you can add the system property "-Djavamelody.displayed-counters=http,sql,log" depending on which counters you want to see exactly in stats (except the "error" counter in your case).

**Comment by KanagarajGanapathy** [comment]
yes,i understand..But i would like to hide only the warnings in both http and system errors. Is there any possibility to do this? 
thank you for your answers.

**Comment by evernat** [comment]
it's not possible
