### ISSUE TITLE
java.lang.ClassNotFoundException: net.bull.javamelody.SessionListener

### ISSUE THREAD

**Issue by liar666** [javamelody/javamelody#607]
Hi,

I'm new to JavaMelody, but it seems exactly what I was looking for. So, first, thanks for the job!

I've followed the User's Guide, in which I understood that I simply need to put 2 jars in the correct place:
https://github.com/javamelody/javamelody/wiki/UserGuide#1-jar-files
Doing this, I managed to get the monitoring page working.

Since, I don't want this page to be publicly accessible in my production server, I followed the following instructions to setup a password protected access:
https://github.com/javamelody/javamelody/wiki/UserGuide#16-security

Unfortunately, as soon as I add these lines in the `web.xml` file, the logs show:
```
 java.lang.ClassNotFoundException: net.bull.javamelody.MonitoringFilter
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1333)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
  
```

I've checked, the jar files are there and accessible (and by the way, the tool works if I do not add the lines in `web.xml` so the problem should not be there)
$ ls /var/lib/tomcat8/webapps/sofia/WEB-INF/lib/
...
-rw-r--r-- 1 tomcat8 tomcat8 1.1M Jan 24 10:37 javamelody-1.63.0.jar
-rw-r--r-- 1 tomcat8 tomcat8 770K Jan 24 10:39 jrobin-1.5.9.jar
...

I've also googled a lot this problem but I couldn't find anything relevant...

Any idea what I do wrong?

**Comment by evernat** [comment]
It's like Tomcat does not find the javamelody jar files anymore.
You should copy here what security you have added to web.xml, so that we can have a look.

**Comment by liar666** [comment]
Hi again,

Thanks for the quick response. 

I'm using the stock web.xml file, to which I've simply added:

```
    <filter>
      <filter-name>monitoring</filter-name>
      <filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
      <async-supported>true</async-supported>
      <init-param>
        <param-name>authorized-users</param-name>
        <param-value>mymonitoringpage:mypassword</param-value>
      </init-param>
    </filter>
    <filter-mapping>
      <filter-name>monitoring</filter-name>
      <url-pattern>/*</url-pattern>
      <dispatcher>REQUEST</dispatcher>
      <dispatcher>ASYNC</dispatcher>
    </filter-mapping>
    <!-- Class not found problem occurrs here if I uncomment the following lines
    <listener>
      <listener-class>net.bull.javamelody.SessionListener</listener-class>
    </listener>
    -->
```

**Comment by evernat** [comment]
Ok, this is a standard web.xml with init-param and it should work with SessionListener.
Are you able to create a simple webapp to reproduce the issue?

**Comment by evernat** [comment]
any news?

**Comment by liar666** [comment]
Sorry for the delays in my answer, 

I tried to make a simple HelloWorld JSP, but couldn't make it work with javamelody either :{

I'm quite overbooked since 2 weeks ago, so I can't investigate more for the moment, sorry... I hope to be able to do so in a few months.

**Comment by jiacheng-0** [comment]
Any news on this? @liar666 @evernat I am facing the same issue with Java 17 Tomcat 10

**Comment by idamerce** [comment]
@jiacheng-0 did you find a solution I'm facing same error spring boot 3.2.5, java 21 and tomcat 10

**Comment by jiacheng-0** [comment]
> @jiacheng-0 did you find a solution I'm facing same error spring boot 3.2.5, java 21 and tomcat 10

@idamerce Hey there, I did updated java-melody-core to 2.1 and jakarta.persistence-api to 3.0.0 and it resolved the errors. Ideally what you want to do as best practice is to use spring-boot-starter-data-jpa artifact going forward as it comes with the mentioned libraries all tested for compatibility. 

Cheers, hope this helps!
