### ISSUE TITLE
CounterResponseStream returns empty responses

### ISSUE THREAD

**Issue by rippi** [javamelody/javamelody#614]
`net.bull.javamelody.CounterResponseStream` seems only to work properly with `java.io.OutputStream.write(byte[] b, int off, int len)`. 

If it is used in combination with `javax.xml.stream.XMLStreamWriter` or `javax.xml.transform.stream.StreamResult` & `javax.xml.transform.Transformer` the response is always empty. 
This behavior was observed on Jetty 8.1.12.v20130726 and with following javamelody versions: 1.59.0, 1.63.0

**Comment by evernat** [comment]
> net.bull.javamelody.CounterResponseStream seems only to work properly with java.io.OutputStream.write(byte[] b, int off, int len)

Why do you say that?

And can you give the source of a simple project (using maven if possible) to reproduce the issue?

**Comment by evernat** [comment]
I have not reproduced the issue, after testing using Jetty 8.1.14.v20131031, JDK 1.8 and the following servlet:
public class TestServlet extends HttpServlet {
	public void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		System.out.println(request.getQueryString());
		XMLStreamWriter xmlWriter = null;
		XMLOutputFactory factory = XMLOutputFactory.newInstance();
		ServletOutputStream outputStream = response.getOutputStream();
		response.setCharacterEncoding("UTF-8");
		response.setContentType("text/xml");
		try {
			xmlWriter = factory.createXMLStreamWriter(outputStream);
			xmlWriter.writeStartDocument();
			xmlWriter.writeStartElement("test");
			xmlWriter.writeEndElement();
			xmlWriter.writeEndDocument();
		} catch (XMLStreamException e) {
			e.printStackTrace();
		} finally {
			try {
				if (xmlWriter != null) {
					xmlWriter.flush();
					xmlWriter.close();
				}
			} catch (XMLStreamException e) {
				e.printStackTrace();
			}
		}
	}
}

Can you give the source of a simple project (using maven if possible) to reproduce the issue?

**Comment by rippi** [comment]
I was using JDK 1.7 and an older version of Jetty as stated above.
Your TestServlet does the same as mine. I will try and use a higher version of Jetty since I can't use Java 8 with GWT and hope it will work.
Thanks for your help anyways.
