### ISSUE TITLE
Charts of Statistics http/sql etc, can not be viewed after restarting the application

### ISSUE THREAD

**Issue by goldyliang** [javamelody/javamelody#617]
The charts under each http/sql request entry can be viewed normally. However if the application is restarted, the charts can not be seen anymore, unless there are several requests coming and 're-activate' the charts.

After some reading of the code, I have found the source of the issue and changed the code to make it work. 

The problem is in  Collector.getJRobin.  After restarting, the http/sql graphs are not added into any of the JRobin collections so getJRobin return null even the RRD file really exists. My quick fix is to create a temporary JRobin object and return that if no JRobin object is found in the collections.

I will send a PR soon for this change.

**Comment by evernat** [comment]
Fixed and pushed to master (e5df3b1). Thanks
