### ISSUE TITLE
spring mybatis jdbc  how to setting

### ISSUE THREAD

**Issue by 123987asd** [javamelody/javamelody#619]

**Comment by evernat** [comment]
I recommend to define a datasource and to use `net/bull/javamelody/monitoring-spring.xml` as said in https://github.com/javamelody/javamelody/wiki/UserGuide#7-jdbc

**Comment by 123987asd** [comment]
I read that,I hava a problem  if  filename must be called monitoring-spring.xml or monitoring-spring-datasource.xml ？

**Comment by evernat** [comment]
You should use monitoring-spring.xml in general.
Or if you have errors with monitoring-spring.xml, you can use monitoring-spring-datasource.xml in your specific case.

**Comment by 123987asd** [comment]
Thank you for your prompt reply.but I define the dataSource in my spring-config.xml.
 As shown below 
	<bean id="dataSource" class="" destroy-method="close">
		<property name="driverClassName" value="${jdbc.driverClassName}" />
		<property name="url" value="${jdbc.url}" />
		<property name="username" value="${jdbc.username}" />
		<property name="password" value="${jdbc.password}" />
		<property name="minIdle" value="${jdbc.minIdle}" />        
		<property name="maxIdle" value="${jdbc.maxIdle}" />       
		<property name="maxWait" value="${jdbc.maxWait}" />      
		<property name="maxActive" value="${jdbc.maxActive}" /> 
		<property name="initialSize" value="${jdbc.initialSize}" />
		<property name="testWhileIdle" value="${jdbc.testWhileIdle}" />
		<property name="validationQuery" value="${jdbc.validationQuery}" />
	</bean>
	
  	<bean id="transactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
    	<property name="dataSource" ref="dataSource"></property>
  	</bean>
  	<tx:annotation-driven transaction-manager="transactionManager" proxy-target-class="true"/>

	<bean id="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
		<property name="dataSource" ref="dataSource" />
  		<property name="configLocation" value="classpath:mybatis.xml" >
  		</property> 
	</bean>
I use ORM is mybatis. Can you send me an example

**Comment by evernat** [comment]
ok, there is no problem.
I suppose that in your web.xml, you have something like
```xml
<context-param>
	<param-name>contextConfigLocation</param-name>
	<param-value>
	/WEB-INF/spring-config.xml
	</param-value>
</context-param>
```

so replace it with the following:
```xml
<context-param>
	<param-name>contextConfigLocation</param-name>
	<param-value>
	classpath:net/bull/javamelody/monitoring-spring.xml
	/WEB-INF/spring-config.xml
	</param-value>
</context-param>
```

If there are errors, you can use the following:

```xml
<context-param>
	<param-name>contextConfigLocation</param-name>
	<param-value>
	classpath:net/bull/javamelody/monitoring-spring-datasource.xml
	/WEB-INF/spring-config.xml
	</param-value>
</context-param>
```

**Comment by 123987asd** [comment]
My spring - config. XML and web. XML is not in the same project.Using the server and consumer patterns.

**Comment by evernat** [comment]
Then I suggest to add `<import resource="classpath:net/bull/javamelody/monitoring-spring.xml" />` in your spring-config.xml

**Comment by 123987asd** [comment]
I try it,but no effect.my web.xml in a project,and my spring-config.xml in the other project,I define the dataSource in my spring-config.xml.
