### ISSUE TITLE
Invalid package for javamelody-spring-boot-starter

### ISSUE THREAD

**Issue by moleksyuk** [javamelody/javamelody#620]
Hi,

I've just tried to configure javamelody for spring-boot application but couldn't because both published versions to Maven Central are invalid.
Neither `javamelody-spring-boot-starter:1.64.0` nor `javamelody-spring-boot-starter:1.65.0` contains binary files. They contains only documentation.
![screen shot 2017-03-24 at 17 55 11](https://cloud.githubusercontent.com/assets/793472/24302531/a1cc1b08-10bb-11e7-8ad3-a199579e0e2f.png)

**Comment by evernat** [comment]
Indeed. I will try to fix that.

**Comment by evernat** [comment]
It is better now:
https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22javamelody-spring-boot-starter%22
But you must upgrade to 1.65.1:
```xml
<dependency>
	<groupId>net.bull.javamelody</groupId>
	<artifactId>javamelody-spring-boot-starter</artifactId>
	<version>1.65.1</version>
</dependency>
```
Thanks for the issue.
