### ISSUE TITLE
the monitoring prompt : 1.63.0 instead of 1.65.0

### ISSUE THREAD

**Issue by jueduizone** [javamelody/javamelody#621]
in the web interface of monitoring, it prompt me：
` A new version of JavaMelody is available (1.63.0 instead of 1.65.0, see Release Notes)`
my pom.xm configuration:
```
<dependency>
	<groupId>net.bull.javamelody</groupId>
	<artifactId>javamelody-core</artifactId>
	<version>1.65.0</version>
</dependency>
```
what's wrong ?（the 1.63.0 is newest？my English is poor，sorry~）

**Comment by evernat** [comment]
Sorry about that. I have understood my mistake.
The message should disappear after the next restart of your server.
