### ISSUE TITLE
Javamelody Collector. Malformed main html page when server is down.

### ISSUE THREAD

**Issue by max-selivanov** [javamelody/javamelody#622]
`HtmlSourceReport` class has a method `htmlEncodeStackTraceElement(...)`, which generates non escaped html string `<a href='?part= ... </a>`. Then this string is used in application link. So in a result we have:
`<a class="tooltip" href="?application=app-name">...<a href='?part= ... </a>....</a>`
Html element `<a>` can't contain inner `<a>`.

**Comment by evernat** [comment]
It's fixed by 56a6e85 in master.
I have uploaded a new build including the fix at :
https://github.com/javamelody/javamelody/releases/download/javamelody-core-1.65.0/javamelody-collector-server-1.65.1.war

Thanks for the issue !
