### ISSUE TITLE
Where does javamelody store its statistical data?

### ISSUE THREAD

**Issue by chrisco484** [javamelody/javamelody#625]
This is more or a question than an issue.

The guides mention that no database is used to store data which is why it is very lightweight but where are the statistics persisted?

Presumably the stats are not just maintained in memory or they would be all lost each time we restarted the servlet container wouldn't they?

**Comment by chrisco484** [comment]
Reposted to the google user group instead.

**Comment by evernat** [comment]
indeed: https://groups.google.com/forum/#!topic/javamelody/JtWqeUqqzrI
