### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by Volong** [javamelody/javamelody#626]
Windows 7 is works better, but in Centos 6 has encoding issue. Picture can not display Chinese.

I found is the font problem, but I don't know how to resolve it.

![20170428142057](https://cloud.githubusercontent.com/assets/9137053/25516623/36670fb6-2c1e-11e7-9114-59128d82f9cd.png)

**Comment by evernat** [comment]
If you use OpenJDK on that server, you may try to use OracleJDK instead.

Or it may be a font configuration issue on the server, you can try to add DejaVuSansMono.ttf or DejaVuSans-Bold.ttf in your server and to setup a fonts.conf alias in your server:
```xml
        <match target="pattern">
                <test qual="any" name="family">
                        <string>mono</string>
                </test>
                <edit name="family" mode="assign">
                        <string>monospace</string>
                </edit>
        </match>
```
(like for #144)

But the simpler would be to change locale of javamelody to English, for example by adding in your web.xml:
```xml
<context-param>
    <param-name>javamelody.locale</param-name>
    <param-value>en</param-value>
</context-param>
```

**Comment by Volong** [comment]
Thank you for the reply. 
I did as you said. But still can not show Chinese.

**Comment by evernat** [comment]
I can't debug the issue with Chinese fonts in your CentOS 6.
I suggest to change the to change locale of javamelody to English, for example by adding in your web.xml:
```xml
<context-param>
    <param-name>javamelody.locale</param-name>
    <param-value>en</param-value>
</context-param>
```

**Comment by Volong** [comment]
I solved the problem in this way in my CentOS .

`yum groupinstall chinese-support`

Thank you for your help.

**Comment by evernat** [comment]
@Volong 
Good to know. Thanks for the information.

**Comment by Beanking77** [comment]
Where can I find the web.xml file in CentOS 7.2 ? 
or create with
```
<?xml version="1.0" encoding="UTF-8" ?>
<context-param>
    <param-name>javamelody.locale</param-name>
    <param-value>en</param-value>
</context-param>
```
and put this file at somewhere and restart jenkins service?

**Comment by evernat** [comment]
@Beanking77 
The web.xml file as you have given is not valid and can't be used as is.
Anyway, adding some part in a web.xml file is supposed to be done by a developer of the webapp. And I suppose that you are not a developer of Jenkins.

So for Jenkins, I suggest to add a system property with the same result instead of adding some param in web.xml. Depending on your installation, you can add `-Djavamelody.locale=en` in jenkins_directory/jenkins.xml or in /etc/sysconfig/jenkins (variable JENKINS_JAVA_OPTIONS) or in /etc/default/jenkins (variable JAVA_ARGS).

**Comment by Beanking77** [comment]
@evernat Thanks for your reply. I'll try this.
