### ISSUE TITLE
Viewing CPU hotspots

### ISSUE THREAD

**Issue by okohll** [javamelody/javamelody#627]
Hi, I'm sure this is something very basic I've missed but I can't see the CPU hotspots report.

My config. in web.xml is below but searching for 'hotspot' on the main screen doesn't find anything. I can't see anything in any of the links below the charts.

	  <filter>
            <filter-name>monitoring</filter-name>
            <filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
            <init-param>
                <param-name>storage-directory</param-name>
                <param-value>/var/local/javamelody</param-value>
                <param-name>sampling-seconds</param-name>
                <param-value>10</param-value>
                <param-name>sampling-included-packages</param-name>
                <param-value>com.gtwm.pb</param-value>
                <param-name>authorized-users</param-name>
                <param-value>[myusername]:[mypassword]</param-value>
            </init-param>
    </filter>

**Comment by evernat** [comment]
I suppose that you are speaking about the hotspots like in the demo:
http://javamelody.org/demo/monitoring?part=hotspots

These hotspots need to be enabled. See https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#enable-hotspots-detection

For example:
```xml
<filter>
        <filter-name>monitoring</filter-name>
        <filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
        <init-param>
            <param-name>storage-directory</param-name>
            <param-value>/var/local/javamelody</param-value>
        </init-param>
        <init-param>
            <param-name>sampling-seconds</param-name>
            <param-value>10</param-value>
        </init-param>
        <init-param>
            <param-name>sampling-included-packages</param-name>
            <param-value>com.gtwm.pb</param-value>
        </init-param>
        <init-param>
            <param-name>authorized-users</param-name>
            <param-value>[myusername]:[mypassword]</param-value>
        </init-param>
</filter>
...
```
Note that `<init-param>...</init-param>` are each one independent.
You may use 1 or 0.1 for `sampling-seconds` to have some data without waiting for an hour of real usage.

**Comment by okohll** [comment]
Great, thanks
