### ISSUE TITLE
xstream serialization issue.

### ISSUE THREAD

**Issue by mmosemmle** [javamelody/javamelody#631]
There are two instances of 'Deserialization of user-controlled data' in javamelody:
https://lgtm.com/projects/g/javamelody/javamelody/alerts/
on lgtm.com
The second one is called in MyObjectInputStream, which implements lookahead class validation, but the first one that uses xstream did not secure the xstream use for deserialization. Since both cases are used in the same context, it is likely that the xstream one also needs to be secured. This can be fixed by following the methods here:
http://x-stream.github.io/security.html
Hope this is the right way to report the issue. Thanks.

**Comment by evernat** [comment]
The concerned method would be executed in the collector server when there is one, but it is not used in practice.
So it's not really an issue.
But I have fixed it anyway so that there is no worry (dd8816863d8d943f819a3fa797c349236e7546d4).

**Comment by evernat** [comment]
By the way, you would better contact the authors in private for other supposed security issues (evernat at free.fr here).

**Comment by mmosemmle** [comment]
Thanks for the prompt action! Sorry about this and I will contact you privately if I see any other security issues. Thanks!
