### ISSUE TITLE
Configuration ignored in Spring Boot application deployed to Tomcat

### ISSUE THREAD

**Issue by Saberos** [javamelody/javamelody#632]
Recently I tried to modify some of the JavaMelody configuration for our applications deployed to Tomcat (enabling JMX_EXPOSE_ENABLED). Everything worked fine locally, starting the Spring Boot application with the embedded Tomcat server the mbean is available. Deploying it to a Tomcat server however, the mbean was not created. Debugging the application shows two MonitoringFilters are created when deployed to Tomcat, the one in our configuration, but also another one:

![javamelody](https://cloud.githubusercontent.com/assets/2879186/26113860/08b8f8ee-3a5c-11e7-9cd9-2b9a2c880541.png)

It appears the second one overrules the configuration set in the Spring JavaMelodyConfiguration class.

JavaMelody is set up in our applications using the information listed here (without the starter):
https://github.com/javamelody/javamelody/wiki/SpringBootStarter#or-integration-without-the-spring-boot-starter

Here's an example project that reproduces the problem for me. Starting the application using `mvn spring-boot:run`, when visiting http://localhost:8080/monitoring?part=mbeans, a net.bull.javamelody mbean is created. However, creating a war using `mvn package,` and deploying this to a Tomcat server (I used 8.5.15), the same mbean is missing.

[javamelody-example.zip](https://github.com/javamelody/javamelody/files/1004973/javamelody-example.zip)

**Comment by evernat** [comment]
You use a JavaMelodyConfiguration class (without the starter) like this:
```java
@Configuration
public class JavaMelodyConfiguration implements ServletContextInitializer {
	@Override
	public void onStartup(ServletContext servletContext) throws ServletException {
		servletContext.addListener(new SessionListener());
	}

	@Bean
	public FilterRegistrationBean javaMelody(ServletContext servletContext) {
		final FilterRegistrationBean javaMelody = new FilterRegistrationBean();
		final MonitoringFilter filter = new MonitoringFilter();
		filter.setApplicationType("Spring Boot");
		javaMelody.setFilter(filter);
		javaMelody.setAsyncSupported(true);
		javaMelody.setName("javamelody");
		javaMelody.setDispatcherTypes(DispatcherType.REQUEST, DispatcherType.ASYNC);

		// see the list of parameters:
		// https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
		javaMelody.addInitParameter(Parameter.LOG.getCode(), Boolean.toString(true));
		javaMelody.addInitParameter(Parameter.JMX_EXPOSE_ENABLED.getCode(), Boolean.toString(true));

		javaMelody.addUrlPatterns("/*");

		return javaMelody;
	}
   ...
}
```

I suggest to change it like the following, to fix this issue when you deploy the webapp as a war in a container:
```java
@Configuration
public class JavaMelodyConfiguration implements ServletContextInitializer {
	@Override
	public void onStartup(ServletContext servletContext) throws ServletException {
		// if webapp deployed as war in a container with MonitoringFilter and SessionListener already added by web-fragment.xml,
		// do not add again
		if (servletContext.getFilterRegistration("javamelody") == null) {
			servletContext.addListener(new SessionListener());
		}
	}

	@Bean
	public FilterRegistrationBean javaMelody(ServletContext servletContext) {
		final FilterRegistrationBean javaMelody = new FilterRegistrationBean();
		final MonitoringFilter filter = new MonitoringFilter();
		filter.setApplicationType("Spring Boot");
		javaMelody.setFilter(filter);
		javaMelody.setAsyncSupported(true);
		javaMelody.setName("javamelody");
		javaMelody.setDispatcherTypes(DispatcherType.REQUEST, DispatcherType.ASYNC);

		// see the list of parameters:
		// https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
		javaMelody.addInitParameter(Parameter.LOG.getCode(), Boolean.toString(true));
		javaMelody.addInitParameter(Parameter.JMX_EXPOSE_ENABLED.getCode(), Boolean.toString(true));

		javaMelody.addUrlPatterns("/*");

		final FilterRegistration filterRegistration = servletContext.getFilterRegistration("javamelody");
		if (filterRegistration != null) {
			// if webapp deployed as war in a container with MonitoringFilter already added by web-fragment.xml,
			// do not try to add it again
			javaMelody.setEnabled(false);
			for (final Map.Entry<String, String> entry : javaMelody.getInitParameters().entrySet()) {
				filterRegistration.setInitParameter(entry.getKey(), entry.getValue());
			}
		}
		return javaMelody;
	}
   ...
}
```

The trick is to detect when the war and the web-fragment.xml are already initialized by the container and to do as needed and without losing your configuration.

If you can confirm if it works for you, it would be great. Thanks.

**Comment by Saberos** [comment]
Thanks for the quick reply, that does indeed solve my issue. 
Thank you!
