### ISSUE TITLE
Install JAR plugin 1.6.7 on Confluence 6.2.3 freezes / fails

### ISSUE THREAD

**Issue by stevemccann** [javamelody/javamelody#641]
I just uploaded and installed jira-confluence-javamelody-1.67.0.jar on two Confluence 5.10.0 systems without issue. When I upload the plugin to a newly-upgraded Confluence 6.2.3 system, the plugin install stays frozen at the Installing... screen.

I've checked the server logs and I can't see any errors. 

pic of stuck window when uploading the JAR:
![image](https://user-images.githubusercontent.com/6005220/27517025-8dc6282c-5992-11e7-978c-977cdaf5e4ec.png)

When I paste the link to the JAR from URL, the upload completes, but I get this error:
![image](https://user-images.githubusercontent.com/6005220/27517115-a2a36cee-5994-11e7-939e-31ff1fcc0f9e.png)

The error in atlassian-confluence.log is attached:

[atlassian-confluence.log.txt](https://github.com/javamelody/javamelody/files/1100395/atlassian-confluence.log.txt)

Here's the top part of that file which may highlight the issue:
`
2017-06-25 14:45:23,473 ERROR [UpmAsynchronousTaskManager:thread-4] [atlassian.plugin.loaders.ScanningPluginLoader] deployPluginFromUnit Unable to deploy plugin 'null' from 'Unit: /var/atlassian/application-data/confluence/plugins-cache/1498401923189plugin.4684515388431968039.601bf2f8-375f-11e7-84f4-71d5497be0b3 (1498401923000)'.

 -- url: /rest/plugins/1.0/ | referer: https://staging.wiki.site/plugins/servlet/upm | traceId: 79a9e0c00faaa99f | userName: username

2017-06-25 14:45:23,474 ERROR [UpmAsynchronousTaskManager:thread-4] [atlassian.plugin.loaders.ScanningPluginLoader] deployPluginFromUnit Because of the following exception:

 -- url: /rest/plugins/1.0/ | referer: https://staging.wiki.site/plugins/servlet/upm | traceId: 79a9e0c00faaa99f | userName: username

java.lang.IllegalArgumentException: The artifact URI file:/var/atlassian/application-data/confluence/plugins-cache/1498401923189plugin.4684515388431968039.601bf2f8-375f-11e7-84f4-71d5497be0b3 is not a valid plugin artifact
`

**Comment by stevemccann** [comment]
I upgraded a Confluence install from 5.10.0 to 6.2.3 that had JavaMelody 1.6.7 installed, and it still works. It appears this is just affecting new installs.

**Comment by evernat** [comment]
I have installed JavaMelody 1.67.0 on a fresh Confluence 6.2.3.
And I do not reproduce the issue.
Do you know by any chance how to reproduce the issue step by step?

**Comment by stevemccann** [comment]
The environment was an existing system upgrade from 5.10.0 to 6.2.3. I'll see if I can re-create from scratch.

I still have the environment up. I can see if it fails with uploading other plugins. It may be a problem with UPM.

**Comment by evernat** [comment]
Any news?

**Comment by evernat** [comment]
No response from the reporter, so closing as incomplete.
