### ISSUE TITLE
seems after refactoring/moving to another package Quartz2Adapter not found anymore

### ISSUE THREAD

**Issue by cyburglar** [javamelody/javamelody#645]
In 1.68.0 release when use Quartz2 in QuartzAdapter singleton throws exeption 
`Caused by: java.lang.IllegalStateException: java.lang.ClassNotFoundException: net.bull.javamelody.Quartz2Adapter
	at net.bull.javamelody.internal.model.QuartzAdapter.createSingleton(QuartzAdapter.java:71)
	at net.bull.javamelody.internal.model.QuartzAdapter.<clinit>(QuartzAdapter.java:46)`

in line 68 should be 
`				return (QuartzAdapter) Class.forName("net.bull.javamelody.internal.model.Quartz2Adapter")
						.newInstance();
`

Patch 
` .../src/main/java/net/bull/javamelody/internal/model/QuartzAdapter.java | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/javamelody-core/src/main/java/net/bull/javamelody/internal/model/QuartzAdapter.java b/javamelody-core/src/main/java/net/bull/javamelody/internal/model/QuartzAdapter.java
index 96451c8c..992c7c25 100644
--- a/javamelody-core/src/main/java/net/bull/javamelody/internal/model/QuartzAdapter.java
+++ b/javamelody-core/src/main/java/net/bull/javamelody/internal/model/QuartzAdapter.java
@@ -65,7 +65,7 @@ public class QuartzAdapter {
 	private static QuartzAdapter createSingleton() {
 		if (QUARTZ_2) {
 			try {
-				return (QuartzAdapter) Class.forName("net.bull.javamelody.Quartz2Adapter")
+				return (QuartzAdapter) Class.forName("net.bull.javamelody.internal.model.Quartz2Adapter")
 						.newInstance();
 			} catch (final Exception e) {
 				throw new IllegalStateException(e);
`

**Comment by enayet-repo** [comment]
I was having the same issue. This solved. Thanks..

**Comment by evernat** [comment]
Thanks for the patch, it's fixed in master by 6ba0cab.
