### ISSUE TITLE
Can javamelody monitor machine's network latency?

### ISSUE THREAD

**Issue by h920526** [javamelody/javamelody#647]
Hi team:

Is it possible to monitor machine's network latency via curl a http request or a ping command by javamelody?

**Comment by evernat** [comment]
It's not possible to monitor network latency like this, but since 1.67 Real User Monitoring (RUM) is available. It displays average network time between the browser and the server. See doc:
https://github.com/javamelody/javamelody/wiki/UserGuide#18-real-user-monitoring
