### ISSUE TITLE
I have a question that why the unit of measurement of JDBC connection counts in the graphic is "m"?

### ISSUE THREAD

**Issue by 314537485** [javamelody/javamelody#650]
I have a question that why the unit of measurement of JDBC connection counts in the graphic  is "m"?
and http sessions?
Look at the picture below!

![issue](https://user-images.githubusercontent.com/18656793/28454963-b4388e12-6e2f-11e7-88fe-6f7d19a77838.png)

thanks !

**Comment by 314537485** [comment]
i use javamelody version:
 javamelody-collector-server-1.68.0.war,jrobin-1.5.9.1.jar,javamelody-core-1.68.1.jar
tomcat version: apache-tomcat-6.0.43
and i integration in springMVC3.2.2 hibernate3.3.1 with jsp view

**Comment by evernat** [comment]
The units of the graphs are automatically chosen based on values.
And the units are "m" for milli (1 / 1000), "k" for kilo/thousands, "M" for mega/millions, "G" for giga/billions and "u" for micro (1 / 1000000).
For example, 7 m for the mean of connection counts means 0.007.

**Comment by 314537485** [comment]
okey thanks very much !
