### ISSUE TITLE
how to deal this 

### ISSUE THREAD

**Issue by tianxia007** [javamelody/javamelody#651]
in my project i hava add:
 <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>

i use : 1.5.2.RELEASE  security and so on.

but also show :
Description:

The bean 'userService' could not be injected as a 'cn.service.UserService' because it is a JDK dynamic proxy that implements:

Action:

Consider injecting the bean as one of its interfaces or forcing the use of CGLib-based proxies by setting proxyTargetClass=true on @EnableAsync and/or @EnableCaching.

thanks!

**Comment by 314537485** [comment]
兄台 看描述你应该是在web.xml 中，context-param 标签中用monitoring-spring.xml了吧，因为如果你用了spring aop 控制事务，那么在监控sql的时候配置这个东西报错了吗？如果是这样，请用monitoring-spring-datasource.xml  替换monitoring-spring.xml ，例如下面的例子：
    <context-param>
        <param-name>contextConfigLocation</param-name>
        <param-value>
        classpath*:spring_service.xml
        _classpath:net/bull/javamelody/monitoring-spring-datasource.xml_
        </param-value>
    </context-param>

**Comment by tianxia007** [comment]
@314537485 哈哈   我这蹩脚的英语我怕没人看懂呢
我用的pybbs spring boot版本，集成javameloady：
地址：https://github.com/tomoya92/pybbs

所以没有各种xml文件的。

**Comment by 314537485** [comment]
哦 这样啊 那我还真不清楚了 我之前遇到的是监控sql的时候在web.xml里用monitoring-spring-datasource.xml替换掉另一个就可以了，这个在维基文档中有介绍，等作者或者高手来解决吧（waiting for the author or others to solve it）,因为一看你的名字就应该是Chinese people ，还有温馨提示那个i haha 应该是 i have。

**Comment by tianxia007** [comment]
IT is ok！
use:
 <dependency>
            <groupId>net.bull.javamelody</groupId>
            <artifactId>javamelody-core</artifactId>
            <version>1.68.1</version>
        </dependency>
