### ISSUE TITLE
JavaMelody is not sending the periodic mail and test mail failed with error for Atlassian Confluence

### ISSUE THREAD

**Issue by suyashjain** [javamelody/javamelody#652]
Hi,

I am using Java Melody plugin for atlassian Confluence 6.2.3 and it is working perfectly in generating the reports and other things. But it is unable to send report and throwing errors on test mail.

The error file is attached with issue.
I am adding the following lines in server.xml context section

        <Resource name="mail/MySession" auth="Container" type="javax.mail.Session"
                    mail.smtp.host="localhost"
                    mail.smtp.auth="false"
                    mail.from="no-reply@appfire.com"
                />
    <Parameter name='javamelody.admin-emails' value='bizsys@appfire.com' override='false'/>
    <Parameter name='javamelody.mail-session' value='mail/MySession' override='false'/>
    <Parameter name='javamelody.mail-periods' value='day,week,month' override='false'/>
[java-melody-mail-error.txt](https://github.com/javamelody/javamelody/files/1175952/java-melody-mail-error.txt)

**Comment by evernat** [comment]
issue already created at:
https://github.com/javamelody/jira-confluence-javamelody/issues/1
