### ISSUE TITLE
Problem with datasources param-name and jndi datasources, only sql data in one report

### ISSUE THREAD

**Issue by pethers** [javamelody/javamelody#658]
Have a few different ear files deployed under wildfly8, want separate javamelody reports for each application

For each application I have specified
--
                <init-param>
			<param-name>storage-directory</param-name>
			<param-value>javamelody-asset</param-value>
		</init-param>
		<init-param>
			<param-name>datasources</param-name>
			<param-value>java:/jdbc/DS_APP_NAME</param-value>
		</init-param>
--

[movement_monitoring.pdf](https://github.com/javamelody/javamelody/files/1197056/movement_monitoring.pdf)
[mobileterminal_monitoring.pdf](https://github.com/javamelody/javamelody/files/1197057/mobileterminal_monitoring.pdf)
[asset_monitoring.pdf](https://github.com/javamelody/javamelody/files/1197058/asset_monitoring.pdf)

The problem is that only one of the javamelody contain all sql data and the other reports are empty.
The mobileterminal_monitoring.pdf , contain sql data but others do not.

Happy to help out with a pull request, looks like https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/JdbcWrapperHelper.java might need to be changed. But not sure.

Javamelody config, examples

https://github.com/UnionVMS/UVMS-AssetModule-APP/blob/dev/rest/src/main/webapp/WEB-INF/web.xml
https://github.com/UnionVMS/UVMS-MovementModule-APP/blob/dev/rest/src/main/webapp/WEB-INF/web.xml
https://github.com/UnionVMS/UVMS-MobileterminalModule-APP/blob/dev/rest/src/main/webapp/WEB-INF/web.xml

**Comment by evernat** [comment]
Hi Pether,
First, I ask myself if it is on purpose that you don't have added net.bull.javamelody.SessionListener in web.xml of AssetModule:
https://github.com/UnionVMS/UVMS-AssetModule-APP/blob/dev/rest/src/main/webapp/WEB-INF/web.xml

**Comment by evernat** [comment]
Can you give the debugging logs at the bottom of the monitoring page of the mobileterminal webapp?
And does it change something if you add in the web.xml files a context-param instead of an init-param in the filter?
```xml
<context-param>
 	<param-name>javamelody.datasources</param-name>
 	<param-value>java:/jdbc/DS_APP_NAME</param-value>
</context-param>
```

I think that the first init done by the SessionListener of the mobileterminal may ignore the `datasources` param in the filter and so may initialize the monitoring of all your datasources.
To fix that, it would be needed in JdbcWrapper.rebindDataSources() to unwrap the previously wrapped datasources when the datasources parameter is defined, before rewrapping the ones listed in the `datasources` param.
I have done a part of a fix, but it will not change anything in your case with WildFly: see b06f34f

**Comment by pethers** [comment]
Thanks for the quick  response,  always appreciated.

Probably just forgot the SessionListener, so will add it and also try using a context-param as well.

Will update this issue, with the debug log on early next week and also look at the JdbcWrapper.rebindDataSources().

**Comment by pethers** [comment]
Tested to add context-param and sessionlistener, still using 1.65.0. But will test with latest snapshot tomorrow.

Get the same debug in all the application

Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource needs rewrap: java:/jdbc/uvms_movement of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource rewrapped: java:/jdbc/uvms_movement
Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource needs rewrap: java:/jdbc/uvms_rules of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource rewrapped: java:/jdbc/uvms_rules
Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource needs rewrap: jdbc/USM2 of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource rewrapped: jdbc/USM2
Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource needs rewrap: jdbc/uvms_asset of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource rewrapped: jdbc/uvms_asset
Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource needs rewrap: jdbc/uvms_audit of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource rewrapped: jdbc/uvms_audit
Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource needs rewrap: jdbc/uvms_config of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource rewrapped: jdbc/uvms_config
Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource needs rewrap: jdbc/uvms_exchange of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource rewrapped: jdbc/uvms_exchange
Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource needs rewrap: jdbc/uvms_mobterm of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource rewrapped: jdbc/uvms_mobterm
Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource needs rewrap: jdbc/uvms_movement of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource rewrapped: jdbc/uvms_movement
Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource needs rewrap: jdbc/uvms_rules of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:09:54 UTC 2017     DEBUG     Datasource rewrapped: jdbc/uvms_rules
Thu Aug 10 16:09:54 UTC 2017     DEBUG     JavaMelody listener init done in 30 ms
Thu Aug 10 16:10:40 UTC 2017     DEBUG     JavaMelody filter init started
Thu Aug 10 16:10:40 UTC 2017     DEBUG     OS: Linux unknown, amd64/64
Thu Aug 10 16:10:40 UTC 2017     DEBUG     Java: OpenJDK Runtime Environment, 1.7.0_141-mockbuild_2017_05_09_15_35-b00
Thu Aug 10 16:10:40 UTC 2017     DEBUG     Server: WildFly 8.2.0.Final - 1.1.0.Final
Thu Aug 10 16:10:40 UTC 2017     DEBUG     Webapp context: /asset
Thu Aug 10 16:10:40 UTC 2017     DEBUG     JavaMelody version: 1.65.0
Thu Aug 10 16:10:40 UTC 2017     DEBUG     JavaMelody classes loaded from: vfs:/content/asset-module-3.0.11-SNAPSHOT.ear/APP-INF/lib/javamelody-core-1.65.0.jar
Thu Aug 10 16:10:40 UTC 2017     DEBUG     Application type: Classic
Thu Aug 10 16:10:40 UTC 2017     DEBUG     Host: wildfly@172.17.0.4
Thu Aug 10 16:10:40 UTC 2017     DEBUG     parameter defined: storage-directory=javamelody-asset

In SessionListener i wrapps all datasources and later in filter init it only wrapps the one I specified.

Thu Aug 10 16:10:40 UTC 2017     DEBUG     datasources found in JNDI: [java:/jdbc/uvms_asset]
Thu Aug 10 16:10:40 UTC 2017     DEBUG     Datasource needs rewrap: java:/jdbc/uvms_asset of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:10:40 UTC 2017     DEBUG     Datasource rewrapped: java:/jdbc/uvms_asset
Thu Aug 10 16:10:40 UTC 2017     DEBUG     parameter defined: displayed-counters=http,sql,ejb,error,log
Thu Aug 10 16:10:40 UTC 2017     DEBUG     parameter defined: system-actions-enabled=true
Thu Aug 10 16:10:40 UTC 2017     DEBUG     parameter defined: datasources=java:/jdbc/uvms_asset

**Comment by pethers** [comment]
Same behavior with 1.69.0-SNAPSHOT

Debug log
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource rewrapped: java:/jdbc/uvms_config
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource needs rewrap: java:/jdbc/uvms_exchange of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource rewrapped: java:/jdbc/uvms_exchange
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource needs rewrap: java:/jdbc/uvms_mobterm of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource rewrapped: java:/jdbc/uvms_mobterm
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource needs rewrap: java:/jdbc/uvms_movement of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource rewrapped: java:/jdbc/uvms_movement
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource needs rewrap: java:/jdbc/uvms_rules of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource rewrapped: java:/jdbc/uvms_rules
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource needs rewrap: jdbc/USM2 of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource rewrapped: jdbc/USM2
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource needs rewrap: jdbc/uvms_asset of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource rewrapped: jdbc/uvms_asset
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource needs rewrap: jdbc/uvms_audit of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource rewrapped: jdbc/uvms_audit
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource needs rewrap: jdbc/uvms_config of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource rewrapped: jdbc/uvms_config
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource needs rewrap: jdbc/uvms_exchange of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource rewrapped: jdbc/uvms_exchange
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource needs rewrap: jdbc/uvms_mobterm of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource rewrapped: jdbc/uvms_mobterm
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource needs rewrap: jdbc/uvms_movement of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource rewrapped: jdbc/uvms_movement
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource needs rewrap: jdbc/uvms_rules of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:55:58 UTC 2017     DEBUG     Datasource rewrapped: jdbc/uvms_rules
Thu Aug 10 16:55:58 UTC 2017     DEBUG     JavaMelody listener init done in 11 ms
Thu Aug 10 16:56:24 UTC 2017     DEBUG     JavaMelody filter init started
Thu Aug 10 16:56:24 UTC 2017     DEBUG     OS: Linux unknown, amd64/64
Thu Aug 10 16:56:24 UTC 2017     DEBUG     Java: OpenJDK Runtime Environment, 1.7.0_141-mockbuild_2017_05_09_15_35-b00
Thu Aug 10 16:56:24 UTC 2017     DEBUG     Server: WildFly 8.2.0.Final - 1.1.0.Final
Thu Aug 10 16:56:24 UTC 2017     DEBUG     Webapp context: /asset
Thu Aug 10 16:56:24 UTC 2017     DEBUG     JavaMelody version: 1.69.0-SNAPSHOT
Thu Aug 10 16:56:24 UTC 2017     DEBUG     JavaMelody classes loaded from: vfs:/content/asset-module-3.0.11-SNAPSHOT.ear/APP-INF/lib/javamelody-core-1.69.0-SNAPSHOT.jar
Thu Aug 10 16:56:24 UTC 2017     DEBUG     Application type: Classic
Thu Aug 10 16:56:24 UTC 2017     DEBUG     Application version: 3.0.11-SNAPSHOT
Thu Aug 10 16:56:24 UTC 2017     DEBUG     Host: wildfly@172.17.0.4
Thu Aug 10 16:56:24 UTC 2017     DEBUG     parameter defined: storage-directory=javamelody-asset
Thu Aug 10 16:56:24 UTC 2017     DEBUG     parameter defined: displayed-counters=http,sql,ejb,error,log
Thu Aug 10 16:56:24 UTC 2017     DEBUG     parameter defined: system-actions-enabled=true
Thu Aug 10 16:56:24 UTC 2017     DEBUG     parameter defined: datasources=java:/jdbc/uvms_asset
Thu Aug 10 16:56:24 UTC 2017     DEBUG     log listeners initialized
Thu Aug 10 16:56:24 UTC 2017     DEBUG     datasources found in JNDI: [java:/jdbc/uvms_asset]
Thu Aug 10 16:56:24 UTC 2017     DEBUG     Datasource needs rewrap: java:/jdbc/uvms_asset of class org.jboss.jca.adapters.jdbc.WrapperDataSource
Thu Aug 10 16:56:24 UTC 2017     DEBUG     Datasource rewrapped: java:/jdbc/uvms_asset
Thu Aug 10 16:56:24 UTC 2017     DEBUG     counters initialized
Thu Aug 10 16:56:24 UTC 2017     DEBUG     counters data read from files in /tmp/javamelody-asset/asset_wildfly
Thu Aug 10 16:56:24 UTC 2017     DEBUG     collect task scheduled every 60s
Thu Aug 10 16:56:25 UTC 2017     DEBUG     New application version added: 3.0.11-SNAPSHOT
Thu Aug 10 16:56:25 UTC 2017     DEBUG     first collect of data done
Thu Aug 10 16:56:25 UTC 2017     DEBUG     JavaMelody filter init done in 879 ms
---

**Comment by pethers** [comment]
Missed the prefix javamelody. on the context-param. So now verything works as expected with the last snapshots, thanks for all the help.
