### ISSUE TITLE
JDBC monitoring stop working when hibernate.c3p0.dataSourceName is used

### ISSUE THREAD

**Issue by fspacek** [javamelody/javamelody#660]
Hi, 

I discovered that when I set name to c3p0 datasouce in hibernate.cfg.xml via property `hibernate.c3p0.dataSourceName` javamelody stop monitoring jdbc connections.  

Excerpt from config file:
```XML
   <property name="hibernate.connection.driver_class">net.bull.javamelody.JdbcDriver</property>
   <property name="hibernate.connection.driver">oracle.jdbc.driver.OracleDriver</property>
   <property name="hibernate.c3p0.dataSourceName">default</property>
```
Is there any workaround for that? 

Thanks

**Comment by evernat** [comment]
I do not reproduce the issue.
What is the hibernate version?
Can you give the source of a simple project (using maven if possible) to reproduce the issue?

**Comment by fspacek** [comment]
This is really weird. I tried to do sample project, and it is working ok.... 

Legacy project (and also sample project) uses Hibernate 3.6.10.Final. 

However in my original legacy project it is not working, and configuration is the same, 
so it has to be related to something else. 

I will try to do more investigation regarding of this issue, and let you know.

**Comment by evernat** [comment]
Any news?

**Comment by fspacek** [comment]
Hi,

I pretty clueless what can cause it, because when I upgraded to latest version of javamelody, 
it starting working on my local machine but does not work on any other environment.... 

So I'll close this issue and if I find real root cause I will add comment.
