### ISSUE TITLE
Open up Parameters class for integration in Spring Boot Admin project

### ISSUE THREAD

**Issue by dvtoever** [javamelody/javamelody#661]
In the Spring Boot Admin project there is an effort to integrate Javamelody as part of the user interface. A pull request exists, but it is currently blocked, because it depends on accessibility to the `net.bull.javamelody.Parameters` class.

https://github.com/codecentric/spring-boot-admin/pull/450

Would it be possible to make the methods `addCollectorApplication` and r`emoveCollectorApplication` publicly available? That way it is possible to dynamically add applications to the javamelody dashboard once these applications register themselves with service discovery.

**Comment by evernat** [comment]
I would be ok to add the 2 public static methods in the CollectorServlet class.
That is:
```java
public class CollectorServlet extends HttpServlet {
...
	public static void addCollectorApplication(String application, List<URL> urls) throws IOException {
		Parameters.addCollectorApplication(application, urls);
	}

	public static void removeCollectorApplication(String application) throws IOException {
		Parameters.removeCollectorApplication(application);
	}
...
}
```
Is it ok for you?

**Comment by dvtoever** [comment]
That would be perfect!

**Comment by evernat** [comment]
Done, the 2 methods are added in CollectorServlet (74d5f65)
It will be released in 1.69.
You can download a snapshot at:
https://javamelody.ci.cloudbees.com/job/javamelody/net.bull.javamelody$javamelody-core/

**Comment by anderius** [comment]
Would it be possible to open up the rest as well? I use the following method in addition to the two mentiond above:

```
Parameters.getCollectorUrlsByApplications()
```

**Comment by evernat** [comment]
After reading again the spring-boot-admin PR, I have just changed CollectorServlet.addCollectorApplication to the following:
```java
	public static void addCollectorApplication(String application, String urls) throws IOException {
		Parameters.addCollectorApplication(application, Parameters.parseUrl(urls));
	}
```

For Parameters.getCollectorUrlsByApplications(), you only use it in the tests of the PR. It is not my practice to make classes or methods public just for tests.
So I suggest to remove the calls to getCollectorUrlsByApplications() from the tests.

**Comment by evernat** [comment]
javamelody-spring-boot-starter is now released as 1.69.0:
http://search.maven.org/#artifactdetails%7Cnet.bull.javamelody%7Cjavamelody-spring-boot-starter%7C1.69.0%7Cjar

**Comment by anderius** [comment]
@evernat: I was not referring to the Spring Boot Admin PR, my team uses that method in our code to avoid re-adding existing apps to the collector servlet.

In short, we poll Spring Boot Admin for a list of applications, and check if it should be added to Java Melody. We COULD probably add it again every time, but that involves writing to file (`net.bull.javamelody.internal.common.Parameters#writeCollectorApplications`).

**Comment by evernat** [comment]
@anderius 
I suggest that you keep a Set (or a Map) of the added applications in your own bean.
So you can add all applications the first time, then add only the new applications which are not already in your Set.
