### ISSUE TITLE
Enable monitoring of Spring services and controllers invalid

### ISSUE THREAD

**Issue by fddOs** [javamelody/javamelody#663]
In the application.properties I set javamelody.spring-monitoring-enabled = true but did not work, the chart Spring in /monitoring is empty, when i joined
```
@Bean
Public MonitoringSpringAdvisor facadeMonitoringAdvisor () {
JdkRegexpMethodPointcut pointCut = new JdkRegexpMethodPointcut ();
PointCut.setPatterns ("com \\. Example \\ .. *");
Return new MonitoringSpringAdvisor (pointCut);
}
```
In the / monitoring chart Spring only appeared information, the problem is special?

**Comment by evernat** [comment]
Can you give the source of a simple project (using Maven if possible) to reproduce the issue?

**Comment by evernat** [comment]
any news?

**Comment by evernat** [comment]
No response from the reporter, so closing as incomplete.
