### ISSUE TITLE
Display the resource name in the SQL statistics detail view

### ISSUE THREAD

**Issue by vgjosse** [javamelody/javamelody#669]
Hi,

I have a Tomcat server, with two applications deployed, monitored by Javamelody.
Javamelody is installed in the Tomcat server (https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#deployment-on-tomcat-without-modification-of-monitored-webapps-beta).

When I access Javamelody, using app1/monitoring or app2/monitoring, in the SQL statistics detail view, I see App1 and App2 queries mixed together. I'd like to have a way to distinguish App1 and App2 queries .

If it is not possible to use the URL, can you, add an extra column in the detail view table to indicate the name of the JDBC resource used to execute the query?

Thanks.

Vincent.

**Comment by evernat** [comment]
Hello Vincent,
Sorry, but that link you have given is (and will never be more than) a beta feature, in particular for 2 apps in the same tomcat with sql queries in each one. Enhancement like this for this beta feature is a no go.
But you can install javamelody in each of your webapp to fix your problems.
