### ISSUE TITLE
The Oracle execution plan is not well displayed in the SQL request detail screen

### ISSUE THREAD

**Issue by vgjosse** [javamelody/javamelody#670]
Hi,

I have a Tomcat server, with two applications deployed, monitored by Javamelody.
Javamelody is installed in the Tomcat server (https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#deployment-on-tomcat-without-modification-of-monitored-webapps-beta).

In the context.xml file, I have mulitple datasources configured with different database users.

When I open the SQL request detail screen, I have an Oracle exception  java.sql.SQLSyntaxErrorException: ORA-00942: Table or view does not exist. When I execute the plan for the same request in SQL Developer using the same database user as the one defined in context.xml, it works.

I think there is an issue with the database user you use to execute the execution plan.

Thanks.

Vincent.

**Comment by evernat** [comment]
Hello Vincent,
Sorry, but that link you have given is (and will never be more than) a beta feature, in particular for 2 apps in the same tomcat with sql queries in each one.
I suggest that you install javamelody in each of your webapps to fix your problems.
