### ISSUE TITLE
Send metrics to StatsD

### ISSUE THREAD

**Issue by gamefundas** [javamelody/javamelody#678]
I see influxdb but currently we run Netdata as our monitoring platform which provides real time visualization using StatsD server.

Any chance this integration will be made available in Java Melody?

**Comment by evernat** [comment]
Done for the next release (1.70) in [92aeffe](../commit/92aeffe800194544b9c91c1c799b36e74d4b7436).
See [doc](UserGuideAdvanced#sending-metrics-to-statsd).
You can download a nightly build here:
https://javamelody.ci.cloudbees.com/job/javamelody/net.bull.javamelody$javamelody-core/

**Comment by gamefundas** [comment]
This is awesome. Such a fast turnaround. 
Will test and report back.
