### ISSUE TITLE
Collector server - monitored applications registration

### ISSUE THREAD

**Issue by gamefundas** [javamelody/javamelody#679]
Is there a better way to feed the list of applications that we want to monitor through a configuration file? In AWS with most of our clustered applications running on ephemeral nodes it becomes difficult to manage the monitored application list by manually adding them in the collector server. 

If some kind of registration/deregistration REST API could be made available on the collector server, or the application themselves register using the collector server url, this could become lot easier.

**Comment by evernat** [comment]
When you are using the collector server, there is a file named applications.properties in the storage directory. This file lists the applications to monitor. So you can write in this file the monitored applications in advance before (re)starting the collector server.

But for epheremal nodes, I agree that it would be easier if applications register themselves in a known collector server. I will probably add that feature.

**Comment by evernat** [comment]
This is done now by the commit 77fd69d which adds a java api to call from the application code and it's ready for the next release (1.71).
If you look at the commit, you will see that the code calls a http post on the collect server with values in the url.
