### ISSUE TITLE
Choose which disk / filesystem is monitored

### ISSUE THREAD

**Issue by yolani** [javamelody/javamelody#680]
Hello there,

i am sorry if this is not the right place to ask for help but i could not find any discussion forum for melody.

I am using Melody in combination with the Jenkins Monitoring plugin to keep track about the disk usage of my Jenkins slaves. However all slaves are reporting the disk usage for my c-partition even though my jenkins workspace is located on the e-partition, which is an additional physical hard-drive.

So my question is: Who does melody decide which filesystem is monitored and how can i configure this?

Greetings,

Christian

**Comment by evernat** [comment]
The free disk space displayed is from the disk of the temp directory. And there is no parameter to change that.

But you may specify a different temp directory when launching a slave.
Either with a system property such as -Djava.io.tmpdir=/tmp (but I suppose that specifying a system property for the slave depends on how you launch it),
or by changing the default temp directory of the OS.
