### ISSUE TITLE
Do the collector server parameters affect all applications?

### ISSUE THREAD

**Issue by Zidedine** [javamelody/javamelody#683]
Hi,

I have a collector server with N applications being monitorized.
If I set the parameter javamelody.disabled = true or javamelody.no-database=true only in the server of collector server, this configuration will affect all applications linked in the collector? They all stop monitoring?

As the user in issue #679, I think an API Rest could be great, with methods for register apps and obtain the list of monitorized apps.

Thanks for your job.

**Comment by evernat** [comment]
No the parameters in the optional collector server do not affect the applications.
For example, if javamelody.disabled = true or javamelody.no-database=true are set in the collector server, it does not affect the applications and it does not stop the monitoring in the applications.

Other examples: the parameters url-exclude-pattern, http-transform-pattern, sql-transform-pattern, maven-repositories, datasources, rum-enabled, sampling-seconds, jmx-expose-enabled, disabled, no-database are supported only in applications (and not in the collector server).

The parameters log, storage-directory, resolution-seconds, warning-threshold-millis, severe-threshold-millis, monitoring-path, admin-mails, mail-session, mail-periods, allowed-addr-pattern, authorized-users, graphite-address, influxdb-url, cloudwatch-namespace, datadog-api-key are supported in the collector server, as said in the [doc](https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#optional-centralization-server-setup) (as well as in the applications without using a collector server). The parameters obsolete-graphs-days, obsolete-stats-days, locale and some others are also supported in the collector server, but not said in the doc.
