### ISSUE TITLE
InfluxDB Integration

### ISSUE THREAD

**Issue by v4vamsee** [javamelody/javamelody#685]
Currently we use JavaMelody as our primary APM.

We just implemented influxdb+telegraf+grafana to monitor system metrics, Jmeter metrics for historical analysis.

Are there plans in future to use influxdb as centralized repository for JavaMelody? Not just for metrics but also to store SQL, Spring, http, jsp statistics.  And use Grafana to custom query the data.

**Comment by evernat** [comment]
There is integration to publish metrics to influxdb:
https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#sending-metrics-to-influxdb
but there are no plans to use influxdb as centralized repository except for metrics.
