### ISSUE TITLE
Repositories inheriting to JpaRepository not working using Java Melody

### ISSUE THREAD

**Issue by Sgitario** [javamelody/javamelody#686]
We followed the instructions from here: https://github.com/javamelody/javamelody/wiki/SpringBootStarter

And the controllers and services are working ok, but the Repositories like:

public interface MyRepository exnteds JpaRepository<Entity, Integer> {
...
}

Stopped being wired... Can you help here? Thanks,

**Comment by evernat** [comment]
Can you give the source of a simple project to reproduce the issue?

**Comment by evernat** [comment]
Any news?
Can you give the source of a simple project to reproduce the issue?

**Comment by Sgitario** [comment]
Thanks for your reply. I checked again with the latest update and the issue is gone. Regards.
