### ISSUE TITLE
Strange characters in graphs 

### ISSUE THREAD

**Issue by KyleRogers** [javamelody/javamelody#687]
If we deploy our application (*.war) on a customer's infrastructure, all texts in graphs are broken. The very same montioring of the application works when deployed in our local infrastructure. All "plain" texts are rendered corretly.

- Only graphs are affected
- The problem seems to be environment specific

I've no clue what we need to do/install/change on the customers environment to be able to have proper texts in graphs again. When we first installed the application the graphs worked. Our customers administrators have updated the system / installed patches since then but cannot tell what they've done exactly. I've never seen java melody showing broken graphs before.

Broken Dashboard: 
![javamelody_charset_graph_error](https://user-images.githubusercontent.com/990538/31614710-97af59fa-b287-11e7-8dfe-b224338b3ee1.png)

Betriebssystem: | Linux, 3.10.0-693.2.2.el7.x86_64 , amd64/64 (16 Kerne)
Java: | Java(TM) SE Runtime Environment, 1.8.0_111-b14
JVM: | Java HotSpot(TM) 64-Bit Server VM, 25.111-b14, mixed mode
Server: | Apache Tomcat/8.0.36

Same Application works fine in our local test environment:
Betriebssystem: | Linux, 4.4.0-78-generic , amd64/64 (16 Kerne)
Java: | Java(TM) SE Runtime Environment, 1.8.0_121-b13
JVM: | Java HotSpot(TM) 64-Bit Server VM, 25.121-b13, mixed mode
Server: | Apache Tomcat/8.0.41

Do you have any idea what we need to change or what our customer needs to install?

**Comment by evernat** [comment]
There was the same issue with exactly the same characters in this issue:
https://issues.jenkins-ci.org/browse/JENKINS-47334

So I will say the same here:

> It is certainly a font problem in your OS.
> 
> In case of Chinese, it was reported that "yum groupinstall chinese-support" has fixed the problem. So you may do the same with your own language [instead of Chinese].
> 
> Otherwise you can try to add DejaVuSansMono.ttf or DejaVuSans-Bold.ttf in your server and to setup a fonts.conf alias in your server:
> 
> <match target="pattern">
>    <test qual="any" name="family">
>       <string>mono</string>
>    </test>
>    <edit name="family" mode="assign">
>       <string>monospace</string>
>    </edit>
> </match>
> 
(In fact, that user was probably in a country with a particular non-latin alphabet and so with a particular configuration of fonts in the OS.)

Is it OK for you?

**Comment by KyleRogers** [comment]
Hi @evernat,

thanks for your reply. I guess just installing language support won't help because even using en-US as (browser) locale didn't work. The fonts.conf alias might be a good starting point. I cannot update/change that by myself because it's a cutomer's machine and I've only web access to that machine. Thus I need my customer's administrators to be willing to change the configuration ;-). It'll take some time until I can convience them to help me, I think.
Thank you for your help.

**Comment by evernat** [comment]
I am now convinced that the issue in the graphs (images generated by the server) is not related to the browser's locale but is related to the configuration of fonts in the server OS. So your guess that installing language support won't help is based on a bad assumption.

**Comment by evernat** [comment]
Let us know if it helps.

**Comment by evernat** [comment]
Someone (@valentin-nasta) said to check the installed fonts:
`fc-list`

And the issue was solved simply by installing the DejaVu fonts:
`yum install dejavu-sans-fonts.noarch dejavu-sans-mono-fonts.noarch`

https://stackoverflow.com/questions/46699967/jenkins-load-statistics-graph-weird-encoding/46924944#46924944
