### ISSUE TITLE
JavaMelody using Jboss EAP 6.4 

### ISSUE THREAD

**Issue by alisahlan** [javamelody/javamelody#688]
I've been copy the files javamelody-1.60.jar and jrobin-1.5.9.jar to the WEB-INF/lib directory of the war of the webapp (application war.file) to monitor our application. 

But, now we are facing a crash on jboss application server, we cannot upload file and view the file in PDF file. 

So we revert the war file without add the javamelody & jrobin. the application it back to normal.

I do not know of a particular compatibility issue between jboss and javamelody. please advise? thanks

Jboss eap 6.4
Java jre 1.8
javamelody-1.60.jar
jrobin-1.5.9.jar

**Comment by evernat** [comment]
Without logs or stack-traces of exceptions this is not a valid issue.
Note that you should probably upgrade to javamelody 1.65.0 (later versions of javamelody are not compatible with JBoss EAP 6, because JBoss EAP 6 is using CDI 1.0 and not CDI 1.1).
