### ISSUE TITLE
Physical memory shows red, but physical memory is at about 12%

### ISSUE THREAD

**Issue by hawkeyej** [javamelody/javamelody#689]
I have an r3.xlarge instance in AWS which has 30 GB of RAM, but the Physical memory graph shows memory as RED.

**Comment by evernat** [comment]
Green to red colors are there just to have pretty graphs. Green at the bottom and red near the top.
So a red color does not mean something bad.

**Comment by evernat** [comment]
Colors are here to make things pretty. Green to green is not pretty.
But just don't bother the colors: you know by yourself that 12% of used memory is probably OK.
