### ISSUE TITLE
Does not show time for recieving restTemplate post request

### ISSUE THREAD

**Issue by jaspreet8** [javamelody/javamelody#690]
I am trying to monitor rest template requests for POST request but the time it shows is not proper.It does not show time after which the post request has completed and returned result. I think it only counts time for hitting that url and not the time taken to complete that request and get result.

**Comment by evernat** [comment]
When monitoring Spring RestTemplate, the time measured includes the execution of the request until having the http response status (200 for example). But it does not include the time of reading the response and converting it to an object.
In fact, Spring RestTemplate uses a ResponseExtractor to extract the data from the response. And the time measured does not include extracting the data from the response and converting it to an object. So if the data is very very large, the time of reading it over the network is not included.
