### ISSUE TITLE
Javamelody feeding to InfluxDB - two tags to distinguish data is not sufficiant

### ISSUE THREAD

**Issue by BrommD** [javamelody/javamelody#694]
We have a shared environment using Wildlfy instances running same application on multiple ports using different application configuration. This is working well so far. Now we try to embed the new InfluxDB feature at Javamelody and stumble upon the fact, that only two tags (columns) defines a unique entry.

app = taken from application,xml -> module/web/context-root
host = well...ok.

Running ~ 50 application of same type on one server produces a lot of entries in InfluxDB, but all are merged into this 

`select * from "javamelody.systemLoad" where time > now() -1h and host='vm-cos-int7.ops.local';
name: javamelody.systemLoad
time                application    host                  value
----                -----------    ----                  -----
1509975417000000000 /TOPJavaMelody vm-cos-int7.ops.local 1.08
1509975418000000000 /TOPJavaMelody vm-cos-int7.ops.local 1.15
1509975460000000000 /TOPJavaMelody vm-cos-int7.ops.local 1.23
1509975477000000000 /TOPJavaMelody vm-cos-int7.ops.local 1.24`

Is there a way to add another column, which can be used to provide more information or simply extend exiting parameter function "-Djavamelody.application-name=myapplication" to populate this column with something unique.

thx

**Comment by evernat** [comment]
I think that the value of the `application-name` parameter could indeed replace the context path (`/TOPJavaMelody` replaced by `myapplication` in your case) in InfluxDB, Graphite, StatsD, CloudWatch or Datadog, when the `application-name` parameter is defined. Would it be ok for you?

But note that adding or changing the `application-name` parameter in an application with existing monitoring data will change the storage directory, so it would cause losing of that existing monitoring data if the files from the storage directory are not moved at the same time.

**Comment by BrommD** [comment]
Thanks for reply. For me this would work. As, like stated, the my captured data until today cannot be used properly as 50 instances are caught into one "context-path". Worthless for me. 
Maybe this would be a good approach to not change application-name for this, but maybe provide a new parameter, only valid for mentioned 3rd party solutions, and is being used for only for separating the provided instances information, i.e. for InfluxDB if would be used for populating "app" column, if passed, otherwise, proceed like today and use "context-path". In case somebody already implemented this today, this would not break captured data process or logic.

I'm fine with every solution as long I can provide a unique tag for each JVM instance using JavaMelody.

**Comment by evernat** [comment]
I think that the `application-name` parameter is well suited for that case.
It's pushed now in master and ready for the next release (1.71).
You can download a snapshot including the change at:
https://javamelody.ci.cloudbees.com/job/javamelody/net.bull.javamelody$javamelody-core/

**Comment by BrommD** [comment]
thanks for implementing this. this is much better now
`select * from "javamelody.systemLoad" where time > now() -45m;
name: javamelody.systemLoad
time                application              host                  value
----                -----------              ----                  -----
1510322267000000000 top_lci_test@vm-cos-int7 vm-cos-int7.ops.local 3.65
1510322270000000000 top_sca_prod@vm-cos-int7 vm-cos-int7.ops.local 3.65
1510322327000000000 top_lci_test@vm-cos-int7 vm-cos-int7.ops.local 1.86
1510322330000000000 top_sca_prod@vm-cos-int7 vm-cos-int7.ops.local 1.86
1510322387000000000 top_lci_test@vm-cos-int7 vm-cos-int7.ops.local 1.07
1510322390000000000 top_sca_prod@vm-cos-int7 vm-cos-int7.ops.local 1.07
1510322419000000000 crm_lci_prod@vm-cos-int7 vm-cos-int7.ops.local 1.84
1510322419000000000 aut_sca_prod@vm-cos-int7 vm-cos-int7.ops.local 1.84
1510322419000000000 crm_lir_prod@vm-cos-int7 vm-cos-int7.ops.local 1.84
1510322421000000000 ibe_sca_prod@vm-cos-int7 vm-cos-int7.ops.local 1.84
1510322421000000000 stg_sca_prod@vm-cos-int7 vm-cos-int7.ops.local 1.84
`

**Comment by BrommD** [comment]
we have started to deploy this version of JavaMelody to our environment, which is a mixed environment using Jboss8 with Java7 and Jboss10 with Java8. Within Java8/Jboss10 the snapshot is working perfectly, whereas within Java7/Jboss8 we got following error on startup when using the same module

{"JBAS014671: Failed services" => {"jboss.deployment.unit.\"minimon.war\".WeldStartService" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"minimon.war\".WeldStartService: Failed to start service
    Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001417: Enabled interceptor class <class>net.bull.javamelody.MonitoringCdiInterceptor</class> in vfs:/content/minimon.war/WEB-INF/lib/javamelody.jar/META-INF/beans.xml@6 does not match an interceptor bean: the class is not found, or not annotated with @Interceptor and still not registered through a portable extension, or not annotated with @Dependent inside an implicit bean archive"}}

Ayn idea whats up?

**Comment by evernat** [comment]
Sorry. No idea at the moment. And it is not a known exception with javamelody.
