### ISSUE TITLE
Add a parameter for measuring cpu time.

### ISSUE THREAD

**Issue by locuslin** [javamelody/javamelody#696]
As documented , measuring cpu might cost about 0.6 millseconds,and it will cost much if a request contains complex opearations.
I tried to find a way to disable it ,but because the value "CPU_TIME_ENABLED" is static, so the only way now is to use relection.
Would you like to make it possible to simply disable it ?

**Comment by evernat** [comment]
You are wrong. It was documented at 0.6 microseconds (and that was about 8 years ago), not milliseconds. It makes a big difference and there is no need to disable it.
