### ISSUE TITLE
Question: Prometheus: Definable Labels via ENV

### ISSUE THREAD

**Issue by phal0r** [javamelody/javamelody#698]
Hi,

thanks for this great tool and thanks for adding prometheus support. This comes in very handy for our planned switch to prometheus.

I have a question, cause I am not sure, if this would be a feature for java melody or the prometheus config. We will deploy several tomcat instances, that are grouped as services (in docker terminology) and we want to be able to distinguish between these groups, to build up meaningful dashboards. It would be helpful to add labels to each group to accomplish this. We could do this either as a configuration of the java melody client like so:
`-Djavamelody.prometheus-default-label=my_group_name` 

or in relabeling phase during prometheus scrape.  Do you guys think, it is a good idea to have that as configuration option for the java melody client?

note: we cannot use the labeling as mentioned in the java melody wiki, since we want to use the dns scrape config, which does not support labels in configuration. 

Thanks in advance for your thoughts!

**Comment by evernat** [comment]
The Prometheus feature in javamelody was contributed by a javamelody user and I don't know Prometheus well myself.
But the relabeling phase of Prometheus seems good for your use case, so I would suggest to go that way.

**Comment by phal0r** [comment]
Yeah, thanks for your feedback. I will go this road and see how it turns out.
