### ISSUE TITLE
Datadog integration non-functional due to invalid JSON

### ISSUE THREAD

**Issue by bluegaspode** [javamelody/javamelody#701]
The current datadog integration is non-functional.

The generated JSON looks like the following, a colon is missing between array entries: 
```
{ "series" : [
{"metric":"javamelody.usedMemory","points":699794512.00,"host":"Stefans-MBP","tags":["application":"/"]}
{"metric":"javamelody.cpu","points":0.00,"host":"Stefans-MBP","tags":["application":"/"]}
]}
```

The leads to exceptions from datadog like the following: 

Error connecting to Datadog (400): Payload is not in the expected format: invalid character ':' after array element

**Comment by bluegaspode** [comment]
in addition the "tags" entry is also not valid JSON.
Datadog expects an array of strings like
`"tags":["application:/"]`

**Comment by bluegaspode** [comment]
um, did anyone actually tested it against datadog?

the "points" entry, needs to be an array with timestamp and data.

So a metric accepted by datadog looks like this: 
`{"metric":"javamelody.usedMemory","points":[[1512751139,704774344.00]],"host":"Stefans-MBP","tags":["application:/"]},`

**Comment by evernat** [comment]
Unfortunately, I do not have a test account (I have looked at web site and it's not clear what I can do with a free account). And it seems that I have overlooked and/or misunderstood some points in the doc as it was written at that time. Sorry.
But fortunately, your PR #702 is merged in master now.
You can download a snapshot including the PR at:
https://javamelody.ci.cloudbees.com/job/javamelody/net.bull.javamelody$javamelody-core/
Thanks.
