### ISSUE TITLE
Could not evaluate condition on DefaultAdvisorAutoProxyCreator - causing error in Spring Boot 1.3 

### ISSUE THREAD

**Issue by baba216** [javamelody/javamelody#703]
Hello, I am trying to use JavaMelody with one of projects. I tried using Javamelody with one dummy project with spring boot version 1.5 and simple jpa and it worked fine with configs mentioned in doc. 

But main project(which has scheduling) is still using 1.3 while startup I am getting this stack trace which I am not able to resolve: 

I have added this property in properties file too-
javamelody.advisor-auto-proxy-creator-enabled=false

using spring boot version - 1.3.2.RELEASE

> {"@timestamp":"2017-12-11T07:04:41.166+00:00","@version":1,"message":"Application startup failed","logger_name":"org.springframework.boot.SpringApplication","thread_name":"main","level":"ERROR","level_value":40000,"stack_trace":"java.lang.IllegalStateException: Could not evaluate condition on net.bull.javamelody.JavaMelodyAutoConfiguration#defaultAdvisorAutoProxyCreator due to org/springframework/boot/web/servlet/FilterRegistrationBean not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)\n\tat org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:55)\n\tat org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102)\n\tat org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:178)\n\tat org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:140)\n\tat org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116)\n\tat org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:333)\n\tat org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243)\n\tat org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273)\n\tat org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98)\n\tat org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:678)\n\tat org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:520)\n\tat org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)\n\tat org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)\n\tat org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:307)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)\n\tat com.nethum.starfox.Application.main(Application.java:22)\nCaused by: java.lang.NoClassDefFoundError: org/springframework/boot/web/servlet/FilterRegistrationBean\n\tat java.lang.Class.getDeclaredMethods0(Native Method)\n\tat java.lang.Class.privateGetDeclaredMethods(Class.java:2701)\n\tat java.lang.Class.getDeclaredMethods(Class.java:1975)\n\tat org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:609)\n\tat org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:521)\n\tat org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:507)\n\tat org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:567)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:683)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:627)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:597)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1445)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:975)\n\tat org.springframework.boot.autoconfigure.condition.BeanTypeRegistry$OptimizedBeanTypeRegistry.addBeanTypeForNonAliasDefinition(BeanTypeRegistry.java:289)\n\tat org.springframework.boot.autoconfigure.condition.BeanTypeRegistry$OptimizedBeanTypeRegistry.addBeanType(BeanTypeRegistry.java:278)\n\tat org.springframework.boot.autoconfigure.condition.BeanTypeRegistry$OptimizedBeanTypeRegistry.getNamesForType(BeanTypeRegistry.java:259)\n\tat org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:182)\n\tat org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:171)\n\tat org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:139)\n\tat org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:113)\n\tat org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)\n\t... 17 common frames omitted\nCaused by: java.lang.ClassNotFoundException: org.springframework.boot.web.servlet.FilterRegistrationBean\n\tat java.net.URLClassLoader.findClass(URLClassLoader.java:381)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:424)\n\tat sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:357)\n\t... 37 common frames omitted\n","HOSTNAME":"Shubhams-MacBook-Pro.local","app_name":"starfox","log_type":"app"}

**Comment by evernat** [comment]
org/springframework/boot/web/servlet/FilterRegistrationBean is not found because your spring boot version (1.3.2.RELEASE) is old.
You can upgrade your spring boot version.
Otherwise you can see this [doc](https://github.com/javamelody/javamelody/wiki/SpringBootStarter#or-integration-without-the-spring-boot-starter) which is an older and manual integration of javamelody for spring boot, without the spring boot starter.
