### ISSUE TITLE
Centralized collector server improvements

### ISSUE THREAD

**Issue by Zidedine** [javamelody/javamelody#714]
## Suggested improvements

**1. It could be great that JavaMelody API provides a REST service with this operations**

- /addapplication (name and path): Adds an app to centralized collector server.
- /removeapplication (name): Removes an app from centralized collector server. 
- /listapplications: List apps linked in centralized collector server. With the state of each app (ok-green OR disconnected/with problems-red) 

Thank you for this great API.

**Comment by evernat** [comment]
Hi Zidedine,
Sorry for the delay.
In 1.71, you will be able to call a java api in the monitored webapp to automatically register the application in the collector server (or to a registor a new node in an existing application).
With the same java api you can remove the application (or remove a node) from the collector server.
See the [doc](https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#7-automatic-registration-of-applications).
This java api is part of #679 and if you read the commit 77fd69d, you can see that the java api calls a http(s) url. For example: http://collectorserver:8080/javamelody?appName=mywebapp&appUrls=http://myhost:8080/mywebapp&action=registerNode
and http://collectorserver:8080/javamelody?appName=mywebapp&appUrls=http://myhost:8080/mywebapp&action=unregisterNode

For the list of applications, you can call http://collectserver:8080/javamelody?part=applications&format=xml or http://collectserver:8080/javamelody?part=applications&format=json 
The values will include the exceptions when an application is unavailable.
This is documented at the end of [this page](https://github.com/javamelody/javamelody/wiki/ExternalAPI#xml).
