### ISSUE TITLE
Tomcat 8 and JNDI doesn't show Statistics

### ISSUE THREAD

**Issue by ratherDashing** [javamelody/javamelody#716]
Melody Log:

Tue Dec 26 10:38:19 PST 2017     DEBUG     JavaMelody listener init started
Tue Dec 26 10:38:19 PST 2017     DEBUG     datasources found in JNDI: [java:comp/env/jdbc/common-datastore]
Tue Dec 26 10:38:19 PST 2017     DEBUG     datasource rebinded: java:comp/env/jdbc/common-datastore from class org.apache.tomcat.dbcp.dbcp2.BasicDataSource to class com.sun.proxy.$Proxy92
Tue Dec 26 10:38:19 PST 2017     DEBUG     JavaMelody listener init done in 14 ms
Tue Dec 26 10:38:53 PST 2017     DEBUG     JavaMelody filter init started
Tue Dec 26 10:38:53 PST 2017     DEBUG     OS: Linux unknown, amd64/64
Tue Dec 26 10:38:53 PST 2017     DEBUG     Java: OpenJDK Runtime Environment, 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12
Tue Dec 26 10:38:53 PST 2017     DEBUG     Server: Apache Tomcat/8.0.32 (Ubuntu)
Tue Dec 26 10:38:53 PST 2017     DEBUG     Webapp context: /common-datastore
Tue Dec 26 10:38:53 PST 2017     DEBUG     JavaMelody version: 1.70.0
Tue Dec 26 10:38:53 PST 2017     DEBUG     JavaMelody classes loaded from: file:/var/lib/tomcat8/webapps/common-datastore/WEB-INF/lib/javamelody-core-1.70.0.jar
Tue Dec 26 10:38:53 PST 2017     DEBUG     Application type: Classic
Tue Dec 26 10:38:53 PST 2017     DEBUG     Application version: 1.0.14-SNAPSHOT
Tue Dec 26 10:38:53 PST 2017     DEBUG     Host: afdfdsafdfdsa@127.0.1.1
Tue Dec 26 10:38:53 PST 2017     DEBUG     log listeners initialized
Tue Dec 26 10:38:53 PST 2017     DEBUG     datasources found in JNDI: [java:comp/env/jdbc/common-datastore]
Tue Dec 26 10:38:53 PST 2017     DEBUG     counters initialized
Tue Dec 26 10:38:53 PST 2017     DEBUG     counters data read from files in /tmp/tomcat8-tomcat8-tmp/javamelody/common-datastore_afdfdsafdfdsa
Tue Dec 26 10:38:53 PST 2017     DEBUG     collect task scheduled every 60s
Tue Dec 26 10:38:53 PST 2017     DEBUG     New application version added: 1.0.14-SNAPSHOT
Tue Dec 26 10:38:53 PST 2017     DEBUG     first collect of data done
Tue Dec 26 10:38:53 PST 2017     DEBUG     JavaMelody filter init done in 328 ms

Config in Spring App:

spring.datasource.jndi-name=java:comp/env/jdbc/common-datastore

Context.xml

Context>
    Resource name="jdbc/common-datastore" type="javax.sql.DataSource" auth="Application" driverClassName="org.h2.Driver" maxTotal="100" maxIdle="50" username="sa" password="" url="jdbc:h2:file:/opt/commondatastore/common-datastore;IFEXISTS=TRUE;FILE_LOCK=SOCKET;AUTO_SERVER=TRUE;TRACE_LEVEL_FILE=0;TRACE_LEVEL_SYSTEM_OUT=0" />
</Context>

I also tried auth="Container"

Melody looks happy, the spring app is happy, but no SQL queries are being logged.  I got excited when I saw a little activity but that was just melody seeing how much memory was free in the DB.  Is tomcat 8 not supported?  I saw it was untested.

Thanks!

**Comment by evernat** [comment]
Tomcat 8 is now tested.
But the problem is probably that Spring loads its context and keep a cache of the JNDI datasource in a servlet listener (Spring ContextLoaderListener) before JavaMelody initializes the monitoring on the JNDI datasource.

In this case, I suggest to add the javamelody monitoring for Spring.
That is add `classpath:net/bull/javamelody/monitoring-spring.xml` (or at least `classpath:net/bull/javamelody/monitoring-spring-datasource.xml`) in your Spring context.
You can see an example with the ContextLoaderListener in web.xml at the end of the JDBC chapter of the user's guide:
https://github.com/javamelody/javamelody/wiki/UserGuide#7-jdbc

**Comment by ratherDashing** [comment]
Thanks!  This was fixed by using the following Annotation:

@ImportResource("classpath:net/bull/javamelody/monitoring-spring-datasource.xml")

Just in case someone stumbles upon this through google or if any documentation needs updating.
