### ISSUE TITLE
Missing UI in Java Melody Report

### ISSUE THREAD

**Issue by Gireesh05** [javamelody/javamelody#719]
Hi, 

I am using Java Melody to Monitor the Memory usage, CPU usage, etc..
But % CPU used is not getting displayed. Do i need to insert any thing in web.xml of my tomcat??
I added below commands to my XML file

```xml
<filter>
       <filter-name>monitoring</filter-name>
       <filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
</filter>
<filter-mapping>
       <filter-name>monitoring</filter-name>
       <url-pattern>/*</url-pattern>
</filter-mapping>
<listener>
       <listener-class>net.bull.javamelody.SessionListener</listener-class>
</listener>
```

**Comment by evernat** [comment]
Your config in web.xml is ok.
The graph of % CPU used should be displayed.
Can you give a screenshot of the main graphs?

**Comment by evernat** [comment]
Any news?

**Comment by aboe026** [comment]
I'm seeing the same thing on my Windows server. When I run the server on Ubuntu though I can see the CPU report. So it seems like an issue with Windows. I'm creating a new issue that covers this

**Comment by evernat** [comment]
No response from the reporter so closing as invalid/incomplete.
