### ISSUE TITLE
Javamelody plugin 1.70.0

### ISSUE THREAD

**Issue by jvtran1400** [javamelody/javamelody#720]
I have Javamelody 1.70.0 installed on Confluence 6.0.6.  The Database is Oracle 12c.  I have a problem with the monitoring page showing contents on the following graphs.

I'm most concerned with getting these graphs working asap.
- Active JDBC Connections
- Used JDBC Connections

These are other graphs not displaying data.
- SQL Hits Per Minute
- SQL Mean Times
- % of SQL Errors
- % Garbage Collector Time
- Transactions per minute
- % of JSP Errors

See attached PDF of screen shots.
[Javameldoy plugin graph no data screen shots  1-22-18.pdf](https://github.com/javamelody/javamelody/files/1653478/Javameldoy.plugin.graph.no.data.screen.shots.1-22-18.pdf)

James 
jvtran@up.com

**Comment by evernat** [comment]
For that, you need to use a datasource as said here:
https://github.com/javamelody/javamelody/wiki/AtlassianPlugin
