### ISSUE TITLE
Release of Javamelody 1.71 tentative release date

### ISSUE THREAD

**Issue by GhoshSidd** [javamelody/javamelody#721]
Hello,

Sorry I am new to Github , my question is not related to any issues with the current releases of Javamelody.

I just wanted to ask if there is any tentative release date for Javamelody 1.71 version ?

Thanks and Regards
Sidd

**Comment by evernat** [comment]
JavaMelody 1.71.0 is released now (except the Grails plugin):
https://github.com/javamelody/javamelody/releases
