### ISSUE TITLE
JavaMelody Displaying wrong system CPU  usage

### ISSUE THREAD

**Issue by v4vamsee** [javamelody/javamelody#722]
We are using JavaMelody to as an APM in our organization.

Currently in the melody graphs, we were seeing high CPU usage by "System". When we compared this graph to CPU Usage graph generated by other tools (nagios & vsphere) melody seems to have it wrong. 

We were expecting to see similar graphs across the tools, Could this be a bug in Melody?

How is System CPU collected by Melody?

**Comment by evernat** [comment]
The system cpu is collected by asking the value to the jvm (OperatingSystemMXBean) once per minute (configurable).
Can you attach the javamelody graph and the graphs of the other tools to compare?
Note that resolutions may differ between tools. I have sometimes seen nagios graphs with resolutions which don't show details as shown by the javamelody graph.

**Comment by evernat** [comment]
No response from the reporter so closing this issue as invalid/incomplete.
