### ISSUE TITLE
Passwords shown on JVM-Infotab

### ISSUE THREAD

**Issue by sprengstuff** [javamelody/javamelody#723]
For some things you absolutely have to use system properties, like 
javax.net.ssl.keyStorePassword and 
javax.net.ssl.trustStorePassword.
And the application ops/sytem admin (understandably) does not want us to know them in a production evnironment... while we want to have access to JavaMelody.

Please reconsider #708

**Comment by evernat** [comment]
I will add comments in #708 so closing this issue as duplicate.
