### ISSUE TITLE
JavaMelody returns a 404 error

### ISSUE THREAD

**Issue by fritaly** [javamelody/javamelody#724]
I've been using JavaMelody 1.59.0 for a while on a web server. The user authentication is managed by the servlet container (Tomcat) against an Active Directory.

Everything was working fine until I recently restart the web server. After the restart, I discovered that opening the "/monitoring" url returned a 404 error.

I personally didn't make any change which would explain this problem but changes could have been introduced by someone else on the machine.

I reapplied the install procedure I used the first time and everything looked file: the jar (javamelody.jar and jrobin.jar) files were present in the expected tomcat's lib directory, the web.xml file was fine. The file permissions were correct.

When I open the "/monitoring" url, my custom login page shows up. If I use incorrect credentials, my custom error page shows up. I have the exact same JavaMelody setup on another server where JavaMelody works so this rules out any issue pertaining to my user (authentication error).

I confirmed that the JavaMelody classes are well loaded by Tomcat because I can see the following frame in the stack traces (catalina.out file):

```
...
at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:178) [javamelody-1.59.0.jar:na]
...
```

I even looked on the file-system and could see the JavaMelody (*.rrd) work files updated minutes ago.

However for whatever reason, the console UI doesn't show up any more. 

Network traces (on the web server where JM works) show that my web browser should send the following requests:

- /monitoring
- /monitoring?resource=resizable_tables.js
- /monitoring?resource=sorttable.js
...

But on the web server where I have this issue, the first request returns a 404.

I tried enabling the JavaMelody logs by tweaking my webapp's logback.xml file to no avail. JavaMelody doesn't generate a single message (even in DEBUG).

Have you ever experienced this problem before ? 

Thanks a million

Edit: I forgot to add that I cannot see a single error when the webapp starts

**Comment by evernat** [comment]
First, a side note: it is not recommended to put javamelody and jrobin jar files in the tomcat's lib directory. The doc says to put the jar files in the webapp's WEB-INF/lib directory.

That said, I have not experienced this before. I would suggest to check the url you use: perhaps you are using the right path of the webapp before /monitoring. And I suggest to check if you use the javamelody parameter "monitoring-path" (if set to something else than "/monitoring", it would cause your problem).

Anyway, you should see the debugging logs at the end of the "last_shutdown.html" file in the javamelody storage directory. (It is written when the webapp is stopped, so you can stop & start the server in order to write it.) In those debugging logs, you will see the context path, the parameters, etc.

**Comment by fritaly** [comment]
Thanks for the quick reply.

I checked the debug logs at the end of "last_shutdown.html" (I didn't know about this local file) but couldn't see anything obvious.

```
Fri Jan 12 07:00:35 UTC 2018     DEBUG     JavaMelody listener init started
Fri Jan 12 07:00:35 UTC 2018     DEBUG     datasources found in JNDI: []
Fri Jan 12 07:00:35 UTC 2018     DEBUG     JavaMelody listener init done in 41 ms
Fri Jan 12 07:00:39 UTC 2018     DEBUG     JavaMelody filter init started
Fri Jan 12 07:00:39 UTC 2018     DEBUG     OS: Linux unknown, amd64/64
Fri Jan 12 07:00:39 UTC 2018     DEBUG     Java: Java(TM) SE Runtime Environment, 1.8.0_77-b03
Fri Jan 12 07:00:39 UTC 2018     DEBUG     Server: Apache Tomcat/8.0.41
Fri Jan 12 07:00:39 UTC 2018     DEBUG     Webapp context: /<webapp>
Fri Jan 12 07:00:39 UTC 2018     DEBUG     JavaMelody version: 1.59.0
Fri Jan 12 07:00:39 UTC 2018     DEBUG     JavaMelody classes loaded from: file:/<base-dir>/tomcat/lib/javamelody-1.59.0.jar
Fri Jan 12 07:00:39 UTC 2018     DEBUG     Host: <hostname>@<ip>
Fri Jan 12 07:00:39 UTC 2018     DEBUG     log listeners initialized
Fri Jan 12 07:00:39 UTC 2018     DEBUG     datasources found in JNDI: []
Fri Jan 12 07:00:39 UTC 2018     DEBUG     counters initialized
Fri Jan 12 07:00:40 UTC 2018     DEBUG     counters data read from files in /<base-dir>/tomcat/temp/javamelody/<webapp>_<hostname>
Fri Jan 12 07:00:40 UTC 2018     DEBUG     collect task scheduled every 60s
Fri Jan 12 07:00:40 UTC 2018     DEBUG     first collect of data done
Fri Jan 12 07:00:40 UTC 2018     DEBUG     JavaMelody filter init done in 424 ms
Sat Jan 13 00:00:47 UTC 2018     DEBUG     Obsolete files deleted. JavaMelody disk usage: 353776 KB
Sun Jan 14 00:00:53 UTC 2018     DEBUG     Obsolete files deleted. JavaMelody disk usage: 353969 KB
Mon Jan 15 00:01:04 UTC 2018     DEBUG     Obsolete files deleted. JavaMelody disk usage: 354177 KB
Tue Jan 16 00:00:13 UTC 2018     DEBUG     Obsolete files deleted. JavaMelody disk usage: 352867 KB
Wed Jan 17 00:00:18 UTC 2018     DEBUG     Obsolete files deleted. JavaMelody disk usage: 352368 KB
Thu Jan 18 00:00:25 UTC 2018     DEBUG     Obsolete files deleted. JavaMelody disk usage: 351745 KB
Fri Jan 19 00:00:30 UTC 2018     DEBUG     Obsolete files deleted. JavaMelody disk usage: 350794 KB
Sat Jan 20 00:00:34 UTC 2018     DEBUG     Obsolete files deleted. JavaMelody disk usage: 349532 KB
Sun Jan 21 00:00:40 UTC 2018     DEBUG     Obsolete files deleted. JavaMelody disk usage: 348246 KB
Mon Jan 22 00:00:48 UTC 2018     DEBUG     Obsolete files deleted. JavaMelody disk usage: 348276 KB
Tue Jan 23 00:00:54 UTC 2018     DEBUG     Obsolete files deleted. JavaMelody disk usage: 348957 KB
Wed Jan 24 00:01:03 UTC 2018     DEBUG     Obsolete files deleted. JavaMelody disk usage: 348933 KB
```

Those logs are outdated so there must be something wrong.

**Comment by fritaly** [comment]
Deleting the JavaMelody temp files on the file-system fixed the issue. I think there was a corruption issue with the data persisted on the disk.
