### ISSUE TITLE
Java Melody issue from version 1.6.5 to 1.7

### ISSUE THREAD

**Issue by SchwarzM90** [javamelody/javamelody#725]
Hi guys,

Java Melody isn't available in JIRA 7.2.6 after upgrading it from 1.6.2 to 1.6.5 or 1.7.

It shows up in the System tab but when I try to access the link it says is dead.

I've disabled it enable it, deleted the .osgi-plugins plugins data, still not accessible.

Any ideas?
Thanks!

**Comment by InfinityGone** [comment]
No ideas, but seeing the same thing after updating both JIRA and Java Melody to 7.7.1 and 1.70.0 from 7.2.2 and 1.62.0 respectively. I've reverted back to 1.62.0.

**Comment by evernat** [comment]
I have not reproduced the issue when using JIRA 7.7.1 and [jira-confluence-javamelody-1.71.0.jar](https://github.com/javamelody/jira-confluence-javamelody/releases/download/1.71.0/jira-confluence-javamelody-1.71.0.jar).

But I have found an issue with auth when using JIRA 7.1.
Can you try the new 1.71.1 version at:
https://github.com/javamelody/jira-confluence-javamelody/releases/tag/1.71.1 ?

**Comment by evernat** [comment]
Any news?

**Comment by evernat** [comment]
No response from the reporter so closing as incomplete.
