### ISSUE TITLE
Can I get graphs for each of the method calls?

### ISSUE THREAD

**Issue by Madhupriyaks** [javamelody/javamelody#730]
Hello,
Thank you. I got the graphs of the complete application as a whole but I need to the specific method calls usage . l need a hierarchy showing various parameters (CPU load, memory usage , threads count) whenever a function is called and returned. I need separate graphs for those . Is it possible to get ?

**Comment by evernat** [comment]
No, it's not possible.
By the way, the number of threads in the jvm are certainly not related to some method calls in your jvm.
