### ISSUE TITLE
Cloudwatch metric upload can't handle more then 20 items without throwing an exception

### ISSUE THREAD

**Issue by marcrelation** [javamelody/javamelody#731]
See screen shot for where the issue is, what happens and a potential fix.

![image](https://user-images.githubusercontent.com/34357776/36604248-2ea1b18c-188b-11e8-8cfa-6c8abe8e3424.png)

**Comment by evernat** [comment]
fixed by d77c169 and ready for the next release (1.72).
Thanks for the issue.
