### ISSUE TITLE
Any wiki page to explain the metrics?

### ISSUE THREAD

**Issue by chengchengpei** [javamelody/javamelody#733]
In fact, I am confused by the metrics got from the monitoring page, e.g. `% System CPU`.

But I got `% System CPU is the CPU usage for the whole system (not just the JVM), between 0 and 100%.` from the release notes. surprised.

**Comment by evernat** [comment]
The "Online help" page included in the monitoring of your server explains: "the cpu percentage used by the whole OS".
The "Online help" is also available in the demo (when the demo is online):
http://javamelody.org/demo/monitoring?resource=help/help.html
http://javamelody.org/demo/monitoring?resource=help/help_fr.html
http://javamelody.org/demo/monitoring?resource=help/help_pt.html
