### ISSUE TITLE
Jenkins 2.89 and JavaMelody NullPointer Exception

### ISSUE THREAD

**Issue by foxrafi** [javamelody/javamelody#735]
Hi,

In Jenkins 2.89 I get many such exceptions:

> 8765: Mar 18, 2018 7:13:09 AM net.bull.javamelody.internal.common.JavaLogger warn
> 8766: WARNING: exception while collecting data: java.lang.NullPointerException
> 8767: java.lang.NullPointerException
> 8768:   at net.bull.javamelody.internal.model.Collector.addJRobinValue(Collector.java:634)
> 8769:   at net.bull.javamelody.internal.model.Collector.collectCounterData(Collector.java:718)
> 8770:   at net.bull.javamelody.internal.model.Collector.collect(Collector.java:356)
> 8771:   at net.bull.javamelody.internal.model.Collector.collectWithoutErrors(Collector.java:324)
> 8772:   at net.bull.javamelody.NodesCollector.collectWithoutErrorsNow(NodesCollector.java:173)
> 8773:   at net.bull.javamelody.NodesCollector.collectWithoutErrors(NodesCollector.java:147)
> 8774:   at net.bull.javamelody.NodesCollector$1.run(NodesCollector.java:91)
> 8775:   at java.util.TimerThread.mainLoop(Timer.java:555)
> 8776:   at java.util.TimerThread.run(Timer.java:505)

Do you know what can be reason of such behavior ?

Thank you,
foxrafi

**Comment by evernat** [comment]
It seems that you don't have any build executors in your Jenkins master or slaves, or they are often not reachable, or they are only on FreeBSD with some "old" openjdk (FreeBSD/openjdk is sometimes a problem to get some informations).
Anyway, this is not a reason to throw NullPointerException and I must fix that [in the Collector class](https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/internal/model/Collector.java#L340) for the next release.

Meanwhile you can disable the monitoring of build executor nodes, by adding the system property `-Djavamelody.nodes-monitoring-disabled=true` (you may do that without restarting Jenkins in the [Jenkins Script console](https://wiki.jenkins.io/display/JENKINS/Jenkins+Script+Console)).

**Comment by evernat** [comment]
fixed by 4894a8a and ready for the next release (1.72).
A new snapshot build of javamelody-core is available at:
https://javamelody.ci.cloudbees.com/job/javamelody/net.bull.javamelody$javamelody-core/

**Comment by foxrafi** [comment]
Ok great, thank you, I will verify that when the new release is available.
