### ISSUE TITLE
Graphics/data unavailable in collector server when one server is not sending data

### ISSUE THREAD

**Issue by blontrock** [javamelody/javamelody#736]
We use a JavaMelody collector server for several applications. When one node is not sending data to the collector server (during maintenance, new deploy, tomcat restart, ...), all the graphics for the application have a gap during that time, even though all the other nodes are sending data to the collector for that same application.

Is it possible to keep displaying the graphics/statistics in the collector even if one (or more) nodes are unreachable/down?

**Comment by evernat** [comment]
I agree that it is better to collect data for the other nodes of an application in the collector server, when one node is down but not all.
This is done by 1a8b48a and ready for the next release (1.72).
A new snapshot build of the collector server is available at:
https://javamelody.ci.cloudbees.com/job/javamelody-collector-server/net.bull.javamelody$javamelody-collector-server/

**Comment by blontrock** [comment]
Thank you very much! We updated to 1.72 and it is now working as intended for us.
