### ISSUE TITLE
Windows Servers Don't Show System Load (% CPU)

### ISSUE THREAD

**Issue by aboe026** [javamelody/javamelody#738]
I have a tomcat server running on windows, and the `/monitoring` URL does not show me the System Load (% CPU) graph. However, when I run the same webapp on Ubuntu with javamelody, the `/monitoring` URL does show the System Load (% CPU) graph.

**Comment by evernat** [comment]
I do not reproduce the issue on windows.
What JDK do you use ? IBM ?
What version do you use ?

By the way, I don't like your photo promoting weapons of war for individuals. You should better go to the march for our lives this weekend.
So closing this issue. Sorry.

**Comment by aboe026** [comment]
We're using the IBM JRE, v7.

And relax, the picture is from a movie I was apart of. I dislike the NRA and support the march just as much as you.

**Comment by evernat** [comment]
ok. IBM JRE is probably not supported for system cpu load and process cpu load. That is ManagementFactory.getOperatingSystemMXBean() is not of type com.sun.management.OperatingSystem or com.sun.management.UnixOperatingSystem or sun.management.OperatingSystemImpl.

**Comment by aboe026** [comment]
Hmm I see. I'll look into seeing what class that is for the IBM JRE/JDK
