### ISSUE TITLE
Spring Boot 2 support

### ISSUE THREAD

**Issue by snicoll** [javamelody/javamelody#741]
the current starter builds against Spring Boot `1.x` (I'd reuse `spring-boot-dependencies` there rather than having a version of Spring Framework that is already managed by Spring Boot).

Have you tried Spring Boot 2? If that doesn't work right now, when are you expecting this to be supported.

I am asking as [adding a reference to this starter](https://github.com/spring-projects/spring-boot/pull/12877) can't really happen if you don't support it.

**Comment by evernat** [comment]
Yes, the spring-boot-starter was a bit tested with spring-boot 2. And in fact, there was a spring-boot PR to make it work: https://github.com/spring-projects/spring-boot/pull/12272

But I will see for spring-boot-dependencies and check that.

**Comment by evernat** [comment]
fixed by https://github.com/javamelody/javamelody/commit/9afe9860eff052ead3f9a9383e320b07fcdf58d0 for the next release (1.73)
