### ISSUE TITLE
CommonsPool2TargetSource release target giving error "Returned object not currently part of this pool" when using with javamelody

### ISSUE THREAD

**Issue by shakunahuja** [javamelody/javamelody#748]
ThreadPoolExecutor execute method create clone of the object to which it refers due to which commons pool api unable to release the thread,And when I comment out only service part of the following regex,it works fine,Please advice

 <bean id="facadeMonitoringAdvisor" class="net.bull.javamelody.MonitoringSpringAdvisor">
		<property name="pointcut">
			<bean class="org.springframework.aop.support.JdkRegexpMethodPointcut">
				 <property name="patterns">
				  <list>
					<value>.*Service.*</value>
					<value>.*Scheduler.*</value>
				  </list>
				</property>
			</bean>
		</property>
	</bean>

**Comment by evernat** [comment]
I have not understood well the issue.
Can you give the source of a simple project using Maven to reproduce the issue?

**Comment by evernat** [comment]
Any news?

**Comment by evernat** [comment]
No response from the reporter, so closing as invalid/incomplete.
