### ISSUE TITLE
how to configure the java source?

### ISSUE THREAD

**Issue by apple987** [javamelody/javamelody#755]
hi! i have installed the javamelody,i see the console for exception message,some exception can be opened in the web console directly but some other exception can not open,when i click the exception code it report the 
Source not found,the demo js as the picture ,here i want to know how to confihure the java source?in order to open the exception in the web console directly!

**Comment by apple987** [comment]
here is the demo

**Comment by apple987** [comment]
here is the demo

**Comment by evernat** [comment]
> here is the demo
Which demo? I do not see any attachment in this issue.
Would you give a screenshot with red circle on the problem?

**Comment by evernat** [comment]
Perhaps it is a problem between the screen and the eyes. And no response from the reporter, so closing as invalid/incomplete.
