### ISSUE TITLE
Spring webflux does not seem to be supported - ServletConext needed

### ISSUE THREAD

**Issue by vogthenn** [javamelody/javamelody#760]
Hi,
using spring-boot 2.0.x I am also using projectreactor/webflux option.  This is not monitorable by javamelody, since I don't have a ServletContext anymore:

`***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method monitoringSessionListener in net.bull.javamelody.JavaMelodyAutoConfiguration required a bean of type 'javax.servlet.ServletContext' that could not be found.
`

**Comment by evernat** [comment]
see also https://stackoverflow.com/questions/51327407/does-javamelody-work-with-spring-webflux

**Comment by evernat** [comment]
This is answered in [stackoverflow](https://stackoverflow.com/questions/51327407/does-javamelody-work-with-spring-webflux). This answer may be improved over time in stackoverflow.
So closing this question here.
