### ISSUE TITLE
vert.x integration

### ISSUE THREAD

**Issue by MeiyappanKannappa** [javamelody/javamelody#761]
Hi Is it possible to integrate Java Melody with Vert.x+Spring Boot App. I have a vert.x+spring boot app, for which i followed the steps of integrating Java Melody with Spring Boot. But it does not work. Because Java Melody needs ServletContext dependency which is not available.

Any help would be much apprciated. Many thanks!

**Comment by evernat** [comment]
Is the following answer relevant to Vert.x like to Webflux?
https://stackoverflow.com/a/51370760/119366

**Comment by MeiyappanKannappa** [comment]
Hi Thank you for your response. But, I hope it will have two servers listening on two port. Which is not possible for me, as we deploy the app in cloud foundry which will enable only 8080 port to be used.

**Comment by evernat** [comment]
You need to have a http port to be able to display monitoring reports one way (standard servlet api) or the other ([embedded server](https://stackoverflow.com/questions/51327407/does-javamelody-work-with-spring-webflux/51370760#51370760)).

"Currently an application on Cloud Foundry is not able to have two ports mapped into its container environment. As part of the new Diego runtime, multiple port mappings has been exposed, but is not currently available through the API. Depending on what you need, you could take a look at Lattice, which uses the Diego runtime." ([ref.](https://stackoverflow.com/questions/32073627/cloudfoundry-application-opening-two-ports))

So I suppose that vert.x is already supported one way or the other. And that it answers your question.

**Comment by zyos-sas** [comment]
@MeiyappanKannappa can you did that?
