### ISSUE TITLE
Monitoring jfrog artifactroy and integrating with grafana with influx db as data source. 

### ISSUE THREAD

**Issue by MohamedNazeer** [javamelody/javamelody#763]
Jfrog running as a docker container.

As mentioned in https://jfrog.com/knowledge-base/how-to-configure-javamelody-in-artifactory-for-monitoring/  i am able to set up the javamelody monitoring. 

But we could not send the java melody metrics to InfluxDB. 
We have configured the javamelody.influxdb-url=http://myhost:8086/write?db=mydb&rp=myretentionpolicy in etc/artifactory.system.properties of docker container.

Can you please look on this issue.

**Comment by MohamedNazeer** [comment]
The jar file of javamelody version was the problem. I have replaced the javamelody jar file version to core 1.73.1 version. Then the issue got resolved thanks. We can close this ticket as well.

**Comment by evernat** [comment]
ok, thanks
