### ISSUE TITLE
Allow to access MBeans metrics with prometheus scraping

### ISSUE THREAD

**Issue by davido** [javamelody/javamelody#767]
[Gerrit Code Review](https://gerrit-review.googlesource.com/admin/repos/gerrit) is using Dropwizard based metrics. In the same time, we also have Javamelody [plugin](https://gerrit-review.googlesource.com/admin/repos/plugins/javamelody) for Gerrit.

Using [metrics-reporter-jmx](https://gerrit-review.googlesource.com/admin/repos/plugins/metrics-reporter-jmx) plugin, we can expose Dropwizard metrics on Javamelody [page](https://imgur.com/a/4ZcJv3a) using:

  http://localhost:8080/monitoring?part=mbeans 

With recently added Javameldoy feature we can scrap the Javamelody metrics from Prometheus using this format URI parameter `format=prometheus`:

  http://localhost:8080/monitoring?format=prometheus

This would produce this result: [1].

However, we can't access Gerrit core internal metrics exposed by Dropwizard registry.

Unless there is another obvious way (that I am missing?) to merge both kind of metrics, how feasible would it be to add the possibility to scrap MBeans metrics in prometheus format, a lá:

  http://localhost:8080/monitoring?format=prometheus&part=mbeans 

Ideally we could also fetch only relevant sub-tree:

```
 JMImplementation 
 com.sun.management 
 java.lang 
 java.nio 
 java.util.logging 
 metrics
```

^^^ Here we would only be interested to fetch metrics sub-tree.

[1] http://paste.openstack.org/show/727866

**Comment by evernat** [comment]
There is currently no way to add MBean values in the Prometheus scraping.

But it's possible to have a http parameter like `/monitoring?format=prometheus&includeLastValue=true`, see https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#last-value-metrics
And I think that it would be possible to add another http parameter for Prometheus such as `/monitoring?format=prometheus&includeMBeans=java.lang,java.nio,metrics,...`. It would give the MBeans values for Prometheus scraping like you want.

The code to change would be here:
https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/internal/web/MonitoringController.java#L234
and there:
https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/internal/web/PrometheusController.java#L207

**Comment by evernat** [comment]
As a follow up, I am wondering how to put mbean attributes in Prometheus values.
Because Prometheus asks for metrics as numbers and a lot of MBeans attributes are often not numbers, in the java.lang domain among others.

For example, can you give the same screenshot as before (https://imgur.com/a/4ZcJv3a) but with open mbeans to see their attributes. And are some or many "caches" metrics of type Strings including units or arrays or just numbers?

**Comment by davido** [comment]
Those are not only strings, e.g: [1]. I think in gerrit code there are number of types for this metrics.

[1] https://imgur.com/a/l3annfZ

**Comment by evernat** [comment]
For information not related to this issue, it is recommended for security to upgrade javamelody-core in the gerrit javamelody plugin and to make a release of this plugin soon.
See https://github.com/javamelody/javamelody/wiki/ReleaseNotes

**Comment by davido** [comment]
Thanks for pointing this out. I will update the plugin later today to new released Javamelody 1.74.

**Comment by evernat** [comment]
After some reading, I think that a generic mbeans to prometheus format would not be really good.

See for example the attached [sample_metrics.txt](https://github.com/javamelody/javamelody/files/2717328/sample_metrics.txt) which is the default result of [prometheus jmx_exporter](https://github.com/prometheus/jmx_exporter). There are gauge/counter/summary types as needed and names and labels adapted for Prometheus. And I do not plan to copy [all that](https://github.com/prometheus/client_java/tree/master/simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot).
In the same way, mbeans values from gerrit would certainly need a custom config for names/labels and values.

So I suggest that you use the [prometheus jmx_exporter](https://github.com/prometheus/jmx_exporter) with a config for gerrit. See [example configs](https://github.com/prometheus/jmx_exporter/tree/master/example_configs). You can integrate the jmx exporter as a [separate http server or with a servlet in your webapp](https://github.com/prometheus/client_java#http).

And this enhancement is certainly won't do here, so closing.

**Comment by evernat** [comment]
As said above, you can't export all MBeans values and the existing export contains many of them.
But if you want other/custom values, you will be able to write a custom JSP using JSP tags, with the next release (1.80).
See [documentation](https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#jsp-tags-for-prometheus).
You can download a snapshot build at:
javamelody.org/downloads/javamelody-core-1.80.0-SNAPSHOT.jar
