### ISSUE TITLE
CounterRequest Memory is not released

### ISSUE THREAD

**Issue by SuZhenYu2** [javamelody/javamelody#769]
![image](https://user-images.githubusercontent.com/17267209/44191609-ce017580-a15e-11e8-8925-90d4fdefbd49.png)

When SQL  String was very huge, it will cause String objects to not release memory ,final lead to memory overflow.

**Comment by evernat** [comment]
or you can use the sql-transform-pattern parameter if it makes sense in your case.

**Comment by evernat** [comment]
Same answer as before.
