### ISSUE TITLE
Quartz instance is created instead of using an existing one

### ISSUE THREAD

**Issue by thackel** [javamelody/javamelody#777]
In my environment the JavaMelody filter is initialized before spring(-boot) initializes its own instance of the Scheduler.
The result is that you have two Schedulers hanging around.

The reason is how the [QuartzAdapter](https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/internal/model/QuartzAdapter.java#L129) is getting the Scheduler.

At this point the DefaultQuartzScheduler is created from the quartz.properties file of the classpath.

My current workaround is to disable the Quartz related functionality in JavaMelody.

**Comment by evernat** [comment]
See https://github.com/javamelody/javamelody/wiki/UserGuide#13-batch-jobs-if-quartz

I suggest to use the javamelody parameter `quartz-default-listener-disabled`.
