### ISSUE TITLE
Javamelody 1.74 JSVC and errno: 13 error: Unable to open directory /proc/self/fd

### ISSUE THREAD

**Issue by sebastienmaillard** [javamelody/javamelody#779]
We recently upgraded our javamelody from 1.53 to 1.74 and under a jsvc (RHEL6) environment, we have an old bug coming back : errno: 13 error: Unable to open directory /proc/self/fd

In JavaInformations.java MBeans access have changed from 

```
try {
	MemoryInformations.getLongFromOperatingSystem(operatingSystem, "getMaxFileDescriptorCount");
} catch (final Error e) {
	// pour issue 16 (using jsvc on ubuntu or debian)
	return -1;
}
```

to 

```
try {
	return MBeansAccessor.getLongFromOperatingSystem("MaxFileDescriptorCount");
} catch (final Error e) {
	// pour issue 16 (using jsvc on ubuntu or debian)
	return -1;
}
```

Problem is, the DefaultMBeanServerInterceptor (sun api) now catch the java.lang.InternalError and rethrow a javax.management.RuntimeErrorException. Such as :

javax.management.RuntimeErrorException: java.lang.InternalError: errno: 13 error: Unable to open directory /proc/self/fd

Don't know if catching Throwable might be a good solution in this case ?

**Comment by evernat** [comment]
It's fixed by 7146d6d and ready for the next release (1.75).
A snapshot build is available at:
https://javamelody.ci.cloudbees.com/job/javamelody/net.bull.javamelody$javamelody-core/
Thanks for the issue.
