### ISSUE TITLE
Java melody collector on clustered server

### ISSUE THREAD

**Issue by leccyril** [javamelody/javamelody#786]
Hi,

I have Wildfly cluster with 4 nodes , 2 servers and 2 jvm (nodes) per server.

When i deploy java melody it will deploy on all nodes....

1. when i add servers on jvm only this JVM knows the configuration (host1:8080/javamelody for example)
host1:8180/javamelody have not the configuration , and all node in host2 too), so when i call via apache and http one time it is ok , other not.

=> is mandatory to use a no cluster server to aggregate all datas and deploy java melody collector? 

![image](https://user-images.githubusercontent.com/3234598/47137547-2e27ab80-d2b7-11e8-871b-6c6f5154d3e6.png)

![image](https://user-images.githubusercontent.com/3234598/47137585-44ce0280-d2b7-11e8-8038-d93639c9edf1.png)

2.  on cluster i add <option value="-Djavamelody.storage-directory=C:\Windows\Tmp\javamelody_8180"/> it works well

then i add in collector server APP1 http://host1:8080/app1,http://host1:8180/app1 to test

i see graph only for one node but don't not which one, same case for http or sql, if time issue don't know from which node it is come from ? (it is ok for system information and threads)

![image](https://user-images.githubusercontent.com/3234598/47137477-f587d200-d2b6-11e8-9141-1d4473fbd162.png)

![image](https://user-images.githubusercontent.com/3234598/47137512-12bca080-d2b7-11e8-88e8-992d13fb51ec.png)

3. now with collector all data are recorded on collector server :

![image](https://user-images.githubusercontent.com/3234598/47137814-ff5e0500-d2b7-11e8-9fdb-452bf070c24e.png)

which way it take informations (if we have to open firewall port ? ) http , jmx , or other protocol and port ?

again thank you for this great light tools usefull ! +100

**Comment by evernat** [comment]
>  is mandatory to use a no cluster server to aggregate all datas and deploy java melody collector?
Yes, the javamelody collector server should be deployed on a single node and not clustered.

> i see graph only for one node but don't not which one, same case for http or sql, if time issue don't know from which node it is come from ?
The graph and http/sql statistics are aggregated for all nodes which you have declared for this application.
So you don't know from which one since they are for all nodes.

> which way it take informations (if we have to open firewall port ? ) http , jmx , or other protocol and port ?
The javamelody collector server calls the monitored instances to pull the data on the http host and port you have declared when adding the application.
