### ISSUE TITLE
Java melody collector servor problem

### ISSUE THREAD

**Issue by leccyril** [javamelody/javamelody#787]
i have 2 problems linked, 

1. i had some servers but i can't remove them, i want know where files are located (aggregate files) to stop server, delete it, and retry from beginning

2. when i want delete or show server data i have this error

_État HTTP 500 – Internal Server Error
Type Rapport d''exception

message An invalid character [32] was present in the Cookie value

description Le serveur a rencontré une erreur interne qui l''a empêché de satisfaire la requête.

exception

java.lang.IllegalArgumentException: An invalid character [32] was present in the Cookie value
	org.apache.tomcat.util.http.Rfc6265CookieProcessor.validateCookieValue(Rfc6265CookieProcessor.java:182)
	org.apache.tomcat.util.http.Rfc6265CookieProcessor.generateHeader(Rfc6265CookieProcessor.java:115)
	org.apache.catalina.connector.Response.generateCookieString(Response.java:974)
	org.apache.catalina.connector.Response.addCookie(Response.java:926)
	org.apache.catalina.connector.ResponseFacade.addCookie(ResponseFacade.java:385)
	net.bull.javamelody.internal.web.HttpCookieManager.addCookie(HttpCookieManager.java:90)
	net.bull.javamelody.internal.web.CollectorController.getApplication(CollectorController.java:600)
	net.bull.javamelody.CollectorServlet.doGet(CollectorServlet.java:89)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
note La trace complète de la cause mère de cette erreur est disponible dans les fichiers journaux de ce serveur._

**Comment by evernat** [comment]
> i had some servers but i can't remove them, i want know where files are located (aggregate files) to stop server, delete it, and retry from beginning

By default, files are stored in the temporary directory of the server. In your case, it's c:\windows\temp\javamelody according to #786

> An invalid character [32] was present in the Cookie value

Yes, in recent Tomcat, space is not allowed in the cookie value. I will fix the issue and meanwhile, do not use an application name including a space, when adding an application in the collector server.

**Comment by evernat** [comment]
The error "An invalid character [32] was present in the Cookie value", when using the collector server in Tomcat, is fixed by 9ac3859 and ready for the next release (1.75).
You can download a snapshot build of the collector server at:
https://javamelody.ci.cloudbees.com/job/javamelody-collector-server/net.bull.javamelody$javamelody-collector-server/
