### ISSUE TITLE
Can  support WasSphere?

### ISSUE THREAD

**Issue by liujiliang2008** [javamelody/javamelody#789]
Can  support WasSphere?
version 8.5

**Comment by evernat** [comment]
Do you mean Websphere?
Yes, javamelody supports Websphere and any server supporting servlet api 2.4 (or Java EE 1.4) or later.
That said, javamelody usage in Websphere is a very small percentage of all javamelody usages.

**Comment by liujiliang2008** [comment]
![image](https://user-images.githubusercontent.com/4192239/48042515-ce893580-e1bc-11e8-90e3-250920b57701.png)

In Tomcat it's works ok.
but in websphere 8.5， 这war start wrong，report more class not found.
like itext.jar  mogodb.jar  xstream.jar

how i can work normal in websphere ?
