### ISSUE TITLE
Push per node metrics

### ISSUE THREAD

**Issue by Puneeth-n** [javamelody/javamelody#791]
How does one push metrics of all the Jenkins nodes to for example InfluxDB.

I can see metrics of Jenkins master and all jenkins nodes. However, I have the feeling that, only Master node's metrics are pushed to InfluxDB.

**Comment by evernat** [comment]
Metrics of master and the aggregated metrics of jenkins nodes are sent to Graphite/InfluxDB/AWS Cloudwatch/Datadog/Prometheus.
But note that if the agent(s) are running on the same host than the master, then the `host` tag in InfluxDB is the same for master and for nodes. And the `application` tag in InfluxDB is `NA` for nodes.
