### ISSUE TITLE
JavaMelody Alfresco plugin does not load

### ISSUE THREAD

**Issue by tomekszy** [javamelody/javamelody#792]
So, basically after compiling and installing Alfresco plugin to alfresco.war file (via apply_amps or alfresco_mmt) nothing happens... I see javamelody jar inside alfresco.war file, as well as other files/directories generated during amp installation, but site <myserver>/alfresco/monitoring does not work (404). No information in logs, and in Module Manager in Admin Console also nothing. My Alfresco Community version is 5.2.0. That's why I have few questions:
1) Is JavaMelody plugin supposed to work in community edition, or only with Alfresco One?
2) Maybe it should be installed in share.war, not alfresco.war?
3) I'm attaching compiled by me amp file. Perhaps something is wrong with compilation?
Than you for any help.

[alfresco-javamelody-addon-1.74.0.zip](https://github.com/javamelody/javamelody/files/2564899/alfresco-javamelody-addon-1.74.0.zip)

**Comment by evernat** [comment]
See https://github.com/javamelody/alfresco-javamelody/issues/2
