### ISSUE TITLE
ENH: allow excluding certain files served

### ISSUE THREAD

**Issue by jason-s** [javamelody/javamelody#793]
My company uses javamelody to track a JIRA instance. When we download .html attachments from JIRA, there is code injected into the .html, apparently by javamelody. This is not ok because we expect attachments to be unmodified; these .html files are different from the JIRA website files.

Could you please add a mechanism to exclude specified URL patterns? In our case it would be (in [git glob syntax](https://git-scm.com/docs/gitignore#_pattern_format))

    https://JIRA_SERVER_NAME/secure/attachment/**

(Please excuse my clumsiness in stating this problem; I'm only an indirect customer here and I don't know or care at all about javamelody, I just don't want my attachments modified.)

**Comment by evernat** [comment]
javamelody is not supposed to inject code into the html, except if the rum-enabled parameter is used.
Can you check if you have used this rum-enabled parameter:
- either in the debugging logs at the bottom of the /monitoring page
- or on the server: in conf/catalina.properties or in bin/setenv.sh for example

If the rum-enabled parameter is not used, can you give a bit of the code injected so that we know what this is about?

**Comment by razvv** [comment]
Hello @evernat,

I think that the RumInjector is enabled by default as I didn't set any other params to javamelody (other than the dir for the logs).

Jason uploaded an HTML file (name _jiratest1.html_) with the following code:

```
<!DOCTYPE html>
<html>
<head></head>
<body>Don't touch my HTML!</body>
</html>
```

When he tried to download the attachment, the HTML file had its contents changed:

```
<!DOCTYPE html>
<html>
<head></head>
<body>Don't touch my HTML!
<script src='../../../monitoring?resource=boomerang.min.js'></script>
<script>BOOMR.init({beacon_url: '../../../monitoring?part=rum', log: null});
BOOMR.addVar('requestName', "/secure/attachment/256844/jiratest1.html GET");
BOOMR.addVar('serverTime', 6);
</script>
</body>
</html>
```

The plugins thinks it's handling a normal page and not an attachment.

**Comment by razvv** [comment]
Hello @evernat,

As I previously stated, I did not set any other configs to the monitoring system, other than the path towards the logs. I grepped the whole directory and didn't find anything.

**Comment by evernat** [comment]
$JAVA_OPTS or in $TOMCAT_OPTS may be set somewhere else than in the server directory.

But let's skip that.
You can't exclude urls from rum but I have just checked that you can exclude some urls from the monitoring and so from rum (and you will no longer have monitoring for that), by using a regexp in a system property. For example:
`-Djavamelody.url-exclude-pattern=.*html`
You need to restart the server after that.
And you may see a system property with rum-enabled while doing that.

**Comment by razvv** [comment]
Thank you for the definition of the parameter and I'll try it out when I get the chance. By 'grepping the whole directory', I meant the whole JIRA_INSTALL folder and not only the JIRA_INSTALL/bin one.
