### ISSUE TITLE
javamelody show 0 jdbc active connections.

### ISSUE THREAD

**Issue by annakurandacelltick** [javamelody/javamelody#796]
### javamelody show 0 jdbc active connections, no monitor for jdbc , jpa queries.
No data about jpa , jdbc queries
My env :spring mvc 4.3.10 , used spring aop  (not use spring boot)
Tomcat 8
java 8

*When try @ImportResource("classpath:net/bull/javamelody/monitoring-spring.xml")   failed on proxy issue
Tried all possible solutions found in internet, still not work
Please help.

Thanks

**Comment by evernat** [comment]
Please give the source of a simple project to reproduce the issue.

**Comment by annakurandacelltick** [comment]
**web.xml conf.**
 <context-param>
        <param-name>contextConfigLocation</param-name>
        <param-value>
            classpath:net/bull/javamelody/monitoring-spring.xml
            /WEB-INF/applicationContext.xml
        </param-value>
    </context-param>


    <filter>
        <filter-name>javamelody</filter-name>
        <filter-class>net.bull.javamelody.MonitoringFilter</filter-class>


    </filter>
    <filter-mapping>
        <filter-name>javamelody</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>
    <listener>
        <listener-class>net.bull.javamelody.SessionListener</listener-class>
    </listener>

No active  jdbc connection 
As Solution tried ImportResource (as shown before) 

@Configuration
@PropertySource("file:...")
@ImportResource("classpath:net/bull/javamelody/monitoring-spring.xml")
public class AppConfig {
}
Filed on $proxy58 issue ,on tomcat start

**Comment by evernat** [comment]
As said before, the source of a simple project to reproduce the issue.
But you are giving only a small extract.
Closing.

**Comment by annakurandacelltick** [comment]
I cant reproduce it in small project.
