### ISSUE TITLE
Enhancement: JIRA/Confluence Version Dark Theme

### ISSUE THREAD

**Issue by jbrass** [javamelody/javamelody#797]
Is it possible to enable the "Dark theme" for the JIRA/Confluence version of JavaMelody? Perhaps it could be enabled by passing in a flag like the RUM. Any pointers on where to look in the code if there were to take a stab at a PR?

**Comment by evernat** [comment]
You can see the source of the dark theme for the javamelody reports at:
https://github.com/javamelody/javamelody-dark-theme/tree/master/src/main/resources/net/bull/javamelody/resource
As you can see, it's just simple themedMonitoring.css and/or themedMonitoring.js files. So you may easily improve the theme in a PR or create a JIRA/Confluence theme perhaps.

And you can download the 1.0 release of the dark theme at:
https://repo1.maven.org/maven2/net/bull/javamelody/javamelody-dark-theme/1.0/javamelody-dark-theme-1.0.jar
(it's just a zip file containing the css and js files)

To use it, make sure you are using javamelody 1.74.0 or later, then make the theme available in the classpath of the webapp. For example:
- copy javamelody-dark-theme-1.0.jar in confluence/WEB-INF/lib for Confluence
- or copy javamelody-dark-theme-1.0.jar in atlassian-jira/WEB-INF/lib for JIRA
And restart the server.
