### ISSUE TITLE
[Spring monitoring] split methods according to input parameter value

### ISSUE THREAD

**Issue by NicolasFelix** [javamelody/javamelody#799]
Hi everybody,
my question is related to **_Spring monitoring_**.

It works as expected on my product. But in a specific use case, I wonder if I can split some method calls according to one of its parameter.

My method looks like this:
`public MyService.run(String data) {
}`

Javamelody displays these method statistics as followed : 
`MyService.run`

I am looking for something like 
`MyService.run(data1)`
`MyService.run(data2)`

**spring-transform-pattern** provides an opposite feature (if I clearly understand),
please let me know if you think about a way to implement this.

_Note_: I am aware this feature can multiply **rrd** files, but the service I want to deeper monitor has a limited (< 50) data values.

Thanks for any help
Nicolas

**Comment by evernat** [comment]
You can't by configuration, sorry.
But you may achieve almost what you said by coding something like this:
```java
class MyService {
public run(String data) {
   if (data != null) {
      switch (data) {
         // "myService" and not "this" to be intercepted
         case data1: myService.run1(data); break;
         case data2: myService.run2(data); break;
         ...
         default: throw new IllegalArgumentException(data);
      }
   }
}
public run1(String data) {
   ...
}
public run2(String data) {
   ...
}
}
```
or like this:
```java
class MyService {
public run(String data) {
   if (data != null) {
      switch (data) {
         case data1: myService1.run(data); break;
         case data2: myService2.run(data); break;
         ...
         default: throw new IllegalArgumentException(data);
      }
   }
}
}
class MyService1 {
public run(String data) {
}
}
class MyService2 {
public run(String data) {
}
}
```

**Comment by evernat** [comment]
or with less cases and an interface:
```java
class MyService {
private static class MyRunnable implements Runnable {
   private final String data;
   MyRunnable(String data) {
      this.data = data;
   }
   @Override
   public void run() {
      // your code
   }
}

public run(String data) {
   Runnable runnable = new MyRunnable(data);
   runnable = net.bull.javamelody.MonitoringProxy.createProxy(runnable, "MyService" + data);
   runnable.run();
}
}
```

**Comment by NicolasFelix** [comment]
Thanks @evernat  for your answer.
Your latest answer can enable my wish, I will test it in our next product version.

Thx again.
Nicolas
