### ISSUE TITLE
Error Starting Tomee Plume 7.0.3, 7.1.0 with javamelody 1.68.0 through 1.75.0

### ISSUE THREAD

**Issue by jdesmet** [javamelody/javamelody#802]
This gives me following exception

```
org.apache.openejb.OpenEJBException: Creating application failed: [xxxx redacted xxxx]: class net.bull.javamelody.internal.common.LogbackLogger cannot access its superinterface net.bull.javamelody.JavaMelodyLogger
	at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:1042)
	at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:718)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1298)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1124)
        [xxx shortened xxx]
Caused by: java.lang.IllegalAccessError: class net.bull.javamelody.internal.common.LogbackLogger cannot access its superinterface net.bull.javamelody.JavaMelodyLogger
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2277)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:811)
        [xxx shortened xxx]
```

Important part is that stating:

>  `net.bull.javamelody.internal.common.LogbackLogger` cannot access its 
>  superinterface `net.bull.javamelody.JavaMelodyLogger`

**Comment by jdesmet** [comment]
Error remains with TomEE Plume 7.1.0

**Comment by evernat** [comment]
I have removed from javamelody the automatic monitoring of `@Asynchronous` methods, because it was working in some application server(s) but it does not seem to be valid according to CDI spec (and according to TomEE plume). Note that you may continue to monitor CDI/EJB methods with a javamelody annotation or by configuration, see https://github.com/javamelody/javamelody/wiki/UserGuide#8-business-facades-ejb-jarxml-file-if-ejb3-or-cdi

The issue is fixed by 406639b and ready for the next release 1.76.

Meanwhile you may workaround the issue by adding a file `WEB-INF\exclusions.list` in your webapp with the following content:
```
# inherit from defaults, this is important to keep it
default-list
# ignore javamelody interceptors
javamelody-core-1.75.0.jar
```

**Comment by james-r-smith** [comment]
@evernat, when will the next release be coming? Would love to not have this workaround. Hoping it will be soon! Thanks!

**Comment by james-r-smith** [comment]
Thanks for the release, @evernat!

**Comment by evernat** [comment]
you are welcome

**Comment by fdzaebel** [comment]
@evernat Also from me a big THANK YOU for the release. But...could you please give me a hint? I am a new user of your software and want to use it with eclipse and TomEE. Now with release 1.76.0 TomEE is starting well but I am not able to access "http://context/monitoring". I always get a HTTP404.

I am also using jsf/bootsfaces. I don't know if this maybe causing a problem? I have no idea where to search for a solution.

THANK YOU very much for your help!

**Comment by evernat** [comment]
Let's say that your application is available at `http://localhost:8080/yourwebapp` (where `yourwebapp` is the context of the application on your server).
Then the javamelody report should be available at `http://localhost:8080/yourwebapp/monitoring`.
If that's not the case, be sure to add the javamelody servlet filter near the top of the 'WEB-INF/web.xml' file in your webapp (that is before other servlet filters which may not chain to other filters after them).
