### ISSUE TITLE
Your project javamelody/javamelody is using buggy third-party libraries [WARNING]

### ISSUE THREAD

**Issue by FDU-SE-LAB** [javamelody/javamelody#803]
Hi, there!
We are a research team working on third-party library analysis. We have found that some widely-used third-party libraries in your project have major/critical bugs, which will degrade the quality of your project. We highly recommend you to update those libraries to new versions.    
We have attached the buggy third-party libraries and corresponding jira issue links below for you to have more detailed information.
  1  org.apache.logging.log4j log4j-core (javamelody-test-webapp/pom.xml)
  version: 2.5

  Jira issues:
  ThreadLocal leak [AsyncLogger$Info] on Tomcat when using AsyncLoggerContextSelector
  affectsVersions:2.4;2.4.1;2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1172?filter=allopenissues
  Memory leak from first loaded web app when log4j jars are in Tomcat's lib folder
  affectsVersions:2.4.1;2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1176?filter=allopenissues
  Initializing Logger during JVM shutdown fails with FATAL error
  affectsVersions:2.4;2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1222?filter=allopenissues
  Message instances are simply serialized. They mustn't.
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1226?filter=allopenissues
  NullPointerException in MapLookup.lookup is the event is null
  affectsVersions:2.4;2.4.1;2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1227?filter=allopenissues
  Don't concatenate SYSLOG Messages
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1230?filter=allopenissues
  org.apache.logging.log4j.core.appender.routing.IdlePurgePolicy not working correctly
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1235?filter=allopenissues
  org.apache.logging.log4j.core.net.TcpSocketManager and other classes does not report internal exceptions to the status logger
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1238?filter=allopenissues
  Faulty placeholder substitution in config xml
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1243?filter=allopenissues
  PatternLayout Nano timestamp does not work
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1248?filter=allopenissues
  Update Jackson from 2.6.4 to 2.7.0
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1249?filter=allopenissues
  Update LMAX Disruptor from 3.3.2 to 3.3.4
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1253?filter=allopenissues
  TlsSyslogFrame calculates message length incorrectly
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1260?filter=allopenissues
  Log4jServletContextListener unnecessary exception
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1262?filter=allopenissues
  log4j2.properties: monitorInterval has no effect
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1263?filter=allopenissues
  AsyncLogger should use thread-local translator by default
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1269?filter=allopenissues
  Logger methods taking Supplier<?> parameters should check if supplied value is Message
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1280?filter=allopenissues
  Change flow logging text from "entry' to "Enter" and "exit" to "Exit"
  affectsVersions:2.0;2.0.1;2.0.2;2.1;2.2;2.3;2.4;2.4.1;2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1289?filter=allopenissues
  Update Kafka client from 0.9.0.0 to 0.9.0.1
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1294?filter=allopenissues
  Remove serializability from classes that don't need it
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1300?filter=allopenissues
  Configuration file error does not show cause exception
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1309?filter=allopenissues
  JndiLookup mindlessly casts to String and should use String.valueOf()
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1310?filter=allopenissues
  SocketAppender will lose several events after re-connection to server
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1311?filter=allopenissues
  <Property name="" value="" /> not working
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1313?filter=allopenissues
  LoggerContext#getLogger causes heavy GC overhead
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1318?filter=allopenissues
  Custom plugins are not loaded; URL protocol vfs is not supported
  affectsVersions:2.5;2.6.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1320?filter=allopenissues
  LoggerFactory in 1.2 API module is not compatible with 1.2
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1336?filter=allopenissues
  AsyncLogger should not call instanceof TimestampMessage in hot path
  affectsVersions:2.0.1;2.0.2;2.1;2.2;2.3;2.4;2.4.1;2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1339?filter=allopenissues
  includeLocation doesn't work when using PropertiesConfiguration
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1363?filter=allopenissues
  Status logger drops/ignores exception
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1368?filter=allopenissues
  "xz" compression results in plaintext; uncompressed files.
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1369?filter=allopenissues
  Update Jackson 2.7.3 to 2.7.4
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1380?filter=allopenissues
  Memory leak related to shutdown hook
  affectsVersions:2.5
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1387?filter=allopenissues
  NPE in Level.isInRange
  affectsVersions:2.4;2.4.1;2.5;2.6;2.6.1;2.6.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1559?filter=allopenissues
  Some LogEvents may not carry a Throwable (Use Message.getThrowable() in log(Message) methods)
  affectsVersions:2.5;2.6;2.7
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1676?filter=allopenissues
  Configurations with multiple root loggers should fail loudly
  affectsVersions:2.0;2.1;2.2;2.3;2.4;2.5;2.6;2.7;2.8
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1954?filter=allopenissues
  Configuration builder classes should look for "onMismatch"; not "onMisMatch".
  affectsVersions:2.4;2.4.1;2.5;2.6;2.6.1;2.6.2;2.7;2.8;2.8.1;2.8.2;2.9.0;2.10.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2219?filter=allopenissues

  2  org.apache.logging.log4j log4j-core (javamelody-core/pom.xml)
  version: 2.8.2

  Jira issues:
  Update JavaMail from 1.5.5 to 1.5.6
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1872?filter=allopenissues
  Unreliable checking for runtime dependencies
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1876?filter=allopenissues
  documentation error regarding additivity default value
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1885?filter=allopenissues
  Log4j throws a java.nio.charset.UnsupportedCharsetException: cp65001
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1888?filter=allopenissues
  Nullpointer with DirectWriteRolloverStrategy
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1916?filter=allopenissues
  EOFException with FormattedMessage
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1929?filter=allopenissues
  JMS Appender does not know how to recover from a broken connection
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1934?filter=allopenissues
  RFC5424 Layout ignores event prefix
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1943?filter=allopenissues
  Trim levels read from properties file to remove trailing spaces
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1948?filter=allopenissues
  JndiManager is not released when the JmsAppender builder catches an exception trying to build itself
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1953?filter=allopenissues
  Dynamic reconfiguration does not work for filePattern of RollingFile
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1964?filter=allopenissues
  GelfLayout/SocketAppender does document "includeNullDelimiter" to append the frame delimiter null byte when using TCP
  affectsVersions:2.8;2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1968?filter=allopenissues
  Log4j-config.xsd only allows one AppenderRef element for each Logger element
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1982?filter=allopenissues
  Fix default buffer size to match documentation (from 8102 to 8192 a.k.a. 8KB)
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1985?filter=allopenissues
  Log4J JUL Bridge and RMI Security Manager causes access denied ("java.util.logging.LoggingPermission" "control")
  affectsVersions:2.7;2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-1987?filter=allopenissues
  DefaultConfigurationBuilder.writeXmlAttributes does not handle null attribute values
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2002?filter=allopenissues
  SslSocketManager does not apply SSLContext on TCP reconnect
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2013?filter=allopenissues
  LoggerNameLevelRewritePolicy documentation is wrong; example is broken
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2018?filter=allopenissues
  Messages appear out of order in log file (was: Log4j2 log file not reflecting application log function calls)
  affectsVersions:2.8.2;2.9.0;2.9.1
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2031?filter=allopenissues
  Curly braces in parameters are treated as placeholders
  affectsVersions:2.8.2;2.9.0;2.10.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2032?filter=allopenissues
  AbstactDatabase appender issue with AsyncLogger
  affectsVersions:2.8.1;2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2060?filter=allopenissues
  Log4j1XmlLayout does not provide the entire stack trace; it is missing the caused by information
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2070?filter=allopenissues
  ReusableParametrizedMessages keeps references to objects beyond their expected lifetime
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2201?filter=allopenissues
  Configuration builder classes should look for "onMismatch"; not "onMisMatch".
  affectsVersions:2.4;2.4.1;2.5;2.6;2.6.1;2.6.2;2.7;2.8;2.8.1;2.8.2;2.9.0;2.10.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2219?filter=allopenissues
  Log4j2 2.8.2 JMX unregister NullPointerException
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2304?filter=allopenissues
  fix the CacheEntry map in ThrowableProxy#toExtendedStackTrace to be put and gotten with same key
  affectsVersions:2.6.2;2.7;2.8;2.8.1;2.8.2;2.9.0;2.9.1;2.10.0;2.11.0
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2389?filter=allopenissues
  Handle some unchecked exceptions while loading plugins
  affectsVersions:2.8.2
  https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2422?filter=allopenissues

  3  ch.qos.logback logback-classic (javamelody-core/pom.xml)
  version: 1.2.3

  Jira issues:
  missing log files and log entries when using SizeAndTimeBasedRollingPolicy 
  affectsVersions:1.2.3
  https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-1361?filter=allopenissues

  4  ch.qos.logback logback-classic (javamelody-test-webapp/pom.xml)
  version: 0.9.19

  Jira issues:
  SyslogAppender quits after a while
  affectsVersions:0.9.13;0.9.14;0.9.15;0.9.16;0.9.17;0.9.18;0.9.19
  https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-511?filter=allopenissues

Sincerely~
FDU Software Engineering Lab
Jan 7th,2019

**Comment by evernat** [comment]
In the javamelody case, that's wrong.

2:
In fact, the Log4J dependency in javamelody is optional, as you can see in the [pom.xml of javamelody-core](https://github.com/javamelody/javamelody/blob/master/javamelody-core/pom.xml#L107).
Because that dependency is optional and by definition not transitive, javamelody does not use that Log4J dependency v2.8.2 and javamelody will never use that Log4J dependency v2.8.2 and it will only use a Log4J dependency vX, if the application in which javamelody is included define a Log4J dependency vX.

So javamelody does not use Log4J v2.8.2 and there is absolutely no particular reason to update that.

3:
Same answer for Logback.

1 and 4:
As said in the name of the module, that's a webapp for testing purpose only. We may want to test with whatever log4j versions, in particular if those versions are buggy.

So closing as invalid.
