### ISSUE TITLE
metrics info has error number

### ISSUE THREAD

**Issue by JKeyZ** [javamelody/javamelody#806]
help, metrics info has error number.

javamelody version: 1.74.0
jdk version: 1.8.0_102
Application container: spring boot 1.4.7

'#' HELP javamelody_last_value_http_mean_times javamelody value per minute
'#' TYPE javamelody_last_value_http_mean_times gauge
javamelody_last_value_http_mean_times �
'#' HELP javamelody_last_value_http_system_errors javamelody value per minute
'#' TYPE javamelody_last_value_http_system_errors gauge
javamelody_last_value_http_system_errors �

**Comment by evernat** [comment]
Some characters in that result can't come from javamelody, for example `'#'` and others.
To check that and to exclude github changes, can you give the same results in a text file attached to the issue?
And can you give the source of a simple project to reproduce the issue?

**Comment by JKeyZ** [comment]
'#' is markdown symbol, so I added quotation mark. 
I found that the data value from the indicator is NAN.

` public double getLastValue() throws IOException {
        try {
            RrdDb rrdDb = this.rrdPool.requestRrdDb(this.rrdFileName);

            double var2;
            try {
                var2 = rrdDb.getLastDatasourceValue(this.getDataSourceName());    <- var2 is NaN
            } finally {
                this.rrdPool.release(rrdDb);
            }

            return var2;
        } catch (RrdException var8) {
            throw createIOException(var8);
        }
    }`

**Comment by evernat** [comment]
Ok, DecimalFormat (with US symbols) prints "NaN" for Double.NaN in a `lastValue` on Java 9 and later, but it prints \uFFFD (�) on Java 8 and before.

It is fixed by 8f92d6e to always print "NaN" and ready for the next release (1.76).
Meanwhile a snapshot build is available at:
http://javamelody.org/downloads/javamelody-core-1.76.0-SNAPSHOT.jar

**Comment by JKeyZ** [comment]
thank u for help. we will upgrade when release
