### ISSUE TITLE
the option for X-Frame-Options enable/disable in HtmlController.

### ISSUE THREAD

**Issue by xyzlast** [javamelody/javamelody#808]
I develop multiple instances for HA using JavaMelody. 
I make view page with iframe into admin site. But X-Frame-Options is always **SAMEORIGIN** in HtmlController. 
So, I suggest servlet init parameter for enable/disable X-Frame-Options. 
How do you think this? 

```java
	public static BufferedWriter getWriter(HttpServletResponse httpResponse) throws IOException {
		httpResponse.setContentType("text/html; charset=UTF-8");
                //enable/disable using servlet init parameter or system parameters.
		httpResponse.setHeader("X-Frame-Options", "SAMEORIGIN");
		return new BufferedWriter(new OutputStreamWriter(httpResponse.getOutputStream(), "UTF-8"));
	}
```

**Comment by evernat** [comment]
I would be prefer to add a system property and not a servlet init parameter.
The system property would allow to specify what X-Frame-Options you want among:
- X-Frame-Options: DENY
- X-Frame-Options: SAMEORIGIN
- X-Frame-Options: ALLOW-FROM https://example.com/
- X-Frame-Options: ALLOWALL
The default value is `SAMEORIGIN`. You may use `ALLOW-FROM https://example.com/` for your admin site. If you use `ALLOWALL`, then it will in fact remove X-Frame-Options to disable it.
But for security, I recommend not to disable X-Frame-Options.
Would it be ok for you?

**Comment by xyzlast** [comment]
Thanks @evernat.
But In HtmlController, this option is constant. so this is not changed. 
Do you have any plan to add system property for X-Frame-Options? Or already have this options?
I don't find it. (https://github.com/javamelody/javamelody/wiki/Parameters)

**Comment by evernat** [comment]
The plan is to add a system property (and perhaps also as a servlet init parameter). It does not exist yet.

**Comment by xyzlast** [comment]
Thanks @evernat.
I have solved another **HtmlController** implement now. 
I will close this issue when you add plan for this. 
Are you ok?

**Comment by evernat** [comment]
done with 2e593b7 and ready for the next release (1.77).

You can use a system property like `"-Djavamelody.x-frame-options=ALLOW-FROM https://example.com/"` (using double-quotes) or a servlet context parameter in web.xml like
```xml
<context-param>
 	<param-name>javamelody.x-frame-options</param-name>
 	<param-value>ALLOW-FROM https://example.com/</param-value>
</context-param>
```
or in init parameter of the filter.
See https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters

**Comment by xyzlast** [comment]
@evernat  Thanks for your working. That's great. I've expected next version.
