### ISSUE TITLE
AdoptOpenJDK for Javamelody

### ISSUE THREAD

**Issue by GhoshSidd** [javamelody/javamelody#809]
Hello,

I had a couple of queries which are mentioned below:

As per wiki the following jdk versions are compatible with javamelody:
"Java version required for execution: 1.6 or later (JDK or JRE or JRockit from Oracle or J9 from IBM)"

1) I wanted to confirm and understand , if AdoptOpenJDK (https://adoptopenjdk.net/) can be used as an free alternative version of JDK for javamelody ? and,

 2) Please advise , if there are any nuances that comes with using AdoptOpenJDK with Javamelody instead of regular JDK from Oracle ?

Thank you.

**Comment by evernat** [comment]
1. Yes, OpenJDK and AdoptOpenJDK can be used. After tests, it works fine. Given that AdoptOpenJDK will be more and more used, issues which may be reported with AdoptOpenJDK will be fixed.

2. There are no nuances. AdoptOpenJDK works like Oracle JDK from javamelody points of view.

**Comment by GhoshSidd** [comment]
Thank you evernat
