### ISSUE TITLE
Monitoring page cann't be seen on remote server

### ISSUE THREAD

**Issue by longnguyen2306** [javamelody/javamelody#811]
I fellow this tutorial https://github.com/javamelody/javamelody/wiki/SpringBootStarter and can see the monitoring page on localhost. However deploying the war file on remote tom cat server results a 404 Error. My tomcat is behind a proxy apache2.

Following logs:

```
main] [INFO ] support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'net.bull.javamelody.JavaMelodyAutoConfiguration' of type [net.bull.javamelody.JavaMelodyAutoConfiguration$$EnhancerBySpringCGLIB$$2755ab03] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[main] [INFO ] support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'monitoringSpringAdvisor' of type [net.bull.javamelody.MonitoringSpringAdvisor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[main] [INFO ] support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'monitoringSpringServiceAdvisor' of type [net.bull.javamelody.MonitoringSpringAdvisor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[main] [INFO ] support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'monitoringSpringControllerAdvisor' of type [net.bull.javamelody.MonitoringSpringAdvisor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[main] [INFO ] support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'monitoringSpringRestControllerAdvisor' of type [net.bull.javamelody.MonitoringSpringAdvisor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[main] [INFO ] support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'monitoringSpringAsyncAdvisor' of type [net.bull.javamelody.MonitoringSpringAdvisor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[main] [INFO ] support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$d1bba25b] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```

The parameters however can be found in /tmp/javamelody so it means that java melody must be running.

**Comment by evernat** [comment]
First, remember that if your webapp is available at http://localhost:8080/mywebapp then the monitoring page is at http://localhost:8080/mywebapp/monitoring
So, can you see the monitoring page if you deploy the same war file on localhost without proxy?
Now can you see the webapp's home page by accessing the tomcat server directly without passing by the apache proxy?
And can you see the monitoring page on the remote server by accessing the tomcat server directly without passing by the apache proxy?
And can you see the monitoring page on the remote server by accessing the apache proxy?

**Comment by evernat** [comment]
To clear it up, I mean:
First, remember that if your webapp is available at http://localhost:8080/mywebapp then the monitoring page is at http://localhost:8080/mywebapp/monitoring
So, can you see the monitoring page if you deploy the same war file on localhost without proxy?
Now can you see the webapp's home page by accessing the remote tomcat server directly without passing by the apache proxy?
And can you see the monitoring page on the remote server by accessing the remote tomcat server directly without passing by the apache proxy?
And can you see the monitoring page on the remote server by accessing the remote apache proxy?

**Comment by evernat** [comment]
any news?

**Comment by longnguyen2306** [comment]
Hi hello,

> First, remember that if your webapp is available at http://localhost:8080/mywebapp then the monitoring page is at http://localhost:8080/mywebapp/monitoring

That is true for my case, the monitoring is showing beautiful on localhost. 

> Now can you see the webapp's home page by accessing the remote tomcat server directly without passing by the apache proxy?

I also can access the monitoring page without Apache2 on production server

> And can you see the monitoring page on the remote server by accessing the remote apache proxy?

sadly no and that is my problem

I'm sorry for answering so late.

**Comment by evernat** [comment]
Just to be sure, when using the Apache proxy you have access to your application at http://yourserver/ and you don't have access to the monitoring at http://yourserver/monitoring ?

If you can access the monitoring page on your remote tomcat server without passing by the Apache proxy and if you can't access when passing by the Apache proxy, then I suppose it can only be an issue in your Apache proxy configuration.

For example, access to the /monitoring url may have been forbidden by an Apache proxy administrator if you have not secured the access to /monitoring.
If you don't find the issue, you may copy your Apache configuration here (without sensitive information), and someone may find the issue.

**Comment by longnguyen2306** [comment]
Following is the the log of <code>JavaMelody</code> in <code>Catalina.out</code>

<code>javamelody - remoteAddr = 127.0.0.1, forwardedFor = 141.7.***.**, request = //monitoring GET: 197 ms, erreur, 0 Ko</code>

So javamelody should work very well. 

And this is my Apache2 setting. The proxy works very well for Jenkins and Springboot. The monitoring page should also be reached by www.domains-name.de/homepage/monitoring, but it doesn't (404 error)

<code>
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        ServerName long-nguyen.de
        SSLCertificateFile /etc/letsencrypt/live/******-******.de-0001/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/******-*****.de-0001/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf
        <Directory /var/lib/tomcat8/webapps/>
                AllowOverride All
                Require all granted
                Options Indexes FollowSymLinks
        </Directory>
        ProxyPass /homepage http://localhost:8080/homepage/
        ProxyPassReverse /homepage http://localhost:8080/homepage/
        ProxyPass /jenkins http://localhost:9090/jenkins
        ProxyPassReverse /jenkins http://localhost:9090/jenkins
        <Location "/webapps">
            Order deny,allow
            Allow from all
        </Location>
</VirtualHost>
</IfModule>        
</code>

**Comment by longnguyen2306** [comment]
Hi, after digging the logging file I found the following error:

<code>[http-nio-127.0.0.1-8080-exec-45] [WARN ] servlet.PageNotFound - No mapping for GET /homepage//monitoring</code>

Notice the <code>/homepage//monitoring</code>, that double slashes caused the 404 error. It seems like I added one slash too many in the proxy setting file. 

Problem solved. Thank you.
