### ISSUE TITLE
export errors data to prometheus

### ISSUE THREAD

**Issue by tek100** [javamelody/javamelody#813]
Hi!
When i get monitoring information from url /monitoring?format=prometheus  in my app, i don't see errors 500's and others errors. Can i send errors statistics to prometheus from Javamelody?

**Comment by evernat** [comment]
Using javamelody 1.76.0, I have got the attached sample [monitoring_prometheus.txt](https://github.com/javamelody/javamelody/files/2871302/monitoring_prometheus.txt) which contains the following extracts:
```
# HELP javamelody_http_hits_count javamelody counter
# TYPE javamelody_http_hits_count counter
javamelody_http_hits_count 5
# HELP javamelody_http_errors_count javamelody counter
# TYPE javamelody_http_errors_count counter
javamelody_http_errors_count 2
# HELP javamelody_http_duration_millis javamelody counter
# TYPE javamelody_http_duration_millis counter
javamelody_http_duration_millis 183
```
...
```
# HELP javamelody_error_hits_count javamelody counter
# TYPE javamelody_error_hits_count counter
javamelody_error_hits_count 2
# HELP javamelody_error_duration_millis javamelody counter
# TYPE javamelody_error_duration_millis counter
javamelody_error_duration_millis 0
# HELP javamelody_log_hits_count javamelody counter
# TYPE javamelody_log_hits_count counter
javamelody_log_hits_count 5
```

There are statistics about errors and logs. There are no details about each http request or about each error. Don't you have the same?

**Comment by tek100** [comment]
Yes i have the same statistics . I asked about detail statistics of errors and now understand, that they can't be sent in prometheus.
[https://snag.gy/ZGKxzh.jpg](image)
