### ISSUE TITLE
VM Crash when MBean Button pressed

### ISSUE THREAD

**Issue by chhex** [javamelody/javamelody#814]
JVM crashes when Javamelody MBean Button is pressed. See the two pid*.log files attachted.

We are running with the following Enviroment: 
`

Betriebssystem: | Linux, 3.10.0-957.1.3.el7.x86_64 , amd64/64 (4 Kerne)
-- | --
Java: | Java(TM) SE Runtime Environment, 1.8.0_191-b12
JVM: | Java HotSpot(TM) 64-Bit Server VM, 25.191-b12, mixed mode
Prozess-ID: | 21493
Server: | Apache Tomcat/8.5.6
Webapp Kontext: |  
Start: | 14.02.19 10:39
JVM arguments: | -XX:+UseG1GC-Xms128M-Xmx6G-Djava.awt.headless=true-Djavamelody.storage-directory=/var/opt/apg-jadas-service-CHTI211
Mean age of http sessions (min): | 40
Tomcat "http-nio-30031": | Busy threads = 5 / 350      Bytes received = 733.204.348Bytes sent = 4.435.627.234Request count = 193.318 Error count = 1 Sum of processing times (ms) = 7.082.443 Max processing time (ms) = 269.707
Speicher: | Non heap memory = 180 Mb (Perm Gen, Code Cache),Loaded classes = 18,156,Garbage collection time = 35,977 ms,Process cpu time = 1,792,130 ms,Committed virtual memory = 10,217 Mb,Free physical memory = 1,536 Mb,Total physical memory = 16,046 Mb,Free swap space = 10,091 Mb,Total swap space = 10,239 Mb

`

Java Melody Version 1.55.0

**Comment by chhex** [comment]
[hs_err_pid19614.log](https://github.com/javamelody/javamelody/files/2864592/hs_err_pid19614.log)
[hs_err_pid25219.log](https://github.com/javamelody/javamelody/files/2864594/hs_err_pid25219.log)

**Comment by evernat** [comment]
Your javamelody version is very old (January 2015), can you test after upgrading? You should really upgrade javamelody anyway.
Your tomcat version is old also (October 2016), can you test after upgrading?

**Comment by chhex** [comment]
@evernat Thanks for your feedback. I updated JavaMelody to the newest version.  We still had the VM crashes. But we believe now it was coincidence and the the Jackson JSON libraries triggering the crashes. We have removed all our Jackson dependencies and haven't had a crash since.  So i am closing the issue.  Thanks for the terrific tool!
