### ISSUE TITLE
spring beans proxied twice

### ISSUE THREAD

**Issue by ZhangChaoWN** [javamelody/javamelody#817]
In my application, each spring beans proxied twice, I suppose the reason is our application explictly configured a bean with class  DefaultAdvisorAutoProxyCreator, but spring-boot-autoconfigure will create a bean with class AnnotationAwareAspectJAutoProxyCreator. both two proxy creator would create proxies for AOP auto prox.

I'm using spring-boot 1, so spring-boot-starter-javamelody is not suitable for my application.

the doc in https://github.com/javamelody/javamelody/wiki/SpringBootStarter#or-integration-without-the-spring-boot-starter told me to copy paste example from https://github.com/javamelody/javamelody/blob/without-spring-boot-starter/javamelody-for-spring-boot/src/main/java/hello/JavaMelodyConfiguration.java

**Comment by evernat** [comment]
In this case, remove the `defaultAdvisorAutoProxyCreator` method from the `JavaMelodyConfiguration` you have copied.
