### ISSUE TITLE
follwing guide to copy paste configuration may cause problem

### ISSUE THREAD

**Issue by ZhangChaoWN** [javamelody/javamelody#818]
As described in https://github.com/javamelody/javamelody/issues/817 , copy paste configuration following the guide https://github.com/javamelody/javamelody/wiki/SpringBootStarter#or-integration-without-the-spring-boot-starter may cause problem. people can remove defaultAdvisorAutoProxyCreator from `JavaMelodyConfiguration` to avoid the problem, but they will waste some time before they find out the solution.

Maybe we should not provide defaultAdvisorAutoProxyCreator in JavaMelodyConfiguration, just tell javamelody user to enable spring aop auto-proxy in the guide, <aop:aspectj enable-autoproxy> or @EnableAspectJAutoProxy both do the job perfectlly.

**Comment by evernat** [comment]
Spring boot V1 applications using the javamelody spring boot starter may not have an aspectj dependency.  So @EnableAspectJAutoProxy is not a good idea.

And in fact, the spring boot starter for spring boot V1 was based on `DefaultAdvisorAutoProxyCreator` while the current spring boot starter for spring boot V2 has now removed the `DefaultAdvisorAutoProxyCreator` and has added the `spring-boot-starter-aop` required dependency.

I have added a note about auto-proxy issues in doc:
https://github.com/javamelody/javamelody/wiki/SpringBootStarter#or-integration-without-the-spring-boot-starter
Thanks for asking about this.

**Comment by ZhangChaoWN** [comment]
Is DefaultAdvisorAutoProxyCreator really required for us to use javamelody in spring-boot 1 application? In my spring-boot 1 applicatin, 
AnnotationAwareAspectJAutoProxyCreator is created by default. AnnotationAwareAspectJAutoProxyCreator would do things as same as DefaultAdvisorAutoProxyCreator , the difference is AnnotationAwareAspectJAutoProxyCreator also handle annotation declared aspects.
 If AnnotationAwareAspectJAutoProxyCreator and DefaultAdvisorAutoProxyCreator exists at same time, some aspects would execute twice for each method invocation. 

The content you added in doc is not what i really experenced. I didn't see error message `The bean could not be injected as ...`, my problem is aspects execute twice for each method invocation.

Avoid problem is better than tell doc reader what to do when they met problems.

**Comment by evernat** [comment]
Yes DefaultAdvisorAutoProxyCreator is required in spring-boot 1 app, when the app does not have a spring-boot-starter-aop / aspectj dependency. And no, AnnotationAwareAspectJAutoProxyCreator is not created in this case. I know that you didn't see the same error message, but your case is specific. So, I think that the doc speaking about auto-proxy issues in general when not using the javamelody spring-boot-starter is good enough.
