### ISSUE TITLE
Add parameter to disable JspWrapper

### ISSUE THREAD

**Issue by dicksonleong** [javamelody/javamelody#823]
Currently, `MonitoringFilter` will always create a `JspWrapper` to wrap the HttpServletRequest object.

As JSP becoming a legacy technology and newer applications are using modern template libraries such as thymeleaf or freemarker, JspWrapper becoming useless and unnessary overhead in these application. Adding a parameter will be useful to remove these overhead (even if negligible, it is still unnessary overhead).

**Comment by evernat** [comment]
First, note that the JspWrapper does not monitor only JSP. In fact, it monitors all request.getRequestDispatcher("...").include(request, response) or forward(request, response), which is used for JSP in general, but which may be used by other technologies.

Then it is known (and measured) that the overhead of javamelody is negligible compared to the execution of any application's code. And given that when getRequestDispatcher("...") is not used in an application, JspWrapper only creates a HttpServletRequestDispatcher to wrap every HttpServletRequest methods calls (without using reflection), then the JspWrapper's overhead is negligible compared to javamelody's code. By the way, the JspWrapper's overhead would be still be negligible even if getRequestDispatcher("...") would be used.
So JspWrapper overhead is negligible compared to the negligible.
And there is absolutely no reason to add this feature and a parameter for it.
Adding a parameter is not negligible: it makes many users ask themselves if they should use it or not for example.
