### ISSUE TITLE
Javamelody-spring-boot-starter 2 Issue

### ISSUE THREAD

**Issue by cbeaujoin** [javamelody/javamelody#825]
Using dependencies:

- Spring boot : 2.1.4.RELEASE
- javamelody-spring-boot-starter : 1.76.0
- fr.xebia.extras.selma-processor : 1.0

Result in : 

> o.s.aop.framework.CglibAopProxy          : Unable to proxy interface-implementing method [public final java.util.List AdminMapperSelmaGeneratedClass.asRoleJsonList(java.util.List)] because it is marked as final: Consider using interface-based JDK proxies instead!

> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'AdminController': Unsatisfied dependency expressed through field 'adminMapper'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'adminMapperSelmaGeneratedClass' defined in file : Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of classAdminMapperSelmaGeneratedClass: Common causes of this problem include using a final class or a non-visible class; nested exception is java.lang.IllegalArgumentException: Cannot subclass final class AdminMapperSelmaGeneratedClass

AdminMapperSelmaGeneratedClass is a generated class based on an interface, generated code looks like this : 

```
@org.springframework.stereotype.Service("")
public final class AdminMapperSelmaGeneratedClass
    implements AdminMapper {
```

When removing javamelody dependency, it works fine.

Any ideas ?

**Comment by cbeaujoin** [comment]
Find a solution by generating not final class using @Mapper(withFinalMappers = false) Selma annotation .
Can be close.

**Comment by evernat** [comment]
ok
