### ISSUE TITLE
Integration of JavaMelody with Spring-Session

### ISSUE THREAD

**Issue by bkbonner** [javamelody/javamelody#826]
We have several clustered servers behind a load balancer.  We've been using spring-security and our load balancer is set to have sticky sessions.  (client requests travel back to the same server).   We also provide an impersonation feature via the session.

The challenge with this setup is scalability.  We're exploring Spring-Session as a way around this.

We configured spring-session to externalize session management to Redis.   The configuration was straightforward, but we're running into a challenge with the SessionListener in JavaMelody.

[updated/]
Since the SessionListener keeps track of the HttpSession objects after the fact, it's not receiving updates from the Spring-Session mapped sessions.   The HttpSession objects are no longer 'linked' when attributes are set, removed, or replaced.

I think this will continue to be the case until SpringSession supports HttpSessionAttributeListener in some manner to keep the two in sync.

Until that time, this issue probably doesn't make sense to work on.  https://github.com/spring-projects/spring-session/issues/5

**Comment by evernat** [comment]
Hi,
I see the updated issue.

You say:
> we're running into a challenge with the SessionListener in JavaMelody
> The HttpSession objects are no longer 'linked' when attributes are set, removed, or replaced.

What's the problem exactly? Is it that some session attributes are not up to date when displayed in javamelody?

**Comment by evernat** [comment]
It seems that this is an issue in spring-session which do not synchronize session state in some case.
So closing as not an issue in javamelody.
