### ISSUE TITLE
Javamelody - Ngnix

### ISSUE THREAD

**Issue by adityamadhira** [javamelody/javamelody#827]
Hi I install java melody for Gerrit.  Gerrit is using https was hosted via reverse proxy using ngnix.
it throws 404 error. 

Here are the reverse proxy settings in ngnix config -
location /gerrit/monitoring {
                proxy_pass              http://localhost:8081/tmp/gerrit_sjc1uvt-ger01.synaptics.com;
                proxy_set_header        X-Forwarded-For $remote_addr;
                proxy_set_header        Host $host;
        }
javamelody files are sitting in /tmp/ directory.

Please help me how to fix it.

Thanks

**Comment by evernat** [comment]
I suppose that you have installed the [javamelody gerrit plugin](https://gerrit-review.googlesource.com/Documentation/config-plugins.html#javamelody). (If you have installed javamelody without the plugin, it does not change the following.)

Note first that I am not the maintainer of the javamelody gerrit plugin. But still, I think that there is a misunderstanding given what you are trying to do: javamelody files can't be used directly to display reports.

I think that you do not need anything in nginx to configure javamelody /monitoring page.
So you can remove from nginx the lines you have written for /gerrit/monitoring and if your gerrit server is available at http://yourgerrit/ then the javamelody reports are simply available at http://yourgerrit/monitoring
