### ISSUE TITLE
Performance with mbeanserver

### ISSUE THREAD

**Issue by cocorossello** [javamelody/javamelody#828]
Hi, 

We are using javamelody across all the application, measuring also some CDI methods, which are used in the order of thousands of times.

I can see some cases (in our CI environment, where about 100 UI tests are running in parallel) where a lot of threads are locked reading Mbeanserver, coming mainly from ThreadInformations. Have you seen such locks?

	-  waiting on java.util.concurrent.locks.ReentrantReadWriteLock$FairSync@5d50183
	at java.base@12/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.base@12/java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
	at java.base@12/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:1009)
	at java.base@12/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1324)
	at java.base@12/java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:738)
	at java.management@12/com.sun.jmx.mbeanserver.Repository.retrieve(Repository.java:484)
	at java.management@12/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1077)
	...

	Number of locked synchronizers = 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@61d6efe7

**Comment by cocorossello** [comment]
I can see that most of the problem comes from MBeansAccessor

	static long getThreadAllocatedBytes(long threadId) {
		if (!MBEAN_ALLOCATED_BYTES_ENABLED) {
			return -1L;
		}
		try {
			return (Long) MBEAN_SERVER.invoke(THREADING, "getThreadAllocatedBytes",
					new Object[] { threadId }, THREAD_ALLOCATED_BYTES_SIGNATURE);
		} catch (final JMException e) {
			throw new IllegalStateException(e);
		}
	}

It can be rewritten as 
((com.sun.management.ThreadMXBean) ManagementFactory.getThreadMXBean()).getThreadAllocatedBytes(threadId)

But I suppose there was a reason for using getPlatformMBeanServer instead of ThreadMXBean. Maybe it's now safe to use it?  Care for a PR?

**Comment by cocorossello** [comment]
Ok, I understand the problem now. It's java 9 modules. I can work around it by adding the jdk switch --add-exports jdk.management/com.sun.management.internal=ALL-UNNAMED

I think that at least a warning should be issued when getThreadAllocatedBytesMethod could not get the method because the performance degrades (noticeable under heavy load)

**Comment by evernat** [comment]
Yes getPlatformMBeanServer is used instead of ThreadMXBean because of Java 9 modules.
I think that I understand the issue.
You are measuring CDI methods in test under "heavy load" (100 tests in parallel), by configuring [monitoring using CDI](https://github.com/javamelody/javamelody/wiki/UserGuide#8-business-facades-ejb-jarxml-file-if-ejb3-or-cdi).
To have an issue with this lock in MBeanServer with Java 9, I think that you are measuring a lot of calls to small and very fast methods. And in the same CDI chapter, the user's guide says "it is not recommended for response time to monitor execution of all the methods of EJB3 beans, for example the methods of low granularity as getters of entities".
So if you can, it would be recommended to reduce the measuring on those methods. Monitoring the response time of those small and already very fast methods is probably not needed anyway.
Otherwise, yes the jdk switch `--add-exports jdk.management/com.sun.management.internal=ALL-UNNAMED` workarounds the lock in MBeanServer.
Thanks for the issue.

**Comment by blontrock** [comment]
We encounter the same issue in production. It seems to occur under heavy load (we have big application servers with 20 cpu's) and get a lot of traffic. It starts suddenly and then hundreds of requests are all waiting for the lock. Restarting the application server sometimes fixes it. Other application servers (not yet hit with the bug) that have a similar traffic have about 20-60 concurrent requests running and I think a maximum of about 170 requests per second at peak times.

Most of the threads are like this:
`http-nio-8080-exec-154
jdk.internal.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:1009)
java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1324)
java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:738)
com.sun.jmx.mbeanserver.Repository.retrieve(Repository.java:484)
com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1077)
com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:806)
com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
net.bull.javamelody.internal.model.MBeansAccessor.getThreadAllocatedBytes(MBeansAccessor.java:128)
net.bull.javamelody.internal.model.ThreadInformations.getThreadAllocatedBytes(ThreadInformations.java:102)
net.bull.javamelody.internal.model.ThreadInformations.getCurrentThreadAllocatedBytes(ThreadInformations.java:87)
net.bull.javamelody.internal.model.Counter.bindContextIncludingCpu(Counter.java:419)
net.bull.javamelody.MonitoringSpringInterceptor.invoke(MonitoringSpringInterceptor.java:75)
org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
com.sun.proxy.$Proxy34...(our application code)`

**Comment by evernat** [comment]
@blontrock 
Have you configured Spring to monitor some methods using MonitoringSpringInterceptor ? if yes, how/what kind of methods are monitored?
And do you use the javamelody spring-boot-starter?
Which version of javamelody are you using?
Which version of java are you using?

**Comment by evernat** [comment]
@blontrock 
And to have a concrete understanding of the issue, can you make a screenshot of the ten or twenty first lines of the detailed Spring statistics (for the week period for example) in the monitoring page? You can mask private information in the screenshot.
