### ISSUE TITLE
Monitoring jira customfields

### ISSUE THREAD

**Issue by aminachayeb** [javamelody/javamelody#829]
I have a jira customfield that acess database throw a jdbc connection, how can I manage javamelody to monitor database access performed by this customfield

**Comment by evernat** [comment]
You can monitor sql requests using the javamelody plugin for JIRA / Confluence / Bamboo / Bitbucket.
See the configuration of the datasource:
https://github.com/javamelody/javamelody/wiki/AtlassianPlugin

Then you can find some particular sql requests in the monitoring page. For example, in the monitoring page click the Details link below the sql statistics. And use the search feature of the browser to find the sql requests on the `customfield` and `customfieldvalue` tables or the sql request used by your custom field (I suppose that you know which table it is using).

**Comment by aminachayeb** [comment]
Hi again,
I followed steps to configure datasource, I can get sql request but no graphic representation of jdbc connections

**Comment by evernat** [comment]
The graphs of active and open jdbc connections are on the main monitoring page on the second row.
Note that depending if sql requests are not slow enough or not with enough load from users, those graphs will remain at 0 most of the time (for example, on a server with just a few tests).

**Comment by aminachayeb** [comment]
My custom field access a database other then default jira database. I added this data base to ressource file but I can't find an request of those executed by my custom field Any thing I could do to let javamelody monitor these jdbc connexions

**Comment by evernat** [comment]
@aminachayeb 
You should use a datasource from jndi with a jndi name like "jdbc/xxxx".
See the following for more info:
https://github.com/javamelody/javamelody/wiki/UserGuide#7-jdbc
