### ISSUE TITLE
How to use javamelody with SharedPoolDataSource?

### ISSUE THREAD

**Issue by mikeRozen** [javamelody/javamelody#831]
Hi,
Is there a way to use javamelody with SharedPoolDataSource _directly_ in the code?
It seems to be possible to use it with BasicDataSource (by using the driverClassName and addConnectionProperty) but I can't find an alternative for it in the SharedPoolDataSource.
Could you please suggest?
Thanks.

**Comment by evernat** [comment]
Hi Mike,
If you create a datasource directly in the java code (that is not in JNDI or in Spring), you can do like the following:
```java
DataSource ds = ... ;
ds = net.bull.javamelody.JdbcWrapper.SINGLETON.createDataSourceProxy(ds);
```
you can then use the datasource (which is monitored) as before.
