### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by lukaskarabec** [javamelody/javamelody#832]
Hi, I added Czech translation to POE. Please add to next release. Thx :-)

**Comment by evernat** [comment]
Hi Lukas,
Thank you for the translation.
I understand nothing to the Czech language, but I have changed about 50 labels. For example, beans are not fazole in Czech, Spring is not jaro.
Can you check at least the latest 50 labels which I have changed in POE ? (order the list by "Updated DESC").
Thanks.

**Comment by lukaskarabec** [comment]
It´s look ok ;-) thx for repair ;-)

**Comment by evernat** [comment]
Czech Translations merged (2d85a88) and ready for the next release (1.78). Thanks.
You can test including PDF reports, a snapshot build is available at:
http://javamelody.org/downloads/javamelody-core-1.78.0-SNAPSHOT.jar
