### ISSUE TITLE
Unable to install JavaMelody v1.77.0 on Confluence

### ISSUE THREAD

**Issue by CathySoMcK** [javamelody/javamelody#833]
We get the following error in the logs trying to upload the jar or use the URL to install...

-- url: /rest/plugins/1.0/ | referer: https://confluence.domain.com:8443/plugins/servlet/upm | traceId: f6c14e4057eca186 | userName: elkzze1
2019-05-04 13:56:58,988 WARN [UpmAsynchronousTaskManager:thread-1] [upm.core.install.DefaultPluginInstallationService] execute Plugin installation failed: Jar contained neither an atlassian-plugin.xml nor a Bundle-SymbolicName

**Comment by evernat** [comment]
When testing with a fresh Confluence install using v6.15.2, installing the plugin via an URL (https://github.com/javamelody/jira-confluence-javamelody/releases/download/1.77.0/jira-confluence-javamelody-1.77.0.jar) does not work at first try:
 -- url: /rest/plugins/1.0/ | referer: http://localhost:8090/plugins/servlet/upm | traceId: 612e9bc88db4d12f | userName: xxxxx
java.lang.IllegalArgumentException: The artifact URI file:/C:/xxxxx/atlassian-confluence-6.15.2-data/plugins-cache/1557275091488plugin.4184807343189304003.dee14580-63d5-11e9-84ad-61decba5a939 is not a valid plugin artifact
WARN [UpmAsynchronousTaskManager:thread-2] [upm.core.install.DefaultPluginInstallationService] execute Plugin installation failed: Unknown error, plugin not installed

That's not the same issue as yours. I have reported my issue to Atlassian with details to enable them to fix it.

**Comment by evernat** [comment]
But when uploading manually from a local jar file (instead of an URL), it works well.
I suggest to download again the jar file and to upload it again in Confluence. Then restart Confluence just in case.
By the way, the jar file is a zip format and it contains an atlassian-plugin.xml file as you can check by yourself.

**Comment by evernat** [comment]
Hi @CathySoMcK 
Any news?
By the way, you can vote for the issue with uploading a jar file via an URL (like https://github.com/javamelody/jira-confluence-javamelody/releases/download/1.77.0/jira-confluence-javamelody-1.77.0.jar) here:
https://jira.atlassian.com/browse/CONFSERVER-58316
(you need to login, for example with a google login)

**Comment by evernat** [comment]
No response at the moment.
Closing as invalid on javamelody side.
