### ISSUE TITLE
Monitor all deployments

### ISSUE THREAD

**Issue by oconnor** [javamelody/javamelody#839]
I followed the Tutorial [Deployment on Tomcat without modification of monitored webapps (beta)](https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#deployment-on-tomcat-without-modification-of-monitored-webapps-betal) . The Monitoring Site is working, I can see the statistics page. The Problem ist Javanmelody recognizes only the pages itself and the tomcat manager. But none of the deployments pages gets recognized. What can I do that Javamelody is monitoring all deployments? The Tomcat 9 has about 50 deployments. I want to see statistics about all deploments not just one deployment.

**Comment by evernat** [comment]
If I understand, you have 50 webapps in a single Tomcat. Wow !
javamelody has a monitoring page and statistics for each webapp independently from the others.
For example:
.../webapp1/monitoring
.../webapp2/monitoring
If you really want to aggregate the graphs and statistics for all webapps in a single monitoring page, you may use the [optional collect server](https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#optional-centralization-server-setup).

If I can ask, why do you have 50 webapps in a single Tomcat?

**Comment by oconnor** [comment]
Ok, I will try the optional collect server. 
The webapps are alle the same, but with different customers (companies). I like to watch the performance from the tomcat overall and also identify webapps with high perfomance requirements to deploy them at a different Tomcat. I do have some tomcats, and i cant watch at every deployment (up to 50) to see how busy one tomcat is.

**Comment by evernat** [comment]
In the optional collect server, instead of adding the webaps one by one independently, you can add all the webapps' urls separated by `,` in one go.

**Comment by oconnor** [comment]
Alright that is what I was looking for. "Note: it is not possible to monitor one application in several collect servers or twice in one collect server." If i understand it right, now I have to make the decision, if I want to monitor all deployments or one by one. I can not have both? You also have automatic registration. Thats great! Do I have to use the same applicationName to register all deployments in one statistic?

**Comment by evernat** [comment]
Yes, you can not have both one by one and all in one in the collect server (at least currently).

For automatic registration, yes you can call `registerApplicationNodeInCollectServer` in each webapp using the same applicationName to add the webapps URLs one after the other. (I have almost forgotten that yes it works). After registering all deployed webapps that way, you will have all statistics in one global application of the collect server.

**Comment by oconnor** [comment]
It would be a realy good feature to switch between "all in one" and "one by one"! Now Im going to implement the automatic registration. Thanks.

**Comment by evernat** [comment]
Ok and I note the idea.
