### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [javamelody/javamelody#842]
Hi
The following lines have cryptographic API misuses. <br> File name => javamelody-core/src/main/java/net/bull/javamelody/internal/model/CounterRequest.java: Line number => 480: API name => MessageDigest:First parameter (with value "SHA-1") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => javamelody-core/src/main/java/net/bull/javamelody/internal/model/UpdateChecker.java: Line number => 303: API name => MessageDigest:First parameter (with value "SHA-1") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => javamelody-core/src/main/java/net/bull/javamelody/internal/model/CounterRequest.java: Line number => 460: API name => MessageDigest:<BR> File name => javamelody-core/src/main/java/net/bull/javamelody/internal/model/UpdateChecker.java: Line number => 313: API name => MessageDigest:<BR>

**Comment by evernat** [comment]
Yes, I know that SHA-1 is not good for cryptographic usage.
But in javamelody, SHA-1 is not used for cryptographic: SHA-1 is used only to compute internal identifiers based on a hash. There is no security required for the computed hashes.
So closing this issue as invalid.

**Comment by evernat** [comment]
To be precise, we could have used the String.hashCode() method, which would have been ok for you, except that we needed more unique results than hashCode().
