### ISSUE TITLE
Tomcat info is not available anymore

### ISSUE THREAD

**Issue by dmitrysm2000** [javamelody/javamelody#843]
Since Tomcat 8.5.35 the Tomcat information is not anymore available with Javamelody 1.74.0.
The same issue as https://bz.apache.org/bugzilla/show_bug.cgi?id=62918 and https://github.com/micrometer-metrics/micrometer/issues/1145

**Comment by evernat** [comment]
Thanks for the issue.
It's fixed by c207790 and ready for the next release (1.79).
A snapshot build, including the fix, is available at:
javamelody.org/downloads/javamelody-core-1.79.0-SNAPSHOT.jar
