### ISSUE TITLE
Export Statistics Requests to InfluxDB

### ISSUE THREAD

**Issue by aaschlote** [javamelody/javamelody#846]
Hi,

I've used Java Melody to follow the statistics of request from my web application. Thanks to that I can see how many hits are used at my EndPoints. 

Now I would like to export this metrics to the InfluxDB, so I can create some graphics in the Grafana. But at moment I just can export the time, host, application and a value from each metric. I would like to know, it's possible to export the information about the request of my EndPoints, thereby I can visualize my EndPoints in the Grafana.

Someone could tell me, how I can export those informations to InfluxDB?

![JavaMelodyInfluxDB](https://user-images.githubusercontent.com/11893663/61717372-38ed0080-ad61-11e9-90b1-18704c48e276.png)

Thanks advance!

**Comment by evernat** [comment]
You can't export all these values to InfluxDB.
Because it would probably be too much data: there are 12 columns+request name in these http statistics and possibly 10000 rows. That would be 120000 values + request names each minute for http statistics.
And possibly 60000 values + sql requests for sql statistics, And possibly logs, http errors ...
That's too much, isn't it ?

**Comment by aaschlote** [comment]
Well, if we're monitoring an application I can expect to receive too much data. I would just to know, its not possible to export these values to InfluxDB, how and where could I export these values?

**Comment by evernat** [comment]
> if we're monitoring an application I can expect to receive too much data

No, if your network and server are doing upload of data to InfluxDB much more than response to users' requests, it's not expected. And no, causing the crash of your server is not expected either. So you can't expect to send too much data to InfluxDB.

If you want to export the values at your wish as json or xml, see the [External API](https://github.com/javamelody/javamelody/wiki/ExternalAPI).
