### ISSUE TITLE
When downloading more than 2GB, assertionError may occur

### ISSUE THREAD

**Issue by rPraml** [javamelody/javamelody#847]
We streamed a file more than 2GB through javaMelody and got an assertion error at `Counter.addRequest` in line `assert responseSize >= -1; // -1 pour requêtes sql`

https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/internal/model/Counter.java#L487

This may happen through integer overflow and the int got negative. So responseSize should be effectively changed to `long` in `CounterResponseStream` and all methods that access it.

**Comment by evernat** [comment]
Fixed by 29b8e30 and ready to be released in 1.79 (soon).
Thanks for the issue.
