### ISSUE TITLE
ehcache for javamelody-offline-viewer

### ISSUE THREAD

**Issue by Shahbazakhter** [javamelody/javamelody#850]
Hi,

Java melody offline viewer provides a very good Offline UI for the generated reports.
However 'Data cache' section for EhCache is missing or not visisble , anyone who can point me to this ?

I need to know the hits details for each cache methods  in offline viewer as we see on 'Data cache' section for EhCache for Online Web requests.

Thanks,
Shahbaz

**Comment by evernat** [comment]
The monitoring data for caches are not stored on disk. They are only computed when asked in the monitoring page.
So they can't and they won't be displayed in the offline viewer.
I suggest to use the online monitoring page if you need information about caches.
