### ISSUE TITLE
Spring method calls counted multiple times when using combination of monitored annotations

### ISSUE THREAD

**Issue by tvirtualw** [javamelody/javamelody#851]
We use Spring Boot 2.1.5 and JavaMelody's Spring Boot Starter 1.79.0. Configuration is done through the auto configuration without additional setting changes.

We have a service like this:

```
@Service
@MonitoredWithSpring
public class MyService implements MyServiceInterface {

  @Async
  @Override
  public void myMethod() {
  }
}
```

A call to `myMethod` increments the counter in the Spring statistics by 3.

My guess is this happens due to all the bean definitions in JavaMelodyAutoConfiguration that define the pointcuts on all the annotations. `@Service` increments by 1, `@MonitoredWithSpring` increments by 1, `@Async` increments by 1.

We could remove `@MonitoredWithSpring` which would lead to counter being increased by only 2. But still, we have to keep the `@Async` and cannot get a correct count then.

So I was wondering if this is a bug in JavaMelody where somehow the logic should identify that different pointcuts affect the same method and such method invocation should only be counted once.

Or if we are doing something wrong or our project setup is special and it doesn't happen to others.

**Comment by evernat** [comment]
Because `@Service` classes are already monitored, there is no reason to add `@MonitoredWithSpring` on them.
Anyway, it is now fixed by  ef7242c and ready for the next release (1.80), including for `@Async` and `@Scheduled`.
