### ISSUE TITLE
Fix wiki for Boomerang url

### ISSUE THREAD

**Issue by kortov** [javamelody/javamelody#861]
In [projects wiki](https://github.com/javamelody/javamelody/wiki/UserGuide#18-real-user-monitoring) url for  Boomerang  doc

 ![image](https://user-images.githubusercontent.com/6348215/65421423-bd690780-de14-11e9-9ce8-02312db3fb2d.png)

 returns 404, I guess it should be replaced with [this one](http://akamai.github.io/boomerang/)

**Comment by evernat** [comment]
fixed, thank you
