### ISSUE TITLE
Error in /monitoring?action=mail_test using Tomcat 9, Open SDK 11

### ISSUE THREAD

**Issue by reyazucar** [javamelody/javamelody#865]
Hi, 
l have the following exception when i trying to test the mail sending of reports.
(Tomcat 9, Open SDK 11)

java.lang.LinkageError: loader constraint violation: when resolving method 'void javax.mail.internet.MimeBodyPart.setDataHandler(javax.activation.DataHandler)' the class loader org.apache.catalina.loader.ParallelWebappClassLoader @c7045b9 of the current class, net/bull/javamelody/internal/common/Mailer, and the class loader java.net.URLClassLoader @4ee285c6 for the method's defining class, javax/mail/internet/MimeBodyPart, have different Class objects for the type javax/activation/DataHandler used in the signature (net.bull.javamelody.internal.common.Mailer is in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @c7045b9, parent loader java.net.URLClassLoader @4ee285c6; javax.mail.internet.MimeBodyPart is in unnamed module of loader java.net.URLClassLoader @4ee285c6, parent loader 'app')
	net.bull.javamelody.internal.common.Mailer.send(Mailer.java:161)
	net.bull.javamelody.internal.web.MailReport.sendReportMail(MailReport.java:171)
	net.bull.javamelody.internal.web.MailReport.sendReportMailForLocalServer(MailReport.java:141)
	net.bull.javamelody.internal.model.Action.mailTest(Action.java:360)
	net.bull.javamelody.internal.model.Action.execute(Action.java:205)
	net.bull.javamelody.internal.web.MonitoringController.executeActionIfNeeded(MonitoringController.java:121)
	net.bull.javamelody.internal.web.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:152)
	net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:408)
	net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:206)
	org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)

thanks in advance
damian

**Comment by evernat** [comment]
It seems that you have the mail jar file and / or the activation jar file both in tomcat/lib and in WEB-INF/lib of your webapp.
To have mails sent by javamelody, they should be in tomcat/lib, so remove the mail jar file and / or the activation jar file from WEB-INF/lib of your webapp.
(JDK 11 or Tomcat 9 may have forced the classloaders to be clean in this case.)

**Comment by reyazucar** [comment]
thanks for your time and help.
i fixed the issue using javax.mail-1.6.0.jar in my project and in tomcat lib too. 
(Without using activation lib)

maven dependency
        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>javax.mail</artifactId>
            <version>1.6.0</version>
        </dependency>

regards
