### ISSUE TITLE
JSF page with garbled characters after adding Java Melody to the classpath

### ISSUE THREAD

**Issue by v2saude** [javamelody/javamelody#866]
Hi, I've added Java Melody to one of our applications that uses JSF + Tomcat 7. It is able to monitor and capture metrics just fine. The thing is that some of the pages (that are non UTF8 encoded but latin1) are displaying garbled characters.

![javamelody](https://user-images.githubusercontent.com/34678335/66149966-9cf63580-e5ea-11e9-8c8d-6b15e0809a95.gif)

Is there any configuration I could do on web.xml to avoid such behavior? I was looking at the source code but haven't found any clue.

Thank you very much,

**Comment by evernat** [comment]
You may have some code calling ServletRequest.setCharacterEncoding(String) or ServletResponse.setCharacterEncoding(String), perhaps in a servlet Filter.
If yes, you can try to put this filter and its filter mapping above the javamelody MonitoringFilter in web.xml.

**Comment by evernat** [comment]
Any news?

**Comment by evernat** [comment]
No response from the reporter, so closing.
