### ISSUE TITLE
log-transform-pattern not working?

### ISSUE THREAD

**Issue by thackel** [javamelody/javamelody#870]
Setting `log-transform-pattern` /  `Parameter.LOG_TRANSFORM_PATTERN` to any value does not seem to have any effect.

Also a quick search in the code via github does not show up any usages of the enum value or the string.

I just want to get rid of `WARN` log events, so the pattern i would use is `ERROR\|FATAL`.

**Comment by evernat** [comment]
The enum is used at https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/FilterContext.java#L215

The goal of the transform patterns is to replace matches with `$` in order that the rest of the request can be aggregated with other identical requests.
For example, for the SQL request `select * from A where id = 1234`, which does not use a binded parameter unfortunately, we should define the sql-transform-pattern `\d+` to transform the SQL request to `select * from A where id = $`. So all SQL requests like this one can be aggregated with mean and max times for a single entry in the statistics.

In your case, you want to remove `WARN....` logs. You can't do that in javamelody, but you can transform all `WARN....` logs to `WARN$` with a log-transform-pattern parameter like `(?<=WARN).*` with lookbehind.
This way you will have a single line in statistics with `WARN$` and it will give almost the same effect as you want.
Note that if you write the parameter in an xml file, you have to xml escape the value as `(?&lt;=WARN).*`.

**Comment by thackel** [comment]
Thanks for the detailed explanation!

But i still have doubts. The title in the overview is:

> Statistics system errors logs

So i expect only ERRORs and above in this list, otherwise it should be renamed to

> Statistics system warnings and errors logs

Who wants to see warnings at this place? I think it should be reduced, or maybe if existing setups should not be bothered a new category with only errors should be available.
