### ISSUE TITLE
Enhancement: offer the value of getUsableSpace()

### ISSUE THREAD

**Issue by rwalkerands** [javamelody/javamelody#875]
The data for the "Free disk space" graph is based on the value of `getFreeSpace()`. (See `JavaInformations.java`.) At least on Linux/Unix this value includes _both_ the free space for block usage and for inodes. In practice, you will almost certainly run out of block usage first, and have a lot of inode space left over that you can't use.

For example, javamelody is currently telling me that I have 22 G of disk space free. But the output of `df` tells me that I only have 15 G free; the other 7 G is certainly "free", but it is allocated for inodes.

The getUsableSpace() method does return 15 G in my case. Test program:

```
import java.io.File;

public class freespace {

    public static void main(String[] args) {
	File file = new File(".");
	System.out.println("getFreeSpace: " + file.getFreeSpace());
	System.out.println("getUsableSpace: " + file.getUsableSpace());
    }

}
```

Output:
```
getFreeSpace: 22095831040
getUsableSpace: 15895654400
```

So, would it be possible to have the value of `getUsableSpace()` recorded and graphed, either as well as, or instead of, `getFreeSpace()`?

**Comment by evernat** [comment]
Done by 6eb6c99 and ready for the next release (1.81).
A snapshot build is available at:
http://javamelody.org/downloads/javamelody-core-1.81.0-SNAPSHOT.jar

**Comment by rwalkerands** [comment]
Works for me, thank you!
