### ISSUE TITLE
Loading a lot of metrics

### ISSUE THREAD

**Issue by ojusttryo** [javamelody/javamelody#880]
Is there a way to download metrics only when we open the "metrics" on http://localhost:9999/monitoring?part=mbeans? If not, it would be great to add the option to load specific group only when you open it or something like that.
We have a lot of metrics. There are may be more than 10 000. And they take too long to load.

**Comment by ojusttryo** [comment]
Are there any chance of adding this functionality?

**Comment by evernat** [comment]
Sorry for the delay.
There is no such option.
After thinking about it, there is no plan to add it since it is too specific for your case in my opinion.
You can forbid the access to this URL using a servlet filter if needed.
