### ISSUE TITLE
Enabling Authentication for monitoring page

### ISSUE THREAD

**Issue by sowmya-parsi** [javamelody/javamelody#881]
I have installed the JavaMelody plugin for bitbucket as mentioned here : https://github.com/javamelody/javamelody/wiki/AtlassianPlugin and set the system property -Djavamelody.authorized-users=admin:pwd . Doing this authentication for the monitoring page is working fine but there is something conflicting in general bitbucket apllication authentication.Is there any way in which the monitoring uses bitbucket authentication only.

**Comment by evernat** [comment]
Sorry. As said in the [user's guide for Bitbucket](https://github.com/javamelody/javamelody/wiki/AtlassianPlugin#Bitbucket):

>  there is no easy access to the user from the http session and Bitbucket's AuthenticationContext does not give access to the user given the order of servlet filters

This is still true when using Bitbucket 6.9.0.

**Comment by sowmya-parsi** [comment]
Hi ,
As said before I have included the property in system properties now the monitoring page have authentication after this somehow the bitbucket application authentication has got affected and it is not showing the login page PFA for more details.
![git-dev](https://user-images.githubusercontent.com/36162299/71413525-953dae80-2678-11ea-894b-81fc2640df8e.jpg)
![git-dev-1](https://user-images.githubusercontent.com/36162299/71413530-9bcc2600-2678-11ea-8d88-ebb91a701c42.jpg)


for more details
