### ISSUE TITLE
Using java melodody with springboot

### ISSUE THREAD

**Issue by cehdmoy** [javamelody/javamelody#887]
Hi all, I'm using javamelody with spring-boot, and everything is going fine, BUT when I kill my *.jar instance and then reboot it, javamelody still has the previous data (my assumption is that it's saving some log file or something like that). My question is, how can I reset my metrics? Is it possible? 

Thanks!!

**Comment by evernat** [comment]
Yes, the monitoring data of javamelody is persistant. That way you can have performance history and trends in statistics and in graphs for any period over a year.
The javamelody files are compact. Total size is typically 10 MB for a small application up to 100 MB for a quite big application.  Purge of old data is automatic.

I don't know why you would want to delete all history, but if you still want to do that you will find the javamelody files in the javamelody subdirectory in the temp directory by default (/tmp/javamelody or $TOMCAT_HOME/temp/javamelody in Linux). The debugging logs at the bottom of the monitoring page prints where those files are.
You may delete those files and new files will be created again as time goes on.
