### ISSUE TITLE
Basic auth checks login only once

### ISSUE THREAD

**Issue by pema83** [javamelody/javamelody#891]
Years ago I have added JavaMelody to our spring application.
Normally we controll access to JM via webserver and or firewall configuration.
But now we also need authentication in JM.
A simple password check would do, so I decided to try the basic auth configuration of JM.

It works. Once. But after asking the credentials once, the user never gets asked again after the first successful login. Even after using the logout button from the JM menu, the user won't be able to login again and JM is just open and unlocked. 

JM debug out states that the user is logged out. But still the user can see and do everything in JM.

`
Thu Feb 06 09:28:46 CET 2020     DEBUG     first collect of data done
Thu Feb 06 09:28:46 CET 2020     DEBUG     Authorized user: admin
Thu Feb 06 09:28:46 CET 2020     DEBUG     JavaMelody filter init done in 385 ms
Thu Feb 06 09:30:45 CET 2020     DEBUG     Action 'LOGOUT' executed. Result: Sie sind ausgeloggt
`
After logout the logout button disappears from the menu.

I managed to get, what we needed using a config in web.xml and tomcat-users. But this would rob us from the possibility to change the settings in our application config.

`@Configuration
@ImportResource("classpath:monitoring-spring.xml")
@SuppressWarnings("javadoc")
public class JavaMelodyConfiguration implements ServletContextInitializer {
    @Override
    public void onStartup(ServletContext servletContext) throws ServletException {
        servletContext.addListener(new SessionListener());
    }

    @Bean
    public FilterRegistrationBean javaMelody() {
        FilterRegistrationBean javaMelody = new FilterRegistrationBean();
        javaMelody.setFilter(new MonitoringFilter());
        javaMelody.setAsyncSupported(true);
        javaMelody.setName("javamelody4app");
        javaMelody.setDispatcherTypes(DispatcherType.REQUEST, DispatcherType.ASYNC);

        // see the list of parameters:
        // https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters

        javaMelody.addInitParameter(Parameter.QUARTZ_DEFAULT_LISTENER_DISABLED.getCode(), Boolean.toString(true));
        javaMelody.addInitParameter(Parameter.LOG.getCode(),
                Boolean.toString(Config.getApplicationConfig().getJavaMelodydoLog()));
        javaMelody.addInitParameter(Parameter.DISABLED.getCode(),
                Boolean.toString(Config.getApplicationConfig().getJavaMelodyIsDisabled()));
        javaMelody.addInitParameter(Parameter.MONITORING_PATH.getCode(),
                Config.getApplicationConfig().getJavaMelodyMonitoringUrl());
        javaMelody.addUrlPatterns("/*");

        javaMelody.addInitParameter("http-transform-pattern", "\\d+");
        javaMelody.addInitParameter("sql-transform-pattern", "\\d+");
        javaMelody.addInitParameter("spring-transform-pattern", "\\d+");
        javaMelody.addInitParameter("log-transform-pattern", "\\d+");
        javaMelody.addInitParameter("error-transform-pattern", "\\d+");
        javaMelody.addInitParameter("job-transform-pattern", "_\\d+");

        javaMelody.addInitParameter("url-exclude-pattern", "\\/app/+");
        javaMelody.addInitParameter("url-exclude-pattern", "\\/css/+");

        
        // to add basic auth:
        javaMelody.addInitParameter(Parameter.AUTHORIZED_USERS.getCode(),
                Config.getApplicationConfig().getJavaMelodyLoginString());
        // to change the default storage directory:
        // javaMelody.addInitParameter(Parameter.STORAGE_DIRECTORY.getCode(), "/tmp/javamelody");

        return javaMelody;
    }

}`

**Comment by pema83** [comment]
Correction:
The configuration of which I thought, that it works, is in fact only working because I had different credentials set in the tomcat-users and in the Parameter.AUTHORIZED_USERS.getCode() settings.
If I have them both set to the same value I only get asked once…

**Comment by evernat** [comment]
Sorry for the confusion with the javamelody logout action.
The logout action logs you out of the webapp (that is it simply invalidates your http session). And there is no relation between the javamelody basic auth (authorized-users parameter) and the logout action.
In fact, when javamelody asks for your basic auth credentials, your browser remembers these credentials for the monitoring URL and your browser does not ask the credentials again, until the browser is closed or forever if you said to your browser to save the credentials. That's the behavior of your browser for every basic auth on the internet and it is not different for the javamelody basic auth. And that is the same if your are "logged in" your webapp (you have a http session) or not, because there is no relation.

Is it clearer now?

**Comment by evernat** [comment]
By the way, you should not add a javamelody parameter twice on the `FilterRegistrationBean` like in
```java
    javaMelody.addInitParameter("url-exclude-pattern", "\\/app/+");
    javaMelody.addInitParameter("url-exclude-pattern", "\\/css/+");
```
The second one replaces the first one.
Instead, you can do the following since it is a regexp:
```java
javaMelody.addInitParameter("url-exclude-pattern", "/app/.*|/css/.*");
```

**Comment by pema83** [comment]
Thank you for clearing up.
I walked completely in to the wrong direction because of the logout button misinterpretation.
And thanks for the hint with the exclude pattern. Of cause you are right.
