### ISSUE TITLE
Time periods mean different things in different places

### ISSUE THREAD

**Issue by rwalkerands** [javamelody/javamelody#897]
This is at least a "gotcha" for new (and not-so-new) users. Perhaps it is not a defect, but if so, I think it would be helpful to explain this in the user guide, or to provide some sort of hint in the user interface.

The time periods "1 day", "1 week", etc. mean different things in different places.

For example:

- As part of the heading for a graph (e.g., "Used memory"), "1 day" = 24 hours.
- As part of the heading for a statistics section (e.g., "Statistics http"), "1 day" = since midnight, local time.

**Comment by evernat** [comment]
Yes, it's true. It can probably be explained somewhere.

**Comment by evernat** [comment]
In statistics titles of reports, I have added "since midnight" to explain that.
For example, "1 day since midnight".
Fixed by 32734fb and ready for the next release (1.82)

**Comment by rwalkerands** [comment]
(Very minor: the [Release Notes](https://github.com/javamelody/javamelody/wiki/ReleaseNotes) give the issue number as 891 instead of 897.)

**Comment by evernat** [comment]
Fixed, thanks.
