### ISSUE TITLE
Inconsistent library versions notice.

### ISSUE THREAD

**Issue by calvinhkf** [javamelody/javamelody#898]
Hi. I have implemented a tool to detect library version inconsistencies. Your project have 1 inconsistent library and 34 false consistent libraries.

Take javax.servlet:javax.servlet-api for example, this library is declared as version 4.0.1 in javamelody-test-webapp, 3.0.1 in javamelody-swing and etc... Such version inconsistencies may cause unnecessary maintenance effort in the long run. For example, if two modules become inter-dependent, library version conflict may happen. It has already become a common issue and hinders development progress. Thus a version harmonization is necessary.

Provided we applied a version harmonization, I calculated the cost it may have to harmonize to all upper versions including an up-to-date one. The cost refers to POM config changes and API invocation changes. Take javax.servlet:javax.servlet-api for example, if we harmonize all the library versions into 4.0.1. The concern is, how much should the project code adapt to the newer library version. We list an effort table to quantify the harmonization cost. 

The effort table shows the overall harmonization cost on APIs. It seems your project have no API invokes on this library, which could be safely upgrade to 4.0.1

|Index|Module|NA(NAC)|NDA(NDAC)|NMA(NMAC)|
|-|-|-|-|-|
|1|javamelody-test-webapp|0(0)|0(0)|0(0)|
|2|javamelody-swing|0(0)|0(0)|0(0)|

Also we provided another table to show the potential files that may be affected due to library API change, which could help to spot the concerned API usage and rerun the test cases. 

As for false consistency, take net.bull.javamelody javamelody-core jar for example. The library is declared in version 1.82.0-SNAPSHOT in all modules. However they are declared differently.  As components are developed in parallel, if one single library version is updated, which could become inconsistent as mentioned above, may cause above-mentioned inconsistency issues

If you are interested, you can have a more complete and detailed report in the attached PDF file.
[javamelody javamelody.pdf](https://github.com/javamelody/javamelody/files/4271287/javamelody.javamelody.pdf)

**Comment by evernat** [comment]
false positive

**Comment by calvinhkf** [comment]
Sorry the false positive. Currently the tool does not consider library versions due to different runtimes. Will improve in the future.
