### ISSUE TITLE
Influxdb: Masking Credentials when using system properties: -Djavamelody.influxdb-url

### ISSUE THREAD

**Issue by dharankt** [javamelody/javamelody#931]
Hi , 

We are currently running Jenkins as docker container and looking at the possibility of  sending java melody data to influxdb. The problem is we are having Influxdb setup with an basic authentication. Is there any possibility of hiding the Credentials when we set the  Djavamelody.influxdb-url in system properties ? My understanding is if we are running jenkins as a docker container we might have to use the JAVA_OPTS to set the influxdb URL . 

Kindly share your  thoughts

**Comment by evernat** [comment]
When running jenkins as docker container, I suppose that you can't set javamelody parameters as (system) properties in [catalina.properties](https://tomcat.apache.org/tomcat-9.0-doc/config/index.html), neither as [context parameters](https://tomcat.apache.org/tomcat-9.0-doc/config/context.html#Context_Parameters) and even less in web.xml.
So the only remaining option in javamelody is to use system properties (it is not currently possible to define javamelody parameters in Jenkins Manage UI).

So you can use JAVA_OPTS indeed or whatever is used to add system properties when starting jenkins.
Or, to better hide the credentials in the parameters, that is without using JAVA_OPTS and the command line of the process, you can add the same system properties using a `$JENKINS_HOME/init.groovy.d/startup-properties.groovy` file with a content like this:
```groovy
System.setProperty("javamelody.influxdb-url", "http://myusername:mypassword@11.22.33.44:8086/write?db=mydb")
```
At the moment, I do not think of other solution for jenkins as a docker container.
Is it ok for you?

**Comment by dharankt** [comment]
Yes ,Setting the System.setProperty via an groovy script seems to be an ideal solution , but the credentials are going to stay Un-masked , Which again would be worrisome . Looks like there are no other options as of now . 

Considering that i think it would be a very good feature if we have the option of adding Data-sources in Java Melody directly in the Jenkins UI  instead of going the System Property route. With Jenkins Docker containers becoming more popular  think this would useful for the Larger section of the Open source Community .

**Comment by dharankt** [comment]
@evernat  Have tried setting the influxdb-url in javaopts and as well as system properties , but the problem is the password is exposed in System Properties . Can we look into the possibility of having a feature similar to the influxdb plugin where we can set the configuration using the jenkin UI Configuration(https://plugins.jenkins.io/influxdb/)

**Comment by evernat** [comment]
I have thought about adding a javamelody UI to configure javamelody parameters. It would make available parameters more visible.
But it is not planned to add a configuration like the influxdb plugin, because it would need a specific Jenkins UI, specific Jenkins Secret and injection of specific Jenkins code for a password, while the javamelody-core code only has an URL for influxdb and it does not know Jenkins code.
So closing this issue in case of Jenkins.
