### ISSUE TITLE
Caches in report shown twice with Spring/Ehcache

### ISSUE THREAD

**Issue by shaack** [javamelody/javamelody#932]
In the cache section of my reports most caches are displayed twice:
``` 
USER_GAME_CACHE | 0 | 0 | -1 | -1 -- | -- | -- | -- | --
USER_GAME_CACHE | 267 | 0 | 100 | 85 |  -- | -- | -- | -- | -- | --
USER_HOLIDAY_CACHE | 0 | 0 | -1 | -1 |  
USER_HOLIDAY_CACHE | 2.313 | 0 | 100 | 91 |  
USERNAME_TO_ID_CACHE | 0 | 0 | -1 | -1 |  
USERNAME_TO_ID_CACHE | 3.571 | 0 | 100 | 89
```
One with '0' hits and the other seems to be the correct one.

The Hibernate Second Level Cache is shown correct (it uses the Ehcache default-Cache):
```
de.chessmail.legacy.backend.club.ClubMember | 1.114 | 0 | 100 | 34 | 
de.chessmail.legacy.backend.user.User | 3.541 | 0 | 100 | 84 |  
de.chessmail.legacy.backend.user.UserSettings | 3.584 | 0 | 100 | 84 |  
de.chessmail.legacy.backend.user.UserStatistic | 3.585 | 0 | 100 | 86
```

A part of the cache configuration.
```xml
<defaultCache
            maxElementsInMemory="20000"
            eternal="false"
            overflowToDisk="false"
            timeToLiveSeconds="1800"
            timeToIdleSeconds="300"/>

<cache name="USERNAME_TO_ID_CACHE"
           maxElementsInMemory="20000"
           eternal="false"
           timeToLiveSeconds="86400"
           timeToIdleSeconds="3600"
           overflowToDisk="false"/>
```

**Comment by evernat** [comment]
First, since you said Ehcache, I suppose that you don't use javax.cache / jcache / jsr107.
And so, to have this display, you probably have caches with the same names in different cache managers.
You can check that by running the following code in your application:
```java
for (final CacheManager cacheManager : CacheManager.ALL_CACHE_MANAGERS) {
    System.out.println("CacheManager " + cacheManager.getName() + " " + Arrays.asList(cacheManager.getCacheNames()));
}
```
If verified, you probably have code in your app and / or Spring using both the default CacheManager instance and another one configured with a name in Spring for example. And in that case, the display in javamelody is as expected.

**Comment by evernat** [comment]
Note that the hibernate second level cache, using the default-cache manager as you said, may use the same ehcache.xml, which contains configuration to initialize USERNAME_TO_ID_CACHE and others.

**Comment by shaack** [comment]
thanks, with your hints, I found the solution, it was:

1. Set the property `shared`of the Main chacheManager "true"
```xml
    <bean id="cacheManager" class="org.springframework.cache.ehcache.EhCacheManagerFactoryBean">
        <property name="configLocation" value="classpath:ehcache.xml"/>
        <property name="shared" value="true"/>
    </bean>
```

2. User `SingletonEhCacheProvider` as the `hibernate.cache.provider_class`
```xml
    <prop key="hibernate.cache.use_second_level_cache">true</prop>   
    <prop key="hibernate.cache.provider_class">org.hibernate.cache.SingletonEhCacheProvider</prop>
```
