### ISSUE TITLE
removeSessionsWithChangedId() removes sessions instead of updating SESSION_MAP_BY_ID

### ISSUE THREAD

**Issue by lmalmeida** [javamelody/javamelody#933]
Question,
The SessionListener.removeSessionsWithChangedId clears entries from the SESSION_MAP_BY_ID, when invoked. This has a side effect that all sessions with changed IDs are removed from the list, meaning the number of sessions reported by javamelody is different from the actual number of sessions.
Any particular reason for the current logic (Removal all invalid) instead of updating the SESSION_MAP_BY_ID with the correct id's

**Comment by evernat** [comment]
No particular reason. #934 merged.
Thank you.
