### ISSUE TITLE
During Implementation  in Tomcat Apache server issue

### ISSUE THREAD

**Issue by anuragk6666** [javamelody/javamelody#935]
Hi ,I have follow all instruction what you do have mentioned for installation guide .but when i am trying to that url for monitoring i
 am facing issue  error is HTTP status 404 .
If i have miss any step please help me out.

**Comment by evernat** [comment]
There is almost zero information in your issue. This is 2% of the needed 100% for a valid issue.
You must say what you have done exactly and what is your application (java version, server version, struts or not, spring or not ...) and what url you use and what you except and what you see.

**Comment by evernat** [comment]
No information and no response from the reporter, so closing as invalid.
