### ISSUE TITLE
Deploying Javamelody to monitor Tomcat 9 Java application

### ISSUE THREAD

**Issue by vbeer008** [javamelody/javamelody#937]
Hi, 

I followed https://github.com/javamelody/javamelody/wiki/UserGuide#2-webxml-file to deploy javamelody-core-1.85.0.jar and jrobin-1.5.9.jar for my tomcat 9. The monitoring page was loaded successfully at the first time, then it will crash the tomcat instance with one error line in catalina.out file "X connection to localhost:10.0 broken (explicit kill or server shutdown)." 

Can someone please help as I would like to use javamelody to monitor the performance of our Tomcat application.

Thanks.
Regards,

**Comment by evernat** [comment]
I am not sure that the error is caused somehow by javamelody.
But if it is, I suppose that it is related with graph rendering and java awt fonts for graphs in particular.
So I suggest to start Tomcat with `-Djava.awt.headless=true` in bin/setenv.sh of Tomcat.

**Comment by vbeer008** [comment]
Ok. I will have a try again.

**Comment by vbeer008** [comment]
Hi Evernat, 

   The "-Djava.awt.headless=true" work like a charm!  :) 

   One more question, as my Tomcat is running HTTPS and could not see the http connection counter for HTTP session...  Is is something I have missed?

**Comment by evernat** [comment]
There is absolutely no différence for javamelody between https and http: javamelody monitors the same data.
I do not understand well what you said about "the http connection counter for HTTP session".
Do you mean that you don't have HTTP sessions graph?
If yes, perhaps you have forgotten to put the javamelody SessionListener in web.xml next to MonitoringFilter?
See https://github.com/javamelody/javamelody/wiki/UserGuide#2-webxml-file

**Comment by vbeer008** [comment]
Hi evernat,

The document mentioned to add the sessionListener before the description of the servlet. I have attached what I modified my web.xml with javamelody sessionlistener. May I ask your help to have a look the attacched web.xml file please? Am I doing it correctly? Thanks

**Comment by evernat** [comment]
The javamelody MonitoringFilter and the javamelody SessionListener are not in the right place.
Attached is the corrected one.
[web-1.txt](https://github.com/javamelody/javamelody/files/5096351/web-1.txt)

That said, I still do not understand well what you said about "the http connection counter for HTTP session".
What do you see ?

If you mean that the "HTTP sessions" graph is empty, maybe no user ever connects and creates an HTTP session in your webapp.

**Comment by vbeer008** [comment]
Hi Evernat, 
 
     Attached the JPEG of monitoring graph and as you can see, I am able to see the HTTP Hits per minute or HTTP mean times (ms) - 1  day, but HTTP sessions - 1 day is always empty. Also, if you look at the System Information section. "Nb of http session 0" and never get updated even I http session connected.
![JavaMelody_HTTP_session](https://user-images.githubusercontent.com/54382484/90641080-2569dd00-e274-11ea-9426-19eb367811ce.jpg)

**Comment by vbeer008** [comment]
Also, I have updated the web.xml file as your recommendation, but it didn't make any difference with / without the javamelody filter configured in the web.xml.

**Comment by evernat** [comment]
Ok, the HTTP sessions graph is empty and its mean is 0. It says that HTTP sessions are never created by users in your webapp (said otherwise, there are no JSESSIONID cookies created). And there are http requests executed, without creating HTTP sessions.
This is not an issue in javamelody, it is a characteristic of your webapp.

Closing since the issue with "X connection to localhost:10.0 broken (explicit kill or server shutdown)" is resolved.
