### ISSUE TITLE
Retaining agent stats for Jenkins kubernetes ephemeral agents

### ISSUE THREAD

**Issue by hokadiri** [javamelody/javamelody#938]
Hi, 
We use jenkins kubernetes plugin to spin up ephemeral agents. We're having an OOM issue on the ephemeral agents and would like debug it. 

But javamelody does not retain the stats of ephemeral agents once the build is completed. 

Is there a way to retain the agent stats?

**Comment by evernat** [comment]
In the Jenkins monitoring plugin, the live data in "System informations" (used memory, etc) is displayed for each agent in /monitoring/nodes. And the stored data (graph of used memory over time, etc) displayed in /monitoring/nodes is aggregated for all connected agents.
And for epheremal agents, there is no live data anymore when the agent is disconnected, so no live data is displayed anymore, sorry.
The best I can suggest is to refresh page you want, when the build is running.
