### ISSUE TITLE
关于文档Spring-boot jdbc 监控样例提供

### ISSUE THREAD

**Issue by hank583746309** [javamelody/javamelody#942]
目前没有很好的样例（文档）可以快速接入。
目前遇到监控jdbc信息为 0 或 NaN, 没找到文档可供参考。

**Comment by evernat** [comment]
In English please.
See https://github.com/javamelody/javamelody/wiki/UserGuide#7-jdbc in your case.

To write an issue give :
- what you see (screenshot ...)
- what you expect
- debugging logs at the bottom of the monitoring page

**Comment by hank583746309** [comment]
Thank you for your reply, I found the answer I want here: 
https://stackoverflow.com/questions/44974139/javamelody-with-spring-boot-and-hikari-datasource
