### ISSUE TITLE
I'm not able to configure log4j2 logging for JavaMelody

### ISSUE THREAD

**Issue by oosterholt** [javamelody/javamelody#947]
It seems JavaMelody isn't reacting on log4j2 configuration. I'm trying to let JavaMelody log to a Console appender with debug logging enabled, but I do not see any JavaMelody logging at all.

log4j2.xml:
```xml
<Configuration>
	<Appenders>
		<Console name="STDOUT">
			<PatternLayout pattern="%-5p %d{yyyy-MM-dd HH:mm:ss} (%c) %m%n"/>
		</Console>
	</Appenders>

	<Loggers>
		<Logger name="net.bull.javamelody" level="DEBUG" >
			<AppenderRef ref="STDOUT" />
		</Logger>
	</Loggers>
</Configuration>
```

**Comment by evernat** [comment]
First, most javamelody logs are when starting or when something goes wrong. Otherwise, it's normal to not have logs.

Then, do you have Logback on the classpath? (`ch.qos.logback.classic.Logger` and `org.slf4j.LoggerFactory` classes)
If yes, javamelody will use logback to log instead of log4j2. That's configurable, for example in system properties: `-Djavamelody.logger-class=net.bull.javamelody.internal.common.Log4J2Logger` or in WEB-INF/web.xml:
```xml
<context-param>
 	<param-name>javamelody.logger-class</param-name>
 	<param-value>net.bull.javamelody.internal.common.Log4J2Logger</param-value>
</context-param>
```
Is it ok for you?

**Comment by oosterholt** [comment]
Thanks for your tips. As seen in the question I have level 'debug' configured and so I do expect some logging. Especially when starting up.

There is no LogBack available and I even forced the Log4J2Logger, but still no logging loged.

To force logging, I configured a faulty 'storage-directory'. The following is reported in the web interface (/monitoring) in the 'Debugging logs' section:
> Sat Oct 17 15:14:36 CEST 2020     WARN     exception while collecting data: java.io.IOException: JavaMelody directory can't be created: /I/do/not/exist/_xyz

But still no logging in my configured console. Any other ideas?

**Comment by evernat** [comment]
I suggest to add a call to the javamelody logger in your webapp and debug with a breakpoint starting from there.
For example, in a JSP:
```
<% net.bull.javamelody.internal.common.LOG.info("test"); %>
```
with a breakpoint in the info method of the LOG class.

**Comment by evernat** [comment]
any news?

**Comment by evernat** [comment]
No response from the reporter, so closing as incomplete.
