### ISSUE TITLE
K8s - problem with changing host name

### ISSUE THREAD

**Issue by DcortezMeleth** [javamelody/javamelody#950]
Hi,

I have question about setting up javamelody in spring boot up run as pod in k8s cluster.

I set up javamelody with mainly default configuration, apart from storage-directory which is set to be saved on persistent drive. I thought that it would be enough to keep statistics history continuous. Unfortunately it's not enough, as k8s with every deployment of next versions, changes pod name (and subsequently host name) to my_app_name-#{some_random_hash}. If I understand correctly this is the main reason javamelody after restart refuses to continue old history (file is saved in persistent drive) and starts the new one.

Question here is can I somehow tell javamelody that this is still the same app, for example using some parameter? Or should I try to make pod name stable (not sure it's possible tho).

Thanks for help!

**Comment by evernat** [comment]
When you say my_app_name-#{some_random_hash} in the storage directory, #{some_random_hash} is in fact the hostname as found by the JVM in the OS configuration.
You can override my_app_name-#{some_random_hash} with a javamelody parameter `application-name`, if the default value does not suit you like in this case of dynamic hostname.

Given that you use spring-boot and I suppose the javamelody-spring-boot-starter, you can do that in your application.yml file (or application.properties). For example in application.yml:
```yml
javamelody:
  init-parameters:
    application-name: my_app_name_instance1
```
Or you can do that with a system property: `-Djavamelody.application-name=my_app_name_instance1`
