### ISSUE TITLE
Italian localization: error in the legend of the graphics

### ISSUE THREAD

**Issue by massimosala** [javamelody/javamelody#951]
Hi

For all the graphics, in the legend "millisecondi" should be corrected with "millesimi".

Millesimi: 1/1000, agnostic
Millisecondi: 1/1000 of second

![image](https://user-images.githubusercontent.com/20907433/96739236-da795c80-13bf-11eb-9955-1edde004608a.png)

**Comment by evernat** [comment]
Thanks for the issue.
It is fixed by c18de32 and ready for the next release (1.87).
