### ISSUE TITLE
Collector server: PKIX path building failed

### ISSUE THREAD

**Issue by KanagarajGanapathy** [javamelody/javamelody#953]
Hello Team,

We are using a collector server to manage the java melody configuration. we could able to configure the application deployed non GCP environment. When we try to add the application which is deployed in GCP we are getting the following error message. could you please help with this?
![collective_server_issue](https://user-images.githubusercontent.com/18610422/96994289-235d1c80-154a-11eb-9f07-a119f61e2682.PNG)

**Comment by evernat** [comment]
In the optional javamelody collector server, it seems that you try to add the monitored app with an URL like `https://...` and the SSL certificate of the monitored app is not valid. Probably it is a test certificate.

To workaround this, you need to add the certificate of the monitored app in the keystore of the JVM of the collector server.
For that, you can download [InstallCert.jar](https://github.com/evernat/InstallCert/releases/download/1.0/InstallCert.jar) and execute `java -jar InstallCert.jar <host>` with the host of the monitored app.
Or `java InstallCert [--proxy=proxyHost:proxyPort] <host>[:port] [passphrase]` if you need more options.

Then, with the `jssecacerts` file created in the current directory, you can [import the certificate in your system keystore](https://github.com/evernat/InstallCert) or you can use the `jssecacerts` file directly from the collector server:
`-Djavax.net.ssl.trustStore=path/to/jssecacerts -Djavax.net.ssl.trustStorePassword=changeit`

**Comment by evernat** [comment]
Is it ok for you?
By the way, I work 15 km from Renault at Guyancourt. Do you work there?

**Comment by KanagarajGanapathy** [comment]
thank you...Let me check the collective server.
yes, i worked in Renault at Guyancount, but now i am in INDIA working for Renault groups...I was staying in Billancourt,

I am getting another issue but it is not https.
![image](https://user-images.githubusercontent.com/18610422/97142525-c69a7580-1786-11eb-95d2-4bf956005e95.png)

**Comment by evernat** [comment]
The monitored app now returns HTTP 401, which you could see when calling the URL yourself in a browser.
If the monitored app asks user and password for basic auth, you can write the user and password in the URL when adding it in the optional collector server. For example of such an URL:
`http://myusername:mypassword@s0825aos.mc2.renault.fr:2022/sm2`

**Comment by KanagarajGanapathy** [comment]
> The monitored app now returns HTTP 401, which you could see when calling the URL yourself in a browser.
> If the monitored app asks user and password for basic auth, you can write the user and password in the URL when adding it in the optional collector server. For example of such an URL:
> `http://myusername:mypassword@s0825aos.mc2.renault.fr:2022/sm2`

yes, above config is working..Thank you
Let me check collective server correction based on your answer.

**Comment by KanagarajGanapathy** [comment]
> In the optional javamelody collector server, it seems that you try to add the monitored app with an URL like `https://...` and the SSL certificate of the monitored app is not valid. Probably it is a test certificate.
> 
> To workaround this, you need to add the certificate of the monitored app in the keystore of the JVM of the collector server.
> For that, you can download [InstallCert.jar](https://github.com/evernat/InstallCert/releases/download/1.0/InstallCert.jar) and execute `java -jar InstallCert.jar <host>` with the host of the monitored app such as `www.google.com`.
> Or `java -jar InstallCert.jar [--proxy=proxyHost:proxyPort] <host>[:port] [passphrase]` if you need more options.
> 
> Then, with the `jssecacerts` file created in the current directory, you can [import the certificate in your system keystore](https://github.com/evernat/InstallCert) or you can use the `jssecacerts` file directly from the collector server:
> `-Djavax.net.ssl.trustStore=path/to/jssecacerts -Djavax.net.ssl.trustStorePassword=changeit`

Hi, I have checked and could see one of the applications is already added in a collective server with https...  I am getting this error when I am trying to add the application is deployed in the GCP environment.  Is any specific config available for GCP env?
![image](https://user-images.githubusercontent.com/18610422/97152982-c2c31f00-1797-11eb-8766-b98362056994.png)

**Comment by evernat** [comment]
No, there is no specific config available for GCP env, because GCP is not different than other env.
Here it is basically an issue with java (the JVM of the collector server at http://....mc2.renault.fr:8080) trying to make an http request to a web app (the monitored webapp in GCP) on https. Nothing special for a java program to make a call on https. You can write a java program by yourself like `new URL("https://...").getInputStream()` and probably have the same issue with the SSL certificate given by the monitored webapp(s).

I suggest that when you have a valid configuration of the SSL certificate of the monitored webapp(s) and of the SSL certificates in the keystores of this simple java program, you can do the same for the keystores of the collector server.

**Comment by evernat** [comment]
Is it ok for you? Can we close this?

**Comment by evernat** [comment]
No response from the reporter, so closing.
