### ISSUE TITLE
Server is prompting credentials to authenticate

### ISSUE THREAD

**Issue by BrandonRiveraGodines** [javamelody/javamelody#955]
I implemented a basic login and it works fine, but it also asks for the server credentials, in this case WebLogic. How can I prevent it and only enter the JM __web.xml__ file credentials **authorized-users** section?.
![wl](https://user-images.githubusercontent.com/25398046/97369358-67199400-1872-11eb-92e6-4313c31a5d01.png)

`<filter>
<filter-name>javamelody</filter-name>
        <filter-class>net.bull.javamelody.MonitoringFilter</filter-class>
        <async-supported>true</async-supported>
        <init-param>
            <param-name>authorized-users</param-name>
            <param-value>user1:pass1</param-value>
        </init-param>
    </filter>`

**Comment by evernat** [comment]
I suppose that you can't have basic authentication from both javamelody and weblogic.
If you want basic auth from javamelody, I suggest that you disable basic auth from weblogic on this url, if it's possible in weblogic.

**Comment by BrandonRiveraGodines** [comment]
> I suppose that you can't have basic authentication from both javamelody and weblogic.
> If you want basic auth from javamelody, I suggest that you disable basic auth from weblogic on this url, if it's possible in weblogic.

Thanks, but which url?

**Comment by evernat** [comment]
> but which url?

all http requests of javamelody have the .../monitoring URL.

**Comment by evernat** [comment]
as you can see in the screenshot

**Comment by titoparizotto** [comment]
@BrandonRiveraGodines 
the suggestion for @evernat works.
To disable the basic authentication in weblogic to use in JavaMelody consult this [documentation  ](https://docs.oracle.com/cd/E92519_02/pt856pbr3/eng/pt/tfee/task_ConfiguringOracleWebLogicServertoDisableAuthentication-ad7e32.html?pli=ul_d72e130_tfee)

In short, go in config.xml in your server config and add enforce-valid-basic-auth-credentials = false

` <security-configuration xmlns:xacml="http://www.bea.com/ns/weblogic/90/security/xacml">
    <name>peoplesoft1</name>
    ...
    <node-manager-password-encrypted>{3DES}c/WblCLbZubUdNamvjN1sw==</node-manager-password-encrypted>
    <enforce-valid-basic-auth-credentials>false</enforce-valid-basic-auth-credentials>
</security-configuration>`
