### ISSUE TITLE
FreeDisk Space Chart

### ISSUE THREAD

**Issue by pawelgryzewski** [javamelody/javamelody#956]
Hi
Doues anyone know what data are displayed in this chart
![image](https://user-images.githubusercontent.com/74305257/98815731-e1781580-2427-11eb-9941-897f9736c73d.png)

As far as i've checked this data shows wrong data
![image](https://user-images.githubusercontent.com/74305257/98815832-079db580-2428-11eb-908d-b1e7b7b7f51b.png)

Thank You in advance

**Comment by evernat** [comment]
It is the free space (unallocated) of the partition of the tmp directory.
Recent javamelody versions also displays the usable space (available) next to the free space.
