### ISSUE TITLE
[Statistics of system error logs] not logging all the errors?

### ISSUE THREAD

**Issue by mvphjx** [javamelody/javamelody#957]
JavaMelody 1.85.0

    Logger logger1 = LoggerFactory.getLogger(this.getClass());
    Logger logger2 = LoggerFactory.getLogger("");
    @RequestMapping("/1")
    @ResponseBody
    public MsgObject forward1()
    {
        /**
         * not log？
         */
        logger1.error("logger1-test1");
        /**
         * can see in the [Statistics of system error logs]
         */
        logger2.error("logger2-test1");
        return this.buildMsg.buildError("test1");
    }

**Comment by evernat** [comment]
First, sorry for the delay.
yes, javamelody monitors logs at warn and error level and displays them in the Statistics of system error logs.

You seem to use either Log4j v1 or SLF4J and it is not known which implementation (Log4J2, Logback or java.util.logging) is used behind SLF4J.
And we have no idea of specific configuration of logs in your webapp.
So closing this issue as incomplete.
It would help much if you give the source of a simple project to show what you mean.
