### ISSUE TITLE
JDBC Removed Abandoned Connections Stay in Used Connections Monitor

### ISSUE THREAD

**Issue by matrenner** [javamelody/javamelody#967]
Using Tomcat with JNDI DataSource.
RemoveAbandoned is set to true. When a connection is removed due to exceeding the removed abandoned timeout it stays in Used JDBC Connections graph. Is this desired behavior? I would think if the connection was successfully removed that it would also be removed from the used connections statistics.

**Comment by evernat** [comment]
Yes, it is the desired behavior. If Tomcat cleans up jdbc connections with RemovedAbandoned after some configured timeout, javamelody should still say that it is used and the connection is still open in the database after all, to show that there was a problem. And abandoned jdbc connections is a severe problem in general.
By the way, if some SQL query on the jdbc connections was just long and longer than this timeout, javamelody will remove it from the used jdbc connections graph when the long query ends.

**Comment by matrenner** [comment]
Okay. Good to know. Thanks for the explanation.
