### ISSUE TITLE
[PDF generation]Programmatically generate PDF report

### ISSUE THREAD

**Issue by NicolasFelix** [javamelody/javamelody#972]
Hi evernat (or whoever answers me ;) )

Is there a way to ask for a periodic PDF report,
I mean _programmatically_ as I don't what to use the _monitor_ page (and available link top to this page).

I apologize if this information is available within the documentation, I didn't find it.

Have a gread day !
Nicolas

**Comment by evernat** [comment]
You can configure javamelody to send a pdf by mail each day or week or month: https://github.com/javamelody/javamelody/wiki/UserGuide#14-weekly-daily-or-monthly-reports-by-mail
Or you can call the PDF URL in the monitoring page.
There is no other api.
