### ISSUE TITLE
Release a Jakarta EE 9 compatible version

### ISSUE THREAD

**Issue by Thihup** [javamelody/javamelody#978]
The major change is the namespace change from 'javax' to 'jakarta'.
Is there any plan to release it?

**Comment by evernat** [comment]
Good.
Except it seems to be bugged:
```
mvn source:jar javadoc:jar package -DskipTests
...
[INFO] Input     [ /javamelody/javamelody-core/target/javamelody-core-1.87.0-SNAPSHOT.jar ]
[INFO]           [ /javamelody/javamelody-core/target/javamelody-core-1.87.0-SNAPSHOT.jar ]
[INFO] Output    [ /javamelody/javamelody-core/target/javamelody-core-jakartaee9-1.87.0-SNAPSHOT.jar ] (Explicit)
[INFO]           [ /javamelody/javamelody-core/target/javamelody-core-jakartaee9-1.87.0-SNAPSHOT.jar ]
...
[INFO] Input     [ /javamelody/javamelody-core/target/javamelody-core-1.87.0-SNAPSHOT-sources.jar ]
[INFO]           [ /javamelody/javamelody-core/target/javamelody-core-1.87.0-SNAPSHOT-sources.jar ]
[INFO] Output    [ /javamelody/javamelody-core/target/javamelody-core-sources-jakartaee9-1.87.0-SNAPSHOT.java-source ] (Explicit)
[INFO]           [ /javamelody/javamelody-core/target/javamelody-core-sources-jakartaee9-1.87.0-SNAPSHOT.java-source ]
...
[INFO] Input     [ /javamelody/javamelody-core/target/javamelody-core-1.87.0-SNAPSHOT-javadoc.jar ]
[INFO]           [ /javamelody/javamelody-core/target/javamelody-core-1.87.0-SNAPSHOT-javadoc.jar ]
[INFO] Output    [ /javamelody/javamelody-core/target/javamelody-core-javadoc-jakartaee9-1.87.0-SNAPSHOT.javadoc ] (Explicit)
[INFO]           [ /javamelody/javamelody-core/target/javamelody-core-javadoc-jakartaee9-1.87.0-SNAPSHOT.javadoc ]
...
```
Sources jar and javadoc jar do not have good names and do not have jar extension.
And the Java EE URLs are not migrated to Jakarta EE URLs in the javadoc.
By the way, Jakarta EE is supposed to be compatible from Jakarta EE 9 to later, so there is no reason for a migration tool to attach an artefact with a name like javamelody-core-jakartaee9-1.87.0-SNAPSHOT.jar: in my opinion, a name like javamelody-core-jakartaee-1.87.0-SNAPSHOT.jar is better. That's important for the names in Maven Central in the years to come.
You could create issue(s) in the tool 😄

**Comment by Thihup** [comment]
Sure! I'll open some issues. 

By the way, if I understood correctly,  you can configure the artifact name by changing the classifier in the configuration of the plugin. The classifier in the example is jakartaee9, but changing for `jakartaee` can help with artifact names.

**Comment by evernat** [comment]
> The classifier in the example is jakartaee9, but changing for jakartaee can help with artifact names.

True

**Comment by dabbabi** [comment]
Hi, is there any chance to bring javamelody to Jakarta ee in a dedicated branch soon? Thank you.

**Comment by dabbabi** [comment]
thank you @evernat for your reply. I think that jdk17 and jakarta ee 10 is not an option now. Is there any plan to deliver javamelody supporting those ones, please? If yes, when? Otherwise, does this means the end of javamelody?

**Comment by evernat** [comment]
@dabbabi jdk17, jakarta ee 10 now, the end of javamelody 😄 🤣 
Some javamelody users still use Tomcat 6, many thousands use Tomcat 7, Tomcat 8 or Tomcat 9. Java 17 is not the issue but is not much in use yet : Java 8 is still the majority of usage.

**Comment by walczakp** [comment]
Just asking out of curiosity, is there a plan to maintain Jakarta EE release now that Spring 6 has it's official release?

**Comment by candrews** [comment]
> is there a plan to maintain Jakarta EE release now that Spring 6 has it's official release?

[Spring Boot 3 was released in November 2022](https://spring.io/blog/2022/11/24/spring-boot-3-0-goes-ga) and it uses `jakara.*` (not `javax.*`) meaning that Java Melody doesn't work with applications using the current version of Spring Boot.

Also notably, [Spring Boot 2.x goes end of life in 2023-11-18](https://spring.io/projects/spring-boot#support) - just 9 months from now. At that time, unless this issue in JavaMelody is resolved, there will be no way for an application using a supported version of Spring Boot to use JavaMelody.

**Comment by rPraml** [comment]
Hello, we have developed together with the maintainer of [ebean](https://github.com/ebean-orm/ebean) a solution, that makes maintaining a jakarta release easy:

Steps to release:
1. Release the javax version with maven release plugin
2. Check out the released commit with `git checkout HEAD~1`
3. change the version in all poms with `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=X-jakarta`
4. Run the javax-to-jakarta translation: https://github.com/ebean-orm/ebean/blob/master/jakarta-to-javax.sh - this script does a search & replace in source code and swaps out some dependency-blocks in the pom.xml
5. Run `mvn clean source:jar deploy` or whatever to build and deploy the current modified code 
6. discard all changes

What means this to javamelody:
- modify the pom files, so that they have the correct dependency-blocks
- identify, if there are some special cases and if so, handle them in the translation script (e.g. comment blocks in java libs)

**Comment by evernat** [comment]
javamelody-core and javamelody-spring-boot-starter 2.0.0 are now released and are compatible with Jakarta EE 9 such as Tomcat 10 and with Spring Boot 3.
