### ISSUE TITLE
Prometheus scraping error : m/metrics: reading text format failed: text format parsing error in line 1: invalid metric name

### ISSUE THREAD

**Issue by ktdharan** [javamelody/javamelody#981]
Hello , 

We are currently evaluating the process of scraping Metrics using the Prometheus end point from Jenkins java melody plugin . trying to achieve this by using the telegraf prometheus input plugin (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/prometheus ) 

It seems there is problem in the exposed Prometheus format , we keep running into the error when trying to scrape the metrics 

 Error in plugin: error reading metrics for http:<Jenkins -url>?path=/custom/metrics: reading text format failed: text format parsing error in line 1: invalid metric name 

Wanted to check if this is something  if anyone has experienced

**Comment by evernat** [comment]
I suppose that you have installed the javamelody monitoring plugin in Jenkins.
You need to call `<Jenkins-url>/monitoring?format=prometheus` to have prometheus metrics from the plugin. Have you done that? And does this url returns prometheus metrics as expected when called in a browser?
Is it needed to authenticate in your Jenkins ? If yes, you will probably need to disable authentication in the plugin (system property `-Djavamelody.plugin-authentication-disabled=true`) and then to enable basic authentication for example in the plugin (system property `-Djavamelody.authorized-users=myusername:mypassword`).
