### ISSUE TITLE
possibly a memory leak in net.bull.javamelody.internal.model.RrdNioBackend.fileSyncTimer

### ISSUE THREAD

**Issue by jdielemans** [javamelody/javamelody#986]
Hello, 
we are using Javamelody 1.8.5 for each of our applications, running on a Tomcat server.
The tool gives us a lot of information about possible problems in our code. 
Today i have used the option to Generate a heap dump and we have analyzed it with jxray.

One of the thing the tool does, is checking for Gc roots.  Strange thing that one class is using a lot of memory. 
Can this indeed be a leak, or does JavaMelody cache a lot of statics details (like sql statements)? 

![jxray01](https://user-images.githubusercontent.com/58222384/105042363-70c32a00-5a64-11eb-8a55-eaddfc59013a.PNG)

![jxray02](https://user-images.githubusercontent.com/58222384/105042373-73be1a80-5a64-11eb-962f-79c893e97cf4.PNG)

Greetings, Jeroen Dielemans 
DMG

**Comment by evernat** [comment]
Yes, this timer keeps some data. That is data for latest graphs in a pool and it is the same timer that keeps in memory statistics of http and sql requests (statistics and not all hits). That's normal and not a memory leak. The quantity of in memory statistics depends on the number of requests in the monitoring page and is limited in size.
