### ISSUE TITLE
After enabling JAVA Melody to springboot application Oracle DB write transactions caused ORA-600 error

### ISSUE THREAD

**Issue by somanathyadav** [javamelody/javamelody#988]
I was trying to see JAVA melody working on my SpringBoot application.
But after putting those jars as dependency, my DB transactions to write in Oracle DB stated throwing ORA-600 error.

After removing those javamelody jars dependency my code works well.

Is Javamelody doing something wrong with the DB driver or SQL code?

**Comment by evernat** [comment]
Of course, javamelody is not doing anything wrong with the DB driver and it does not change anything to SQL queries.

ORA-600 may be internal issues and bugs in Oracle database.
I suggest to look what's up with your database.
See for example:
- https://blogs.oracle.com/db/ora-600-troubleshooting
- https://www.orafaq.com/wiki/ORA-00600
