### ISSUE TITLE
javamelody we don't see any ip address,browser,country and user information.user session are increased high(2000 to 3000) and after 10 mints it'll reduces  normal session 300 to 600.

### ISSUE THREAD

**Issue by AppalanaiduMetta** [javamelody/javamelody#989]
in my application we are using javamelody. we are facing below issue.
 **we don't see any ip address,browser,country and user information.user session are increased high(2000 to 3000) and after 10 mint it reduces  normal session 300 to 600.**

![image](https://user-images.githubusercontent.com/11383834/105504450-c9592800-5ced-11eb-9c4e-ef293d85797d.png)
..could  you please help me .

**Comment by evernat** [comment]
You may want to look at the Http Sessions page. There is a link the System informations chapter of the monitoring page.
