### ISSUE TITLE
Filters are not working for charts

### ISSUE THREAD

**Issue by malivijay** [javamelody/javamelody#992]
When I click on the **Choice of period**  filter, filters are getting applied only on Statistics but on charts it always shows 1 day result for charts.
Please check the screenshot.
<img width="1749" alt="javamelody" src="https://user-images.githubusercontent.com/78797530/107359638-ee75d500-6afa-11eb-950f-47d9b046496e.png">

**Comment by evernat** [comment]
The reports use a cookie to change the period.
- Are you using MS IE as a browser and does your server hostname contains an underscore ('_') ? If yes, you have a problem: https://stackoverflow.com/questions/21012559/issue-with-session-and-cookie-in-internet-explorer-for-websites-containing-under
- Are you using a reverse proxy in front of your application server and are your URLs rewritten by the reverse proxy? If yes, the path in the cookie will not match the path of the URL in the browser (check the cookie content in your browser). So the cookie will not be sent back to the server and the period change will do nothing. And you can see that the choosen period works when accessing the monitoring on the application server directly without using the reverse proxy. So, you need that the reverse proxy rewrites the path of the cookie like it rewrites the path of the URLs. For example, when using Apache httpd as reverse proxy, it's quite simple by using mod_proxy's top ProxyPassReverseCookiePath directive: http://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypassreversecookiepath

**Comment by malivijay** [comment]
@evernat 
We are not Internet explorer and also there is no "_" in our hostname. Still after loading the javamelody URL I can see "_" is automatically added to the host fqdn. 

Also we tried without proxy redirection (Directly accessing from tomcat server), Still we are facing the same issue.

**Comment by darioseidl** [comment]
I was facing the same problem, behind an nginx reverse proxy with `location /tomcat/`.

As a quick workaround, editing the cookie in Firefox, changing the cookie path from "/monitoring" to "/tomcat/monitoring" (and then changing the value manually to the time period) works.

Then this fixed it in the nginx config:

```
    location /tomcat/ {

        proxy_pass http://tomcat:8080/;

        # Rewrite javamelody cookie path
        proxy_cookie_path /monitoring /tomcat/monitoring;
    }
```

**Comment by darioseidl** [comment]
Hmm, somehow this has stopped working for me. I see the "set-cookie" header with the correct path:
```
	"Response Headers (1.173 kB)": {
		"headers": [
...
			{
				"name": "set-cookie",
				"value": "javamelody.period=semaine; Max-Age=2592000; Expires=Fri, 01 Nov 2024 11:02:41 GMT; Path=/tomcat/monitoring; SameSite=None"
			}
...
```
but no cookie is created. I tried in Firefox and Chromium. Maybe it's a problem on my side, I'll keep looking ...
