### ISSUE TITLE
Increases the number of sessions consistently on each call to the JSP with tags for Prometheus.

### ISSUE THREAD

**Issue by jolr** [javamelody/javamelody#997]
Using the example shown in the [advanced guide](https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#jsp-tags-for-prometheus), it happens that new HTTP sessions are created for each scrape made by Prometheus.

This is solved by setting in the JSP:
`<%@ page session="false"%>`

Here is an example of before and after implementing the change:
![javamelody_tags_prometheus](https://user-images.githubusercontent.com/30478463/111782357-371e6c00-88b9-11eb-9b6a-9bc4215ede0f.png)

**Comment by evernat** [comment]
Yes, indeed.
I have updated the example: https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#jsp-tags-for-prometheus
Thank you
